### ISSUE TITLE
New design migration: AJAX scroll mechanism within thread

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#1000]
The new design will have a better mechanism for loading messages, which is in line with modern interfaces like Messenger.

The page will show the unread messages onwards, and scrolling up will dynamically load earlier messages.

I would like to get as much of this mechanism of this working on the current site, to lower migration efforts. If necessary this can use a 'load earlier messages' button rather than detect a scroll up.

**Comment by nikolai-b** [comment]
I've put a very very rough implementation of this up on staging to check it is the direction you are after.

**Comment by mvl22** [comment]
Yes, that's going in the right direction - thanks.

As you say it's a bit rough at the moment, e.g. there's an off-by-one bug I think as I get a blank message, but do keep going.

I think we need to work on the assumption that it's likely that a few messages above the current will want to be seen more immediately, rather than having to wait for them, so they should probably be included in the initial load. Recent messages will often be scanned by a user to provide a quick reminder of the context of the so-far unread messages.

**Comment by nikolai-b** [comment]
I don't think loading 100 should be that slow.  I checked some of the largest threads, e.g.  /threads/500 which has 1108 messages on the copy I am testing it on, and it loads in under 800ms.  I've also increased the initial load so we load all the new messages and 10 seen messages.  We can play with the numbers but it should be ready for another test on staging.

**Comment by nikolai-b** [comment]
@mvl22 let me know when you have had a look and we can get this merged.  This [won't work on IE 11](https://caniuse.com/?search=IntersectionObserver) without a [polyfill](https://github.com/w3c/IntersectionObserver/tree/main/polyfill), which is easy enough to add, just to check we do want to support IE 11 even though [Microsoft will stop supporting it](https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/) on 2022-06-15

**Comment by mvl22** [comment]
Yes, please include the polyfill. I doubt we have many IE11 users, but it's sensible not to cut them off in advance of the new design migration.

**Comment by mvl22** [comment]
Could we avoid having two spinners - just one at the start is enough:

![Screenshot 2022-01-05 at 17 02 21](https://user-images.githubusercontent.com/361423/148258668-ee0f3f67-0d7d-4318-9539-e90b15308a96.png)

Is this supposed to load *everything* before, or just say 20 at a time? I noticed on /threads/832 it's a very long wait because it's loading hundreds. I think progressively at a time, as per FB Messenger, would avoid that problem.

**Comment by nikolai-b** [comment]
I've changed it to progressive loading (40 at a time) and cut the spinners down to one.  I've also added the polyfill.  I'll deploy soon unless I hear otherwise.

**Comment by mvl22** [comment]
Thanks - looks good to go.

**Comment by nikolai-b** [comment]
Done in 34afd3ebb973792a7b6e7e9f9dadeadd8d605af6 and commits around it.

**Comment by mvl22** [comment]
Well done, thanks for your work on this.
