### ISSUE TITLE
New design migration: Replace thread 1-5 priority system with simple favouriting

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#1001]
Currently the site has a system whereby threads can be given a 1-5 rating. This is over-complex, resulting in less use.

The new site will replace this with a simpler starring system.

I would like to get as much of this mechanism of this working on the current site, to lower migration efforts.

Firstly, can you confirm that the database shows this mechanism isn't really being used at present and is therefore safe to remove?

(The 1-5 rating system is quite a 2010 approach, in the days when things like MP3 players like iTunes had 1-5 ratings, whereas user research has presumably shown now that simple starring is quite sufficient.)

Data migration-wise, I suggest that any thread marked 3-5 should be treated as a starred thread.

UI wise:

- The box 'My Thread Priority' should be removed.
- In its place, a simple button [☆ Favourite], grayed out by default. Clicking on this saves this to the database via AJAX, and turns the star gold, and the word Favourite to be black. Design can be very basic - just a line round this with a bit of padding is fine.
- On /overview, the list of threads should have an additional column at the end which has a star, again gray by default becoming gold.
- Ditto /threads
- The listing at /overview#my-priorities can be replaced with a static listing of 'My favourited threads'

**Comment by nikolai-b** [comment]
@mvl22 let me know if you are happy with the staging site and I'll deploy this.
