### ISSUE TITLE
Odd right click pop up box

### ISSUE THREAD

**Issue by soundplusfury** [cyclestreets/cyclescape#1027]
As you can see (hopefully.) I was expecting the spellchecker to appear. Is this a Firefox (vs 101) issue or a Cyclescape issue, though? 
![cyclescape-prob](https://user-images.githubusercontent.com/77234589/174455169-d92b3d1d-dd1f-4d92-a226-1aac620b8983.png)

Just to clarify this, I can't copy and paste anything either. If it uses a right click, this is what comes up.

**Comment by soundplusfury** [comment]
Still happening, sadly. I can c+p from the Edit menu in the browser toolbar but not by right clicking.

**Comment by soundplusfury** [comment]
Though all is well using the Feedback form. (Used for other, non github related stuff, btw.)

**Comment by mvl22** [comment]
Most richtext editors give a context menu like this, rather than the usual browser spellcheck/etc. menu. Ideally this would indeed not happen. Just a single add-link option isn't really that helpful, it's fair to say.

**Comment by soundplusfury** [comment]
Thing is, this is the only site I use that it happens on. If a solution does present itself that would be great, but I half expect it's some bit of unrelated code somewhere that had a knock on effect and it would be a needle in haystack job to find it.

**Comment by soundplusfury** [comment]
Spellchecking is go, once more.
