### ISSUE TITLE
Some threads still showing as unread after reading

### ISSUE THREAD

**Issue by soundplusfury** [cyclestreets/cyclescape#1032]
This only seems to a problem with Vivaldi on my tablet. I have refreshed the page. I logged out. I logged back in hours later. Still unread.

**Comment by mvl22** [comment]
Could you give a specific thread number, so we have an example to look at?

**Comment by soundplusfury** [comment]
So of course, I report it and then as if by magic (not magic - tech stuff from somewhere) it's fine again. As you were.

**Comment by nikolai-b** [comment]
Sadly not by magic.  @mvl22 in our error reporting we were getting `NameError: uninitialized constant ThreadRecorder::ThreadView` and (`ActiveJob::DeserializationError: Error while trying to deserialize arguments: uninitialized constant Message`) for some reason in the background jobs (resque).  I restarted resque on the server and it seems to be fixed but I'm not sure what was happening.

**Comment by soundplusfury** [comment]
(I know it isn't magic. I was being daft.) But to report #892 is doing the same thing in Firefox now.

**Comment by soundplusfury** [comment]
Also #5261. It will clear after about three refreshes, I think, so it's not quite so bad, but still odd.

**Comment by soundplusfury** [comment]
Add #5115 too. This one's being pretty stubborn. I'll stop there.

**Comment by nikolai-b** [comment]
Ha, I didn't mean to suggest you really thought it was magic, just that sometimes these problems crop up and _magically_ fix themselves.  I've no idea why this is happening but I've update the background worker and re-deployed :crossed_fingers: that fixes it.

**Comment by nikolai-b** [comment]
Closing as I think this was related to a deployment.
