### ISSUE TITLE
Search result page

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#105]
A few usability fixes here, after a month or two of usage:

1) I'm finding that the issues tab is actually far more helpful, as it is more visual and the maps aid quick recognition of the issue being wanted. So I think should be made the default (first) tab.

2) The tabs could do with the number of results in their label, e.g. something like:
Issues (2)  ||  Threads (5)  ||  Library (0)

3) In group subdomain context, the issues tab seems to pick up stuff outside the group's area, which is going to become problematic as more groups get loaded. It should have the same limitation as per the standard issues list (but obviously just limited to the text searched for), plus a link "You can also _search for issues beyond %groupname's area_".

**Comment by smsm1** [comment]
Feedback 1645 notes that there is a limit of only 20 issues on the tag search page. Should this be tackled as part of this issue, or should a new separate issue be opened. I thought one already existed, however couldn't find it.

**Comment by smsm1** [comment]
See also the feedback at https://twitter.com/mattturnersheff/status/633911921461329920 re the 20 results limit.

**Comment by nikolai-b** [comment]
Tags are done 2f0cfdf1b64 and there have been many commits related to implementing solr, our new search infrastructure.
