### ISSUE TITLE
Allow editing of an issue just after creation

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#108]
If you make a minor error in text of the drawing of the geometry of an issue, you have no way of being able to change it. Could having a limited time or allowing admins to edit issues be useful. I can see the need where something is said that needs to be removed, or say personal information is included and needs to be removed.

**Comment by nikolai-b** [comment]
Issues can be edited for longer than 24 hours now.

**Comment by mvl22** [comment]
What is the time limit, if any, now? Would be useful to have a definitive statement here.

**Comment by nikolai-b** [comment]
You asked to release the restriction in #506 so it is unlimited.
