### ISSUE TITLE
Private messages sending crash

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#1083]
Posting to:
`/users/USERID/private_messages`

gets:
`We're sorry, but something went wrong.`

I see Rollbar sent a report at the time:

```
[cyclescape] production - New Error: #685 Pundit::NotDefinedError: unable to find policy `NilClassPolicy` for `nil`
```

**Comment by soundplusfury** [comment]
It may not be related but I got that message when I tired to search for a planning application.

**Comment by nikolai-b** [comment]
Should be fixed in https://github.com/cyclestreets/cyclescape/commit/9188a738a5536d9d7182c253fd708b20b1f7f88b
