### ISSUE TITLE
Turnitin bot filling logs with errors

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#116]
The turnitin bot is trying to crawl the issue voting links. Since it makes get requests, no route matches, and nothing untoward happens, other than filling the logs with errors. This makes it harder to investigate genuine problems.

We should consider some robots.txt action, or investigate if there's a better way to deal with the links. Normal users send post request via UJS magic.

**Comment by nikolai-b** [comment]
Not really an issue now
