### ISSUE TITLE
As an admin I should be able to confirm group membership requests

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#145]
Currently as an admin I'm unable to confirm group membership requests as it just returns a not authorised error of "You are not authorised to access that page." for the url of the pattern: 
http://<group>.cyclescape.org/groups/<group>/membership_requests/<id>/confirm

**Comment by nikolai-b** [comment]
Not really sure we want this.  It feels like this power is fine with group committee members. I'm closing this as there hasn't been any activity for 3 years.
It can added easily so re-open if required.

**Comment by mvl22** [comment]
Agree. There hasn't been any requests for sysadmin intervention in three years that I can recall. Committee members seem to manage fine.
