### ISSUE TITLE
Promote this thread via social buttons

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#151]
Easy ways to tweet, mail and encourage people to promote a topic in other social networks.

**Comment by mvl22** [comment]
Currently this only exists on an issue page (where it is hidden away and needs to be moved up), but should be on thread pages too.

e.g.
http://www.cyclescape.org/issues/1881-groningenisation-of-farncombe

would also have same buttons on its component thread pages:
http://www.cyclescape.org/threads/2070
http://www.cyclescape.org/threads/2071

There needs to be a Facebook share button alongside the twitter one.
