### ISSUE TITLE
Search result tuning - thread title should have increased relevance

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#158]
After several months of using the search, it's clear it needs a bit of tuning.

The main thing is to increase the relevance of the thread title in the thread search.

For instance:
http://camcycle.cyclescape.org/overview/search?query=catholic+church

finds 16 threads, but the two threads with 'catholic' and 'church' in them are buried somewhere in the list. These should clearly have greater relevance to the appearance of those words in just the text themselves.

This change would also provide an incentive for group admins to keep thread titles clean and descriptive.

**Comment by mvl22** [comment]
Traits that should increase rankings are:

1) Presence in title (works nicely), 2x currently
2) Presence as a phrase when more than one word (probably doing this automatically)
3) Threads with recent postings are more relevant than old ones, 1.5x maybe
4) Maybe: Number of postings, 1.2x

**Comment by nikolai-b** [comment]
1-3 have been done, I'm closing now but please re-open if you want to do 4.
