### ISSUE TITLE
Setting a priority should use a one-click radiobutton set

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#16]
At present, setting a priority on a thread involves using a select drop-down and then pressing a button.

This feature is something that we want people to be able to use for many threads so this becomes a more useful feature. Accordingly, it should not require much effort.

Therefore, this should changed to be a set of 6 radiobuttons:

     X          X        X        X           X                      X
    Very low   Low    Medium    High      Very high            No priority

Clicking should immediately set the priority via Ajax, which (for accessibility) should override and hide a standard submit button under the radiobutton set and intercept the post.

Default should be No priority. It should not be 'Medium' as people should only set a priority for things they are actually interested in.

In particular, it must have the ability to unset the existence of a priority, as otherwise the priorities list grows and grows, accumulating things which have already been dealt with and therefore not even the lowest-possible priority.

**Comment by mvl22** [comment]
I think in the future we should migrate to a starring system, but for now, I'd like to get this section of the UI cleaned up so that it at least works more smoothly, and so that the CSS layout of the box on the thread page looks much cleaner - it's basically never been styled.

**Comment by nikolai-b** [comment]
Done in 77efd1ddcbe8 do you want to me to push it to staging (cs5)?

**Comment by mvl22** [comment]
> do you want to me to push it to staging (cs5)?

Yes, please.
