### ISSUE TITLE
Deadline/date should show day name also

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#161]
Minor reformatting:

"18 January 2013"
->
"Friday, 18th January, 2013"

This is a problem at:
on the deadline listing: /overview#deadlines
on a thread page, e.g. /threads/2140

**Comment by rbazinet** [comment]
@mvl22 can you provide a way for me to see this?  My deadlines tab is blank, not sure how to populate this tab.

**Comment by mvl22** [comment]
If you go into any thread page, i.e. ```/threads/<id>/```, then scroll to the end of the discussion, then click 'Date/deadline', you'll be able to post a date/deadline.

(We're planning to redo this interface, as it's harder to find than it should be, as you've found!)

**Comment by rbazinet** [comment]
@mvl22 LOL..no, it wasn't obvious. I've got it now. Thank you.

**Comment by rbazinet** [comment]
@mvl22 does this format work for you?
![cyclescape](https://cloud.githubusercontent.com/assets/170/12340708/86681704-baea-11e5-83eb-ed641c54e701.png)

**Comment by mvl22** [comment]
Much nicer, thanks.

**Comment by rbazinet** [comment]
@mvl22 great! This is now committed to the issue-161 branch.

**Comment by mvl22** [comment]
@nikolai-b Ready to merge I believe.

https://github.com/cyclestreets/cyclescape/commits/issue-161

**Comment by nikolai-b** [comment]
Looks fixed by #498
