### ISSUE TITLE
Show thread number on the page

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#162]
The beta group (Camcycle) often refers to "thread XXX" during its conference calls. This is only shown in the URL.

Would be good to show the thread number on the page for easy reference, as:

`Thread #xxx`

**Comment by rbazinet** [comment]
@mvl22 the issue title says "Show thread number on the page". Which page? Please provide some details.

**Comment by mvl22** [comment]
Sorry, yes, not a very clear spec! The thread number should be shown on each thread page, i.e. ```/threads/<id>```

I've done a quick mockup, and I think you can probably use the styles shown, though obviously putting that in the stylesheet rather than directly in the HTML:

![screen shot 2016-01-14 at 22 24 26](https://cloud.githubusercontent.com/assets/361423/12339620/e122a56a-bb0d-11e5-9d6e-8209a6fb2fc8.png)

**Comment by rbazinet** [comment]
@mvl22 thank you. It was probably version obvious to you when you added this issue. :-) I will take care of this. I appreciate the great mockup.

**Comment by mvl22** [comment]
Yeah, sorry quite a few of the tickets here it seems aren't quite as self-explanatory as I had thought.

**Comment by rbazinet** [comment]
@mvl22 this is complete and committed to the issue-162 branch.

**Comment by mvl22** [comment]
@nikolai-b Think this is ready to go:

https://github.com/cyclestreets/cyclescape/commits/issue-162

**Comment by nikolai-b** [comment]
Fixed in #497
