### ISSUE TITLE
Thread/issue URLs need a canonicalising redirect if the slug does not match

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#163]
http://camcycle.cyclescape.org/issues/36-cycle-parking-at-the-station
is the correct URL for issue 36.

However, fiddling with the slug does not redirect to that:
http://camcycle.cyclescape.org/issues/36-car-parking-at-the-station

Clearly there is potential for abuse, as happened with this high-profile case:
http://www.shinyshiny.tv/2011/04/fiddling-around-with-urls-indpendent-kate-middleton-jellybean.html

Note that lack of a slug does produce a working page:
http://camcycle.cyclescape.org/issues/36
and that too should redirect to the full version with the slug included.

**Comment by rbazinet** [comment]
@mvl22 can you please verify this problem? I have tested with the URL you gave in the original issue. I tested all of these URL's and all work fine:

http://camcycle.cyclescape.org/issues/36-car-parking-at-the-station
http://camcycle.cyclescape.org/issues/36

As long as /36 is at the beginning of the slug...all of my tests worked.  Maybe this has been resolved already?

**Comment by mvl22** [comment]
I think you may have misunderstood the problem. I'm not sure how to explain it any more clearly than the title and description above - do have a good re-read.

The key point is that, in the case of that issue (36) above, the correct local part is:
```/issues/36-cycle-parking-at-the-station```

But you can request
```/issues/36-something-very-rude```
and it will still work. We don't want URLs like that being circulated.

**Comment by mvl22** [comment]
Note that it's important that the domain (whatever.cyclescape.org / www.cyclescape.org) and http or https is maintained as per the typed-in address. It's only the REQUEST_URI part that needs to be canonicalised.

**Comment by rbazinet** [comment]
@mvl22 ok, I thought you wanted people to be able to change the slug but as long as the id was there, still go to the correct issue. I understand now.

**Comment by rbazinet** [comment]
@mvl22 this is fixed and in branch issue-163.

**Comment by mvl22** [comment]
@nikolai-b Can you merge into staging so I can approve? Thanks.

**Comment by nikolai-b** [comment]
Fixed in #496
