### ISSUE TITLE
Reply type which sets the 'leader' of an issue

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#169]
Clear requirement from the Camcycle group to be able to set any discussion to have an identified leader.
- Leader can be set as a reply type
- Leader is shown clearly on the page (at the top, and in the list of people) in the thread
- 'I'm leading' tab in My Cyclescape

**Comment by nikolai-b** [comment]
Can we scale this back to a message thread having a leader (and remove the follower, doer and other roles for now)?  In which case, does a thread have only one leader?  Who decides?  I'm not quite clear on all the intricacies around this.

**Comment by mvl22** [comment]
> Can we scale this back to a message thread having a leader

Yes, that's fine. I think that's all that's come up in recent discussions - I agree that in retrospect the other types seem over-complex. We should put in Leader and I can then seek feedback from the group once that's in place.

> In which case, does a thread have only one leader?

I haven't been given a clear spec by the group, so I think we should probably keep this simple and just allow anyone to self-declare themselves, and allow more than one. I think that if two or even three people come forward and declare themselves as co-leaders, that is a positive thing in that it shares the load a bit.

@roxannedebeaux is good at these kinds of process things and may have suggestions.

I would forsee an interface as follows:

* Add this new reply type as another icon tab alongside Text, Photo, Street View, etc.
* Call it 'Leader' or similar
* Clicking on that new tab gives basically a brief summary of what the Leader is expected to do, e.g. "The Leader of an issue takes on responsibility for ensuring that discussions continually move forward and that actions are carried out and followed-up." It would also show any current Leader(s) and then have a button to set oneself as a Leader. There would be a short comment after the button that setting as Leader will inform others. (This should help avoid trivial on/off switching).
* When the user is currently a Leader, the Leader tab would have the same text but the button would be a 'Remove myself as Leader'.
* When either the on or off button scenario is pressed, this results in a reply being shown in the same way as other reply types, and an e-mail emitted similarly, e.g. "Jane Smith set themself as the Leader of this issue. They will take on responsibility [... then text same as above for consistency].

Do you think that would work?

If this doesn't prove enough we can put more controls in place, but I think this would be a workable first iteration and I suspect will work fine for the long term.

**Comment by roxannedebeaux** [comment]
I think this is a good move forward.

One thing I would really like to see is a floating box on each cyclescape thread with the most important details including:
- Leader
- Upcoming deadlines
- Tasks to be done/stage of the critical path (on my wish list). 
- Relevant documents or links

This box should always be visible even when scrolling down the thread. The way I use cyclescape makes it hard to find these relevant details without scrolling up and down the thread. 

I think there are also next steps after applying these features which is being able to allocate tasks on a critical path. The role of leader will be important in this. 

I will need to let this idea marinate for a while and think about how to use the 'leader' feature and what requirements there may be.

**Comment by jf1** [comment]
+1 for @roxannedebeaux's 'floating box' idea, although ideally the confusion caused by having 1) an issue title; 2) an issue description; and 3) a first discussion post (as described in #587) should be tackled first or simultaneously.

+1 for most of @mvl22's suggestions too...
I'd call the tab 'Leadership' as this name also works for withdrawing yourself as leader.

More importantly, I think people should 'Offer to lead on this issue' then a committee member should approve/choose the leader. Perhaps a simple way to implement this initially would be to only allow committee members to be the leader of an issue.
The reply/email text could be "Jane Smith offered to be the Leader of this issue." then "Fred Bloggs offered to be the Leader of this issue." then "John Doe appointed Jane Smith as the Leader of this issue."

But -1 for adding "They will take on responsibility [... then text same as above for consistency]" to each reply/email as I feel this is better detailed once, elsewhere, eg with a pop-up and/or link on the text "Leader" in the 'floating box'

**Comment by mvl22** [comment]
> Perhaps a simple way to implement this initially would be to only allow committee members to be the leader of an issue.

I think this should be avoided - it basically militates against ordinary membership getting more involved, which is surely something most groups would want more of.

> But -1 for adding "They will take on responsibility [... then text same as above for consistency]" to each reply/email

I was suggesting this happens only once - when it happens. This is about e-mails to other people. Without this, people who use the site via e-mail would be disadvantaged, and this breaks the consistency with all other reply types.

**Comment by mvl22** [comment]
> This box should always be visible even when scrolling down the thread.

This is a layout thing which we should address as part of #591.

**Comment by jf1** [comment]
> If it becomes a problem, a second iteration could add more controls

A simple control could be the ability for committee members to "de-select" the leader of an issue. I hope this would never be needed but can envisage times - eg if an issue leader becomes ill, busy or uninterested - when it'd be useful.

> This is about e-mails to other people. Without this, people who use the site via e-mail would be disadvantaged

To clarify, it's only the extra "They will take on responsibility [... then text same as above for consistency]" text I was giving a -1 to. I support the suggestion to send an email with the "Jane Smith set themself as the Leader of this issue" section.

**Comment by mvl22** [comment]
I've had a look at the pull request - thanks.

Well it seems to work, but I remain of the view that the UI isn't really right. It's hidden in the top-right and I think only a determined person will really discover it.

1) I still think it should be a new reply type, which gives the benefit of it being in the flow of the discussion and also gives the space to explain what a leader means.

2) Setting as leader doesn't seem to get indicated as a reply, i.e. "Jane Smith set themself as the Leader of this issue. They will take on responsibility for ensuring that discussions continually move forward and that actions are carried out and followed-up"

3) Currently we end up with two boxes: Leading this thread and Following this thread. The latter already has a system of colourising a 'special' box, i.e. the owner. So we should just extend this principle to show the Leader, under the Owner, in that same listing.

**Comment by nikolai-b** [comment]
I've updated this.  Probably my fault but it turned out to be a total re-write.  Probably it makes sense for me to put a (very basic Photoshop) UI mock up to avoid me going down the wrong path.
Anyway, please have another look.
