### ISSUE TITLE
Priorities list should enable direct settability

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#17]
The My priorities list in My Cyclescape at
http://camcycle.cyclescape.org/overview
(third tab) needs the ability to set the priorities for an item directly.

This should use the same radiobutton set as proposed in issue #16.

In particular, it must have the ability to unset the existence of a priority, as otherwise the list grows and grows, accumulating things which have already been dealt with and therefore not even the lowest-possible priority.

**Comment by nikolai-b** [comment]
Sorry, made a typo, fixed.

**Comment by mvl22** [comment]
I don't think this UI is workable - I get this, which has overlapping text (which means that 'Top priority' can't actually be clicked on) and makes the listing unusable as there are now only three items visible before scrolling. The functionality itself does work through, so looks like this is not far off.

So, I suggest changing this to a select drop-down rather than a radiobutton set.

![screen shot 2018-03-05 at 09 30 21](https://user-images.githubusercontent.com/361423/36967538-f1389d72-2057-11e8-9e92-20007d0864ac.png)

**Comment by nikolai-b** [comment]
@mvl22 it would be a shame to have a  radio buttons on the thread page and a drop down on the dashboard.  

The reason yours is like this is because of a thread with a very long title.  I've forced these titles to wrap, is this solution acceptable?

**Comment by mvl22** [comment]
> I've forced these titles to wrap, is this solution acceptable?

That fixes the overlap problem, thanks, but overall the use of radiobuttons still doesn't work, because there are now only three items visible before scrolling - which prevents the intended at-a-glance nature of this page.

I realise this creates an inconsistency, but I think in this case it is acceptable. I realise it means that two bits of rendering code are needed.
