### ISSUE TITLE
Use CycleStreets' tilecache

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/cyclescape#171]
Cyclescape should use tiles from CycleStreets' new tilecache which serves tiles from:

http://tile.cyclestreets.net/

eg. http://tile.cyclestreets.net/opencyclemap/11/1024/674.png

**Comment by mvl22** [comment]
This is HTTPS-enabled and also supports @2x for Retina displays, which Leaflet (and probably OpenLayers) will handle natively. E.g.

https://tile.cyclestreets.net/opencyclemap/11/1024/674@2x.png

**Comment by mvl22** [comment]
The main file needing to be updated is:
https://github.com/cyclestreets/cyclescape/blob/master/config/initializers/map_layers.rb

though I can't see why OSM_MAPNIK is not there. Perhaps that is an OpenLayers built-in. Hopefully it can be overriden by adding it to the above file.

The URL paths for https://tile.cyclestreets.net are:

/opencyclemap/{z}/{x}/{y}.png
/mapnik/{z}/{x}/{y}.png
/osopendata/{z}/{x}/{y}.png

**Comment by nikolai-b** [comment]
https://tile.cyclestreets.net/opencyclemap/13/4091/2722@2x.png works but
https://c.tile.cyclestreets.net/opencyclemap/13/4091/2722@2x.png (with a leading `a` `b` or `c`) is not working over SSL, is this something you can fix @mvl22 ?

**Comment by mvl22** [comment]
We don't have a subsubdomain cert. This might happen in future but not at present.

Just for now use it without the a/b/c. That's only really needed when you have a large map display and then it's helpful to have a/b/c as it multiplies by 3 the number of threads a browser can make to the same place.

**Comment by nikolai-b** [comment]
@mvl22 this is noticeably slower than opencyclemap tile server, do you think this is due to lack of subdomains?

**Comment by jf1** [comment]
I've also noticed its slowness. Some tiles were blank (whitespace) so I wondered if they were being generated on demand or if there was a caching system that wasn't yet fully populated.

**Comment by mvl22** [comment]
I'll try to get a sub-subdomain cert in place, i.e. so we can serve {a|b|c}.tile

**Comment by mvl22** [comment]
> I'll try to get a sub-subdomain cert in place, i.e. so we can serve {a|b|c}.tile

Now in place and working.
