### ISSUE TITLE
/user/locations needs various usability improvements

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#174]
- Catch-up link is easy to miss
- Table below needs styling
- Table below easy to miss as below fold
- Should entice user to join groups and explain the benefit of this

**Comment by jf1** [comment]
Could /user/locations/new integrate a routing engine or add a gpx file upload feature, as detailed in
https://github.com/cyclestreets/cyclescape/issues/95

Also in /user/locations/new it'd be useful if users could choose, eg from drop-down lists of, political areas (to county and LAs level) and Cyclescape groups, especially ones they're members of.

**Comment by mvl22** [comment]
> Also in /user/locations/new it'd be useful if users could choose, eg from drop-down lists of, political areas (to county and LAs level)

Coincidentally, Nikolai and myself met on Thursday and we discussed exactly this, as part of a complete reworking of that interface area. So yes, this will hopefully happen soon.

**Comment by mvl22** [comment]
Ref #551 which would be a quick win - will enable the search results to be zoomed into a suitable zoom level.

**Comment by dekarl** [comment]
- The first thing I missed is support for the mouse wheel to zoom in/out of the map.
- Also adding a short descriptive text to each location in addition to the category would be helpful. I missed it when adding routes between primary, secondary, tertiary work location and when adding routes to relatives/friends.

**Comment by jf1** [comment]
@mvl22  Please can this be added to https://github.com/cyclestreets/cyclescape/milestone/8 ?

**Comment by nikolai-b** [comment]
@mvl22 I'm not sure exactly what is needed from this ticket now.  Is it still valid?

**Comment by mvl22** [comment]
> @mvl22 I'm not sure exactly what is needed from this ticket now. Is it still valid?

Closing - it related to the previous interface.

If there are any new issues with the new `/user/locations` interface, please open a new ticket.
