### ISSUE TITLE
City-wide issues as a preset

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#190]
A year's usage in Cambridge has highlighted the problem of city-wide issues (e.g. lorry safety; Local Plan; promotion of cycling in the area). These issues are clearly being used heavily (as are smaller more local issues for which the site was primarily designed).

It would be useful to have a standard 'insert <city> polygon' type functionality on the issue page, which would draw in the standard group area. This would also set a standard flag so that various listings could show this, and so that the issue map would exclude these to avoid clutter.

**Comment by nikolai-b** [comment]
Can this be started?  For a start we could make the user location map (with presets) apply to issues which also resolves helps #682.
We could also use it for group profiles to fix #385

**Comment by mvl22** [comment]
Yes, this could present the group's boundary as the preset.

I envisage this would simply be a button in the top-right of the issue map which says "Group's area" and which if clicked, clones the group's geometry, replacing anything currently there.

NB This is an issue that will be included in the design reworking, but it would be good to get a working button in the meanwhile, so we can transplant this easily.
