### ISSUE TITLE
Users cannot be changed to sysadmins in /admin/users

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#193]
Changing a user in /admin/users from member to admin (i.e. System administrator), results in an exception.

Presumably this will have started when the attr_accessible stuff was added.

Presumably needs a change near
https://github.com/cyclestreets/toolkit/blob/master/app/models/user.rb#L30

**Comment by nikolai-b** [comment]
Looks like this is the same as #348, closed in https://github.com/cyclestreets/cyclescape/commit/deeee2b89c3a5fa336bf07f0d650c5e972a90782
