### ISSUE TITLE
Tags need autocomplete

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#20]
Tagging is currently rather haphazard and non- self-explanatory as there is no naming authority control (so we end up with 'cycle parking', 'cycle-parking', 'cycleparking', etc.). Autocomplete will resolve this. It will also make this feature much more self-explanatory and fun/attractive for users.

There are mixed views on whether tags should allow spaces or not. Personally I feel they should be, with comma separation as the way the user indicates the separation. Users ideally shouldn't have to create 'computery' looking strings like cycleparking when the natural language is 'cycle parking'.

I've used this plugin before and it's pretty good:
http://loopj.com/jquery-tokeninput/

and there are other implementations:
www.google.com/search?q=facebook+style+auto+complete

**Comment by nikolai-b** [comment]
I've added styling in https://github.com/cyclestreets/cyclescape/tree/tagging (which is now merged into staging) I can't really make the autocomplete faster, is it still an issue (it comes up very quickly for me)?

**Comment by mvl22** [comment]
Yes, the speed is not a problem nowadays. I think at some point there was an intentional delay which has been removed.
