### ISSUE TITLE
Limit length of user lists

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#203]
We expect lots of new users soon, and I expect the length of the user list pages
http://camcycle.cyclescape.org/admin/users
http://camcycle.cyclescape.org/groups/.../membership_requests
and 
http://camcycle.cyclescape.org/groups/.../members
to become unmanageably large.

For the all users page and the group members page I think it would probably be sufficient for now to select by first letter, but we also need a search.

For the requests page, I think you should drop the confirmed or denied requests by default (possibly have a separate option to display these) and only show pending un-actioned requests.

**Comment by mvl22** [comment]
The users list is now paginated and includes a search.
