### ISSUE TITLE
Include photos from CycleStreets by reference

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#213]
We already have a home for geographically located photos with other valuable metadata which could be incorporated into a thread by reference (e.g. with an additional tab in the kinds of item which could be added to a thread). This would avoid duplication, but let us see the data in line rather than have to jump to it, and also recognises the data may already exists, so no need to re-upload it.

**Comment by mvl22** [comment]
As a first start, it would be useful to have CycleStreets photos on the main map for the issue, in the same way that collisions can be switched on.

So
http://camcycle.cyclescape.org/issues/127-chisholm-trail

would have a button "Show photos from CycleStreets"

which would add the same data layer shown at
http://www.cyclestreets.net/photomap/

using this API:
http://www.cyclestreets.net/api/v2/photomap.locations/

**Comment by nikolai-b** [comment]
A draft of this should be on staging, if your happy with that @mvl22 then we can close this (and finish Tranche 3)

**Comment by mvl22** [comment]
The integration is working fine (great!), but there is some very odd interaction between the two checkboxes now - do you not see the same thing? They don't seem to act independently, with inconsistent on/off behaviour.

Collisions no longer actually seem to show either.

**Comment by mvl22** [comment]
Once that aspect is done we then need to get the second part in place, which is just as important:

> additional tab in the kinds of item which could be added to a thread

In practice that will become the thing that is most used.

I envisage the same browsing map, but perhaps with a button in the popup that selects it, and enables a caption to be added, as per the Google Street View integration.

**Comment by nikolai-b** [comment]
So a user selects the Cyclescape Photo (maybe next to the Photo option), sees the map, selects a photo, has the option to add a caption?

E.g like this bad mock up (should be Cyclestreet Photo not street view selected)...
![bad mock up](https://cloud.githubusercontent.com/assets/6289830/18616017/1cf4e65a-7dac-11e6-93b9-43a1965cceb7.png)

We can't add another reply type without thinking about it as the list starts to be too long.  It could be a picture sub-type?

**Comment by nikolai-b** [comment]
Also, should Cyclescape pull all the data and store it or should it only really store the id and get the rest from Cyclestreets?  For example. if a user includes a photo I think that photo shouldn't change even if the Cyclestreets user updates the photo or location.

**Comment by mvl22** [comment]
> We can't add another reply type without thinking about it as the list starts to be too long.

We need to bite the bullet on this at some point. I think we should just start a second row for now. In my view the recent changes for the Leader stuff will need this anyway.

> So a user selects the Cyclescape Photo (maybe next to the Photo option), sees the map, selects a photo, has the option to add a caption?

Yes.

> Also, should Cyclescape pull all the data and store it or should it only really store the id and get the rest from Cyclestreets? For example. if a user includes a photo I think that photo shouldn't change even if the Cyclestreets user updates the photo or location.

Correct - selecting a photo should pull in the data and clone it into the Cyclescape database. There should be no further Photomap API call.

Obviously selecting a photo should pre-fill the caption, to save the user having to do that.

**Comment by mvl22** [comment]
All seems fine, except one thing: Once a message has been created, clicking on the image to show the full resolution image doesn't work - the image src is presumably wrong.

**Comment by mvl22** [comment]
> some very odd interaction between the two checkboxes now
> Collisions no longer actually seem to show either.

This all works fine now and is fine to deploy - thanks for the fix. They correctly work as two independent checkbox controls.
