### ISSUE TITLE
Privacy versus Transparency

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#218]
Nigel points out that the public visibility of profiles is not compatible with a real name policy.

I think there needs to be a preference as to whether your profile is public, or visible only to group members and admins.

Furthermore, creating issues is always public, so real names are disclosed outside a group context if you do that.

Maybe there could be a preference also so that you can choose in what contexts to display real name instead of pseudonym: always, only in group visible items, or never.

**Comment by georgio8** [comment]
As far as I can see, these plans will do a good job of ensuring that people can control the privacy of their real names while allowing members of particular groups to see them. But they don't address the problem that I raised in #323 - which has become a crucial issue for us in LCC now that we are using Cyclescape to mediate discussion of TfL consultation across all LCC members and other supporters. 

To reiterate, we are using public threads for the discussion of consultations (because it will be a long time, if ever, before all LCC members and supporters are in the LCC Group on Cyclescape). But we want to ensure that we can identify the contributors to these discussions by their real names.

My suggested solution is to enable the initiator of a thread to set an option 'comments only from users with public real names'. If this is too simplistic a solution, I'd like to discuss other options to achieve what we need.

**Comment by nikolai-b** [comment]
hi @georgio8, I've just started doing development work on cyclescape (which means I would like to understand a bit but also I might ask things that have already been answered).
I don't understand how it would be decided that contributors are using their real names?
Are you just saying you'd like the ability to only allow users with two names given to be able to comment on a thread (e.g. "Jean Green" can comment but "Jean" cannot).  That would be simple to implement and when commenting there could be a little notice saying "Please use your real name" but then a person called "NotMyName RealName" can also comment.

Personally, I like your suggestion in #323 about having the ability to send a direct message to a user.  This could be limited to members of the group the user has commented on.

**Comment by georgio8** [comment]
Hi Nikolai,
How about changing the form to have 'First Name', 'Last Name' and 'Display Name' fields? In my opinion we should require that the complete them all, but others may disagree. In that case, it should be an option for a thread creator to set the thread to 'no anonymous comments', meaning that comments can only be posted by people who have filled all the name fields in their profile.
Glad that you think the 'Direct Mail' facility is needed. Cyclescape is about the only forum/social network that doesn't provide it at present.

**Comment by mvl22** [comment]
> Glad that you think the 'Direct Mail' facility is needed

Yes. Direct messaging was always part of the original spec - see section 26, where it was marked as a Priority 3 level thing to implement.
http://blog.cyclescape.org/images/ToolkitSpecificationFull.pdf

Issue 48 is the direct messaging thread:
https://github.com/cyclestreets/cyclescape/issues/48
so can we discuss that particular issue there.

**Comment by mvl22** [comment]
> How about changing the form to have 'First Name', 'Last Name' and 'Display Name' fields?

There is a bit of an issue here which is that not everyone has both a forename and surname. There is certainly active camcycle member for instance who doesn't.

**Comment by nikolai-b** [comment]
This has been done in #369, can we have an parts of this that are still outstanding opened as new issues

**Comment by mvl22** [comment]
Yes; I will try to migrate the residual points to fresh issues.

I think the main one is reworking of the layout of the e-mails, which don't make things like this anything like clear enough. The information is all in them, but it needs to be made much clearer.

**Comment by mvl22** [comment]
> My suggested solution is to enable the initiator of a thread to set an option 'comments only from users with public real names'.

For ease of reference, this is separately discussed as issue #392.

**Comment by mvl22** [comment]
> Personally, I like your suggestion in #323 about having the ability to send a direct message to a user.

To confirm: this has been implemented a while back as issue #48.

**Comment by mvl22** [comment]
> This has been done in #369, can we have an parts of this that are still outstanding opened as new issues

Just to confirm that I've reviewed the full discussion in this issue, and all aspects are implemented, except where noted as a separate issue.
