### ISSUE TITLE
Lack of notification if mail queue gets stuck

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#221]
If the incoming mail queue gets stuck, notification is sent to the same mailbox as other incoming mail.

Instead, this e-mail should go to a human mailbox.

There was a stuck mail in early June, and another has just been discovered dating from 25th June. The mail queue is now being worked through. I have kept both messages and will attach them shortly.

**Comment by nikolai-b** [comment]
Is this still an issue?

**Comment by mvl22** [comment]
No, this is long-fixed; the report comes through correctly to cyclescape-errors @ ourdomain.
