### ISSUE TITLE
Peformance

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/cyclescape#223]
The attached munin chart shows the critical memory situation on the machine that currently hosts Cyclescape. You will notice that it is swapping, that its swap size has been growing and that the amount of swapping is about 10x that of CycleStreets. This could account for the dire performance with very slow response time.

There's a chance of getting more RAM allocated, the question is how much more should it need? Will switching from 4GB to 8GB be enough?

![malvolio_mem_swap_july_2013](https://f.cloud.github.com/assets/361987/787290/65eea6c8-ead6-11e2-8397-eaabe6116c4c.png)

Cyclescape runs as a VM, currently shared with CycleStreets' backup / import server VM. At the time of writing the CycleStreets' machine is running in failover mode while Nominatim is being set up. Before Cyclescape or CycleStreets switch back to the main server a decision needs to be taken about RAM allocation.

**Comment by mvl22** [comment]
Cyclescape now on a dedicated machine, so closing this issue.

Basically the clear message is generally that if you use a VM you get less good disk performance!
