### ISSUE TITLE
Non-existent "To:" field in incoming mail causes incoming mail queue processor to stick

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#225]
Notwithstanding clearing the mail queue this week, I am still missing at least one message in thread 853. The message was sent on 25 June at 11:35. It was BCC'd to me and it came back to me so it definitely left my server, but it isn't shown in the thread. Perhaps it is because it lists the thread as a CC, I imagine because I replied to a message I sent to cyclescape reflected back to myself rather than from cyclescape itself, but I wasn't aware I had done that.

If there is some reason for you to reject an email, I really want it bounced, not disappearing into a black hold - this massively undermines my confidence in the system if messages just disappear because you choose not to like how I sent it, if that is indeed the case.

Since the queue crashed at that time, maybe this message is why it crashed: if my supposition that you are explicitly rejecting it is wrong, maybe the queue crashed because it is missing the To header, and you are assuming it must have a To.
## Here's the raw email, from my sent items

From - Tue Jun 25 11:35:08 2013
X-Mozilla-Status: 0001
X-Mozilla-Status2: 00800000
X-Mozilla-Keys:  
BCC: david@frankieandshadow.com
Message-ID: 51C9725C.6040403@frankieandshadow.com
Date: Tue, 25 Jun 2013 11:35:08 +0100
From: David Earl david@frankieandshadow.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20130509 Thunderbird/17.0.6
MIME-Version: 1.0
CC: thread-1ec69127933915300b46@cyclescape.org
Subject: Re: [Cyclescape] Histon Road (Cambridge) Improvements proposed
References: aef331b3-f562-4c97-885c-c68d289faabe@mail.android.htc.com
In-Reply-To: aef331b3-f562-4c97-885c-c68d289faabe@mail.android.htc.com
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

On 24/06/2013 17:42, david.j.earl@gmail.com wrote:

> I will have another look but my first reading was that it was just
> removal of parking, not cycle lanes.

So, I looked at the map, and it doesn't actually show any cycle lanes 
other than the approach to the junction. But the text does say so.

However, it doesn't offer any widths.

I can't tell whether this is instead of or in advance of the more 
ambitious scheme that I thought Mike Davies' team were considering.

**Comment by nikolai-b** [comment]
Fixed in #364
