### ISSUE TITLE
Gracefully handle unprocessable emails

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#231]
So far we've had 3 instances of mails which can't be processed, and as a side effect, 'block' all further emails from being processed.

https://github.com/cyclestreets/toolkit/blob/master/lib/mailbox_reader.rb

In all cases it's been in the save_message block (#226 , #225 inter alia)
After the exception is raised, the mail remains 'UNSEEN' on the mailbox, and is picked up again on the next scheduled run and reprocessed. That throws another exception, causing stalemate. In addition, an error report is generated from cron every 5 minutes or so.

The desired output would be to send only one error notification, and then to move on and process other messages. The bogus mail can then be inspected, reprocessed and/or bugs fixed at leisure.

The code above is run via cron, using the whenever gem and the schedule.rb file:

https://github.com/cyclestreets/toolkit/blob/master/config/schedule.rb

So triggering an exception would suffice for notifications, as long as it was ensured the mail was also marked read.

The danger is that broken code could mean that all messages fail, and we need to handle manual re-processing of hundreds of mails. The current setup guards against this by ensuring only successful processing of emails marks them as read.

**Comment by mvl22** [comment]
Thanks; this is all much better now, compared to the old situation.
