### ISSUE TITLE
CSS needs adjustment to make variable width for smaller screens

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#235]
A couple of users have experienced problems with the fixed width 1024px layout. In particular, important parts of navigation (the green buttons) tend to be to the right of an 800px screen, and scrolling to the right is whited-out rather than showing the obscured part of the layout.

The CSS basically just needs to be amended to have min-width/max-width defined rather than a specific width, as far as I can see, though there would be some other adjustments elsewhere in the CSS also needed. The whiting-out problem is also there somewhere.

https://github.com/cyclestreets/toolkit/blob/master/app/assets/stylesheets/content.css.scss

and other files in

https://github.com/cyclestreets/toolkit/blob/master/app/assets/stylesheets/

**Comment by panchew** [comment]
@mvl22 I've created a pull request for this: https://github.com/cyclestreets/cyclescape/pull/494

**Comment by mvl22** [comment]
Thanks, that's certainly an improvement - Nikolai, please do merge into master.

We'll keep the issue open as it will need further work on various screens.

**Comment by nikolai-b** [comment]
Merged
