### ISSUE TITLE
Prevent users setting privacy in group context if not on Committee

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#241]
In a group context, where the group has privacy = private-to-group by default, only Committee members should be able to set the privacy to public.

**Comment by mvl22** [comment]
This was referring to the initial creation of a thread, though changing an existing thread should similarly be restricted.

Is that what has been implemented?

**Comment by nikolai-b** [comment]
It is not but only committee members can edit a message thread.  Bizarrely they can assign it to any group, not just ones they are in.  Should I create a new issue for that?

**Comment by mvl22** [comment]
Yes, please.
