### ISSUE TITLE
Need a rotate photo control

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#244]
The photos Heather added to thread 897 clearly illustrate the need for a photo rotation control. (Does Cyclescape take note of the Orientation exif setting in images? Though the original has this as 'normal' in this case, which is odd, so it wouldn't make any difference here).

**Comment by nikolai-b** [comment]
@mvl22 this is now on staging.  Please let me know what you think.

**Comment by nikolai-b** [comment]
@mvl22 have you had a chance to look?

It is on the 
* user profile edit
* group photo
* group logo
* photo message

**Comment by nikolai-b** [comment]
Done in #777

**Comment by mvl22** [comment]
Awesome; works perfectly. Please do push into live.
