### ISSUE TITLE
Photo thumbnail missing

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#245]
The photo posted at http://www.cyclescape.org/threads/945#message-10257 doesn't appear (just shows the missing image browser icon) in either thumbnail or medium size; if you click through to the original it is correctly visible.

**Comment by smsm1** [comment]
Interestingly Safari shows the first page of a PDF in the browser, however for full platform compatibility rendering a thumbnail image of the PDF page would be a good option, and would be the same as Basecamp.
Related #289

**Comment by smsm1** [comment]
#157 is also related.
