### ISSUE TITLE
Unsubscription/subscription by e-mail should never be more than one click

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#250]
Useful suggestion from a user - which I think has been considered before but I think needs to be reconsidered.

> Re the link on the bottom of the email, for example:
> Cyclescape thread:
> http://www.cyclescape.org/threads/975
> You can stop following this thread by visiting the link above.
> 
> Since I use email on a shared computer and we both have Cyclescape accounts, the link takes me to the Cyclescape page for that thread for whichever of us happens to be logged in to Cyclescape at the time.
> 
> It would be much better if the link text said "to stop following this thread, click here" and the link included a token to identify me so that clicking here was all I needed to do to stop following. (This could be in addition to the current link, in case people want to visit the thread on the web but not stop following it by email).
> 
> Otherwise I have to click the link, log out as other user, log in as me, find the thread again, click to stop following.

There is one issue though, which is that I understand some mail-clients or at least web-browsers can pre-load links, resulting in mass auto-unsubscription.

In general I'd like subscription/unsubscription never to be more than a one-click action. In the case of e-mail, to deal with the pre-loading issue, maybe a 'confirm' once you're on the site would be fine. There shouldn't be a need to trigger a login because following a link in an e-mail containing a token is as secure as having to request a new password (both require e-mail access).

I do think this is different to clicking on the general thread link and then having to find the page - it is a clearly distinct user action to be prompted in an e-mail that they can unsubscribe.

**Comment by richvdh** [comment]
An "unsubscribe" link in the email would be super useful.

I feel like requiring a login would be fine - the browser can deal with sending the credentials if necessary without user interaction - and this might mitigate concerns over mail clients preloading links?
