### ISSUE TITLE
Tag problem

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#259]
In thread http://camcycle.cyclescape.org/threads/979 the thread is clearley tagged 'newsletter'. However if I click on the grey box containing the tag it says nothing is tagged 'newsletter'. This is clearly nonsense.

**Comment by mvl22** [comment]
I wonder if this is a database uniqueness constraint problem, where multiple items against an expected only-one mean that no result is obtained.

**Comment by panchew** [comment]
@mvl22 I wasn't able to reproduce this one neither locally or on prod. All the samples I created in my local environment worked properly. Is there a way to reproduce?

**Comment by davidearl** [comment]
Just click on the grey tag box at the top of that thread. That should
presumably list all the items with that tag including the one you came from
- bit it says there aren't any. Still does, I just tried it.

**Comment by mvl22** [comment]
I suspect this is a data inconsistency error in the main site database arising from an early bug which probably got fixed.

As such, I think @nikolai-b is best to look at this as it requires access to the database with real data in.

May need a migration to sort this out.
