### ISSUE TITLE
Upgrade devise

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#268]
The version of devise that we're using is becoming increasing old, and we're only putting off work that needs doing eventually.

- [x] The original reason for pinning is now fixed
- [x] Upgrading to latest in 2.1 series
- [x] Upgrade to 2.2 series https://github.com/plataformatec/devise/wiki/How-To:-Upgrade-to-Devise-2.2 Also fixes #46 
- [ ] Upgrading to 3.0.x needs an upgrade to devise_invitable too
- [ ] Devise invitable upgrade needs a migration
- [ ] Upgrading to 3.1.x needs a devise secret key (for encrypting tokens in the db) - will need a similar setup to the rails secret key in chef

**Comment by nikolai-b** [comment]
Done in dc89c7cab326c9afbc0e36c9e050732720760771, 17d1dccf8edcfba5f769dfa692037790c66bbacc, and https://github.com/cyclestreets/cyclescape-chef/commit/135d882f05c86a319b24a91391a04aede2ebac45 . 
Will close when merged.
