### ISSUE TITLE
Duplicate users in group

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#274]
If someone is added to a group (eg from their user page) and they are already a member of that group they appear to be added twice (and thrice,...). Furthermore, it then appear that they cannot access that groups threads.

Clearly, they should only get added if they are not already assigned to the group, and an error message shown if a second attempt is made.

And I suspect there is a test somewhere when checking for page visibility for count of members of that name == 1 rather than > 0, on the currently incorrect assumption that it can only be 0 or 1.

The user also points out that the error message which says they aren't allowed to view a page in these circumstances (which is presumably the same if they genuinely aren't part of the group when trying to access a group page) isn't very helpful, in that it doesn't say why not and what you can do about it (such as applying for membership of the appropriate group and providing a link to do so).

Finally the message on the user page  says that "you can invite" them to the group. Do they actually get an email invitation at that point, or are they just added silently (which isn't an invitation in my book) as in other circumstances, already registered users don't get an email, but on this page by definition you know they are already signed up. (In general if someone is sent an email as a result of an action it is useful to be told that when it has happened).

**Comment by mvl22** [comment]
> If someone is added to a group (eg from their user page) and they are already a member of that group they appear to be added twice

Was fixed in 7a596c9bb391d1fc0d8900aeaaa3e62e4f4c9195.

> The user also points out that the error message which says they aren't allowed to view a page in these circumstances (which is presumably the same if they genuinely aren't part of the group when trying to access a group page) isn't very helpful

Was fixed in 7222a1dc8989fff88940761e44d782b39a4331f5.

> Finally the message on the user page says that "you can invite" them to the group. Do they actually get an email invitation at that point, or are they just added silently

Users now get an e-mail when they are added, as fixed in bf37962f20a5d51f3efa4f5e771ca9faf3e6daaf and e9e68486397a235b4c1157761f951aaf5d5d0617.
