### ISSUE TITLE
Allow language / locale switching

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#277]
We have translations available for the site, so we should use them too! Auto-detection of language using browser headers is a good approach, but we'll need profile-based language choices too for the corner cases so it makes sense to start there.

**Comment by nikolai-b** [comment]
Looks like we have auto-detection based on browser headers.  Do we still want an user preferences over-ride?  My view is that we should wait till it has been requested.

**Comment by mvl22** [comment]
Yes, there does need to be a way to change the language if wrong. I favour the Facebook approach of auto-detection, but links at the bottom to change.
