### ISSUE TITLE
Admins should be able to edit messages

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#281]
Admins can censor messages, but it's a bit of a blunt tool.

**Comment by nikolai-b** [comment]
As they have already been sent out via email this seems like enough as @mvl22 says in #279

**Comment by mvl22** [comment]
Agreed. Any kind of post-publication editing will need significant consideration of the ramifications. I think censoring is probably enough, as this at least deals with legally-actionable content.
