### ISSUE TITLE
Password reset page needs some TLC

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#284]
It's unstyled and rather cramped at the moment, along with some terse copywriting.

There's a badly presented error when the email doesn't exist too.

**Comment by mvl22** [comment]
http://www.cyclescape.org/users/password/new

Like most of the signin stuff, looks awful. As the first thing that users encounter, this would be good to make look much nicer.

**Comment by rbazinet** [comment]
@mvl22 is there a form that exists on the site that you do like? I can model the password/new form after it.

**Comment by nikolai-b** [comment]
![screenshot from 2016-07-17 21-35-45](https://cloud.githubusercontent.com/assets/6289830/16902936/a9b1e2fe-4c66-11e6-8e7a-65354770cf58.png)
@mvl22 is this better ^ I've removed the confusing error title but the red warning made sense to me.  It is the devise default https://github.com/tigrish/devise-i18n/blob/7d73e77fc4/rails/locales/en-GB.yml#L116 so I was somewhat loathed to alter it.  I've spaced the links out and increased the text box form padding so it copies https://www.cyclescape.org/users/sign_in (but I've added some padding to the button).  If you'd like to add more explanatory text let me know.

**Comment by nikolai-b** [comment]
Closing as I believe this issue is fixed in e824d48, if not please re-open with more information about what you'd like the page to look like.

**Comment by mvl22** [comment]
Thanks, that's better.

The whole user account area needs in general some nice designs, but I suggest this gets looked at as a separate matter once we have the responsive layout stuff in place in #591.
