### ISSUE TITLE
Upgrade dragonfly

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#298]
https://github.com/markevans/dragonfly/wiki/Upgrading-from-0.9-to-1.0

**Comment by nikolai-b** [comment]
Can be closed when https://github.com/cyclestreets/cyclescape/commit/78d9511c4a50d5f558abd0942c374f329a285915 is merged

**Comment by mvl22** [comment]
@nikolai-b can this be closed now?
