### ISSUE TITLE
Use devise-i18n gem?

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#301]
https://github.com/tigrish/devise-i18n

At the moment we have customized versions of the devise locale files, both in English and in Czech. But there are a few disadvantages to this:

* Translators need to re-translate all the standard devise messages for their language, when that's already been done in the devise-i18n gem
* It's unclear which of our strings in devise.en-GB.yml are from upstream and which are ours. Unless, of course, it has the word 'Cyclescape' in there :-)

So we should investigate adding the devise-i18n gem, and see if it works nicely with our overrides. If so we should edit the devise*.en-GB.yml files, and remove the unmodified translations.

**Comment by fabianhjr** [comment]
What is the satus on this?

**Comment by nikolai-b** [comment]
Nothing has happened but it is a [current priority](https://github.com/cyclestreets/cyclescape/labels/current-priorites) so when I get time I will compare https://github.com/tigrish/devise-i18n/blob/master/rails/locales/en-GB.yml with https://github.com/cyclestreets/cyclescape/blob/master/config/locales/devise.en-GB.yml and delete all the generic ones, only keeping the Cyclescape specific ones.

**Comment by mvl22** [comment]
> but it is a current priority

NB Current priorities are listed at:
https://github.com/cyclestreets/cyclescape/milestones/Tranche%201

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/3de4e0019 but not in master yet
