### ISSUE TITLE
Add mailer for issues posted to /site/comments

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#307]
It would be useful if issues posted to /site/comments could also be e-mailed to an e-mail address that is settable as a system-wide admin setting. It would make replying to them easier.

(In the longer term a proper feedback handling system would obviously be useful, as /site/comments was set up to be quite simple, but replying by e-mail now is fine for now.)

**Comment by PetrDlouhy** [comment]
I think, that this is very necessary. On Cyklisté sobě, feedbacks often tend to be long time forgotten without any action. We need to get the messages by email.

The new message moderation seems to have the same problem.
