### ISSUE TITLE
Creating issues needs to be clear around public status

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#311]
Refs #218 

> We agreed that the web form for creating an issue needs to make clear that the title and description of the issue will be visible to anyone, and so they might want to keep the issue description fairly short and simple. The web form should encourage users who want to make a non-public personal statement about the issue to do so as the first posting to a group-private thread on the issue.

**Comment by nikolai-b** [comment]
We have 

> Please note that all issues are publicly viewable.


And 

> Group This specifies who can see and edit this discussion thread.

So I'm closing this now
