### ISSUE TITLE
Show real name to group users

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#314]
Refs #218 

> The general rule we came up with is, wherever a page (or e-mail) shows a person's name:

>   *  If display name is set, then if person looking at your name is in the same group [strictly speaking: if group memberships overlap] as you are, they can see your real name. This takes effect no matter what the nature of the material is (e.g. irrespective of the whether a thread is owned or not owned by a group).
>   * (Obviously, in all situations, if no display name is set, always show the real name.)

**Comment by mvl22** [comment]
> However, I think it's actually a loss of functionality to force people to use their real names in groups.
> I can understand that this is what particular people have asked for but I'm not sure it's a universal
> situation.

I can see your point here.

@davidearl - do you have thoughts on this?

**Comment by davidearl** [comment]
It's a bit tedious to find out who an email is from if you have to go via the web site. Don't forget the web site is not the only or even main way of working.
