### ISSUE TITLE
Update guidance on display_name and full_name

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#315]
Refs #218 

> The form where the Real name and Display name needs labels underneath to make clear when these are used. This might be slightly tricky to do clearly. Perhaps something like:

> "If you set a display name, it will be shown to people who are not in any group(s) you have joined."

This needs to wait until #314 is implemented, since that changes the required guidance.

**Comment by nikolai-b** [comment]
Done
