### ISSUE TITLE
Spaces getting lost

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#320]
If you send an email or enter in the editor a string with more than one space, or a space at the start of a line, they get lost. It's pretty obvious from the way HTML works why that is. I think multiple spaces need to be replaced with n-1 x &nbsp; ending with one real space. The particular problem is when you indent something with spaces, the indentation gets lost completely.

I wonder if GitHub
       <-- several spaces 
does it properly?

**Comment by nikolai-b** [comment]
We now trust the HTML part of emails so I believe this issue is resolved.
