### ISSUE TITLE
Posts are sent as raw HTML embedded in a text/plain email

### ISSUE THREAD

**Issue by wookey** [cyclestreets/cyclescape#328]
The mail that arrives is text/plain and so are the additions added by cyclescape, but the original content part of the mail is an HTML doc, including the DOCTYPE header, HTML entity conversions etc, making it a hard read, and well, just wrong. I'm guessing this happens when the original mail was sent as HTML-only with no text/plain part for cyclescape to use? This fits with the fact that I see this behaviour with posts from one particular poster, not others, so I assume it's down to what they are sending in to the system.

It should un-html the mail to send as proper plain text. (e.g using links -dump), or (worse, but better than the current breakage) make the whole mail type text/html and properly format the message.

Here is an example:
Reply-To: thread-3f890bc9173809e7389e@ cyclescape.org  
To: wookey wookey@wookware.org 
Message-ID: 53e49a182e528_76cf75788071350@sebastian.mail 
References: <thread-3f890bc9173809e7389e@ cyclescape.org>
Mime-Version: 1.0  
Content-Type: text/plain;  
        charset=UTF-8 
Content-Transfer-Encoding: 7bit 
X-SA-Exim-Connect-IP: 93.93.130.6 
X-SA-Exim-Mail-From: notifications@ cyclescape.org 
X-Spam-Checker-Version: SpamAssassin 3.3.2 (2011-06-06) on 
        stoneboat.aleph1.co.uk 
X-Spam-Level:
X-Spam-Status: No, score=-4.2 required=4.5 tests=AWL,BAYES_00,
        RCVD_IN_DNSWL_MED autolearn=ham version=3.3.2
Subject: Re: [Cyclescape] Study Visit to Assen
X-SA-Exim-Version: 4.2.1 (built Mon, 26 Dec 2011 16:57:07 +0000)
X-SA-Exim-Scanned: Yes (on stoneboat.aleph1.co.uk)                                                          

Monica Frisch added a message to the thread. 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

 </head><body>
 <p>If we want to get councillors etc. along I think we need to be sowing the seed of the idea now, so thatwhen we announce possible dates they are already considering the idea of going. We could consider giving a presentation about previous study visits to groups of councillors, write to them explaining the purpose of a visit to Assen and inviting them to express interest. I doubt if we&#39;ll get much response if we just  say &#34;we are going in.... please come along&#34;. <br /></p> 

<br>
E-Mail scanned for viruses by The Co-operative Phone &amp; Broadband.  

</body></html>                                                                                              

---

Cyclescape discussion thread: 
http://www.cyclescape.org/threads/1463 

Only members of Cambridge Cycling Campaign can view
and post messages to this discussion thread. 

[MLS: Added spaces between e-mail address parts to avoid spam.]

**Comment by nikolai-b** [comment]
I believe this is fixed now.  Please re-open if now
