### ISSUE TITLE
Add table of most active members within a group

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#331]
It would be useful if Committee members of an organisation could see the most active members of the group (as defined by most numbers of postings).

**Comment by mvl22** [comment]
This would be particularly useful in the run up to a group's AGM, where they could quickly determine members who have become more active, and thus approach them with a view to becoming part of the group's committee.

**Comment by nikolai-b** [comment]
@mvl22 in staging, let me know if your happy with it.

**Comment by mvl22** [comment]
Apologies that I was not clear. I meant that this should be in stats page, so that only the group admins can see it (they can see stats, is that right?). I definitely don't think this should be on the public listing.

**Comment by mvl22** [comment]
OK, but please mark this as such, so that people looking at this will know that the tab is not ordinarily visible.

I'd still prefer to have it amongst the other admin functions though - that seems the logical place.

**Comment by nikolai-b** [comment]
The stats page is for admins only and there is no group info.  I've added the text:

> Please note, this tab is is only visible to committee members.

**Comment by mvl22** [comment]
Could we increase the list to 25 people?
