### ISSUE TITLE
404 error when trying to sign out

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#332]
Starting from here:
https://camcycle.cyclescape.org/users/edit
if I click Sign Out it gives me a 404 Page Not Found error and doesn't sign me out.
However if I start from 
http://camcycle.cyclescape.org
it does work, so it doesn't appear to be a subdomain related thing; could be because it is https?

**Comment by mvl22** [comment]
/users/edit is now
https://camcycle.cyclescape.org/settings/edit

**Comment by mvl22** [comment]
This seems to be working fine now.

David, can you confirm this can be closed?

**Comment by davidearl** [comment]
No, I still get a 404 when pressing sign out, on http://camcycle.cyclescape.org/users/sign_out .

**Comment by mvl22** [comment]
@davidearl From which page are you clicking on the sign out link?

**Comment by davidearl** [comment]
Possibly. I tried http://www.cyclescape.org/threads/844 before, but I've just tried it again and it signed me out this time (without clearing the cache), no 404. I wonder if it has to do with an expired session. I will leave the page open until the morning and try it again then.

**Comment by nikolai-b** [comment]
@davidearl we've upgraded many things so I'm going to close this.  Can we only re-open this if there are new instances please.
