### ISSUE TITLE
Changing user preferences is broken

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#334]
If I try to change a user's preferences from an admin account, it says
"We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly."

I'm sure this used to work, as I was setting email on for new users at the start.

Furthermore, if I navigate from there to one of the other tabs, it puts me on a page that would change MY settings not the person I was dealing with.

**Comment by nikolai-b** [comment]
I think this is probably fixed, can either of you confirm?

**Comment by mvl22** [comment]
Yes; definitely works for me.
