### ISSUE TITLE
Upgrade to rails 4.0

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#335]
Rails 3.2 is going to be end-of-lifed (i.e. no security patches) with the imminent release of 4.2, and already we're getting deprecation warning from gems that won't support 3.2 any longer.

**Comment by nikolai-b** [comment]
can be closed when #377 is merged

**Comment by mvl22** [comment]
Do we not need still to update to Rails 4.2?

**Comment by nikolai-b** [comment]
I think it would make sense to have a separate issues for upgrade to 4.1 and 4.2 because that allows us to measure progress and switch direction (like the LCC API stuff and jQuery).  I've been working on them both #408 and #409.

**Comment by mvl22** [comment]
Agreed - great work.
