### ISSUE TITLE
Selecter extending no longer ignored by sass

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#337]
In sass 3.3.x and above:

"Sass will now throw an error when an @extend that has no effect is used. The !optional flag may be used to avoid this behavior for a single @extend."

```
".superblyTagfieldDiv" failed to @extend "input.text-input".
The selector "input.text-input" was not found.
Use "@extend input.text-input !optional" if the extend should be able to fail.

  (in /home/andy/src/toolkit/app/assets/stylesheets/screen.css.scss)
```

Figure out if this is an important error or can be ignored with the !optional flag.

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/bca5ed3e8aa84fc453fa3caa302e4597924623e7#diff-064dfe5152f63e2432421e0c826389a3R3
