### ISSUE TITLE
Move away from exceptional.io

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#338]
We're using exceptional for error tracking, but there's a few major problems with it:

* Our account has never really worked cleanly. They have a super-minimal UI and I can't see any of the errors or have anyway to change things
* They have deprecated exceptional, and [we're supposed to move to airbrake now](http://blog.exceptional.io/bye-bye-exceptional-hello-airbrake/)
* Their SSL cert doesn't even work any more

So we have a few choices:

* Move to airbrake. Cheapest plan is [$39 per month](https://airbrake.io/account/new)
* Use the airbrake gem, but with [errbit](http://errbit.github.io/errbit/) as the server-side handler
* Other commercial options like [honeybadger.io](https://www.honeybadger.io/pages/plans), [Rollbar](https://rollbar.com/pricing/), [bugsnag](https://bugsnag.com/pricing), [raygun](https://raygun.io/pricing) etc
* Something else?

**Comment by mvl22** [comment]
@nikolai-b Presumably we can clear out the last remnants of Exceptional.io:
https://github.com/cyclestreets/cyclescape/search?q=exceptional

and then close this issue?

**Comment by mvl22** [comment]
@nikolai-b Can we close this now? There seems to be no code left, and you can hopefully confirm that the new system is working fine.

**Comment by gravitystorm** [comment]
Looks like we migrated to rollbar some time ago, so we're not using exceptional any more.
