### ISSUE TITLE
Update Ruby version

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#344]
.@nikolai-b [writes](https://lists.cyclestreets.net/pipermail/cyclescape-development/2015-February/000017.html):

> I'd really like to get ruby to 2.1.5 as that is the newest that Rails 3 supports.  I'm not sure how
> complicated that is for the chef scripts.  Rails 4.0 + prefers ruby 2.+.  I've run all the specs against ruby
> 2.1.5 and started the app, everything seems to work fine.
> 
> Also, I asked about the .ruby-version in the git ignore.  I'd like it included in git, is that a problem?

@gravitystorm, can you comment?

Looking through the chef repo:
https://github.com/cyclestreets/cyclescape-chef/search?q=ruby

I can see the following which look like they might need adjustment:
* https://github.com/cyclestreets/cyclescape-chef/blob/master/cookbooks/ruby19/recipes/default.rb
* https://github.com/cyclestreets/cyclescape-chef/blob/master/cookbooks/passenger-gem/templates/default/passenger.module.conf
* https://github.com/cyclestreets/cyclescape-chef/blob/master/cookbooks/apache2/recipes/mod_auth_openid.rb

Obviously it would be good if we can get to latest versions of Ruby and Rails, sooner rather than later.

**Comment by mvl22** [comment]
Branch at
https://github.com/cyclestreets/cyclescape/tree/ruby_version

**Comment by gravitystorm** [comment]
Rails 4 only requires 1.9.3+, so it's possible to do the rails 4 upgrade while maintaining the same ruby version. I don't think 14.04 comes with any newer version of ruby than that, so it's worth considering what benefits there are to running a non-provided ruby version.

**Comment by nikolai-b** [comment]
ok, I assumed that the project used a version manager.  I think the benefits are that 1.9.3 is [unsupported](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) from today!  Also Rails 4 recommends 2.0+, I'd worry that using 1.9.3 would be a pain and waste time with annoying bugs.  I've started on an [rbenv](https://github.com/cyclestreets/cyclescape-chef/tree/rbenv) branch of the chef repo but I'm new to chef.

**Comment by gravitystorm** [comment]
See https://github.com/cyclestreets/cyclescape-chef/issues/27 for chef discussion - obviously any developer can use rbenv/packages/chruby to manage their version

**Comment by gravitystorm** [comment]
Is there any advantages/disadvantages to using the `.ruby-version` file versus specifying the ruby version in the Gemfile?

**Comment by mvl22** [comment]
@nikolai-b Presumably this can be closed now?
