### ISSUE TITLE
Permalink not working wth new woocommercer update 2.3.3

### ISSUE THREAD

**Issue by garocchi** [cyclestreets/cyclescape#346]
HI there,
I have a problem with permalink with the new woocommerce update.
Shortly the button EDIT beside the permalink strings is not working. Is it something I'm missing or a bug problem?
I deleted the new plugin and installed the ols version and it's working fine.
Can you advice if I'm mmaking some mistakes or it's not something I'm doing wrong?
Thanks very much, I've been getting crazy sicne 3 days now.
Gabriele

**Comment by gravitystorm** [comment]
Hi Gabriele, this isn't the correct place to report problems with woocommerce. Try https://support.woothemes.com/hc/en-us

**Comment by garocchi** [comment]
Hi Andy,
sorry I thought it was the page to send advice or to tell about problems.
Thanks
Gabriele
