### ISSUE TITLE
Can't update user role (promote as an administrator)

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#348]
If I try to set user role in admin (promote some new user as an administrator), nothing happens (he stays member). In error log is following exception:

WARNING: Can't mass-assign protected attributes: role, profile_attributes

**Comment by nikolai-b** [comment]
fixed in https://github.com/cyclestreets/cyclescape/commit/deeee2b89c3a5fa336bf07f0d650c5e972a90782
