### ISSUE TITLE
Planning application browsing and clone-to-issue interfaces

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#35]
Planning applications, once the importing work is done, need user interfaces:

 * A browsing interface, basically a isting and browsable map map as another tab on the Issues page. Would have bubbles that have a button which links to a form to clone these into an issue. If an issue has in fact been promoted already, the button should instead be a link to the issue instead.
 * Clone to issue interface, which just pre-fills the issue.

A specific problem is that the issue needs to have a URL associated with it. To get this running quickly, for now just add \n\n + the link to the external URL at the end of the issue description.

Any user should be able to promote a planning application to an issue.

**Comment by mvl22** [comment]
Agree the GUI aspects are all dealt with.

#76 is the major issue.

Closing this GUI -related thread.

**Comment by nikolai-b** [comment]
in master
