### ISSUE TITLE
Deadlines listing should show all, not just limit 12

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#356]
I think there should not be a limit on the deadlines listing. There are unlikely ever to be hundreds of items here - it does not make sense to limit this listing artificially.

https://github.com/cyclestreets/cyclescape/blob/master/app/controllers/dashboards_controller.rb#L14

**Comment by rbazinet** [comment]
@mvl22 this is complete and committed to a feature branch.

**Comment by mvl22** [comment]
Thanks Rob.

@nikolai-b This all looks straightforward - can you review and merge into master.

https://github.com/cyclestreets/cyclescape/tree/issue-356

**Comment by nikolai-b** [comment]
I'm not sure there was a pull opened and I missed it, sorry.  I think that we should paginate which is more complicated that the approach.  You say it is unlikely to have hundreds of deadlines so we could increase the limit to n (n=40 as a suggestion) very quickly or paginate.
