### ISSUE TITLE
Voting to hide planning applications needs to be done without a full page refresh

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#358]
Having a full page refresh for the voting to hide planning applications is quite jarring. It would be much nicer if it could be done through background requests.

**Comment by mvl22** [comment]
Much better now; cheers :) Have rolled out.

**Comment by smsm1** [comment]
Bug related to this change on e.g. http://cycleipswich.cyclescape.org/planning_applications/uid/15/00292/ADV where the vote to hide button has incorrect text.

![cyclescape](https://cloud.githubusercontent.com/assets/82719/6971877/8d39efc6-d977-11e4-8f55-1247ba4ea2a5.png)
