### ISSUE TITLE
Too many issues rendered on homepage

### ISSUE THREAD

**Issue by washeck** [cyclestreets/cyclescape#361]
We run a copy of Cyclescape at www.cyklistesobe.cz. The codebase is about 1,5 year old fork. We plan to merge it but there is currently lack of developers to do so and we need to keep running the old version for a while. See https://github.com/auto-mat/toolkit for our current code.

I was informed that our server became extremely slow and investigation showed that it's caused by a huge number of issues rendered on the Issues page. http://cyklistesobe.cz/issues/ has 780 (!) occurrences of `<article class='issue'>`, most of them in the "Popular" tab. It makes rendering of the page slow and forces the browser to make thousands of requests to the server.

I'm not a Rails guy but I did a quick diff of our fork to cyclescape:master and I don't see a functional change here (except older versions of libraries) so I'm reporting here.

**Comment by mvl22** [comment]
Hi @washeck,

Looks like something odd is happening there - the pagination seems not to be working (though the pagination links are showing within the page.

PS Incidentally, I have some suggestions about how we could help support the Czech version. If you're involved in running the site, could you possibly sign up to:
https://lists.cyclestreets.net/mailman/listinfo/cyclescape-development
and we could discuss there a suggestion I have?

**Comment by washeck** [comment]
The thing is that on the page load, not only the latest issues (the "List" tab) with pagination is rendered but also the "Map" and "Popular" tabs (they are hidden but present in the html source code). And if you have a look at http://www.cyklistesobe.cz/issues#popular-pane you see this tab is not paginated at all (and has hundreds of issues). I don't know why you don't see this on Cyclescape (may be there are not so many issues or people don't click so much on the vote button).

The fix could be either to paginated "Popular" tab as well or limit the number of issues displayed there.
I thought this code
`popular_issues = Issue.plusminus_tally(start_at: 8.weeks.ago, at_least: 1).includes(:created_by)`
in issues_controller.rb would do some filtering but I don't fully understand what it is meant for (display only issues no older that 8 weeks?)

**Comment by gravitystorm** [comment]
It counts only votes cast in the last 8 weeks. You're correct in that it should be paginated, or at least limited to a particular number of responses.

**Comment by washeck** [comment]
@gravitystorm: Thanks for explanation. Could you please help me with a hotfix change of the query (e.g. hardcode a limit of issues) that we could apply? Currently the page load time is in minutes and it was reported to force browser to download more than 50 MB of data so I'd like to take at least a temporary measure.

**Comment by gravitystorm** [comment]
Try something like: `Issue.plusminus_tally(start_at: 8.weeks.ago, at_least: 1).includes(:created_by).limit(50)`

**Comment by washeck** [comment]
Thanks, this helped. I'm not closing the issue to leave it open for your decision about fix in Cyclescape code.
