### ISSUE TITLE
iCal output for dates/deadlines listing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#368]
It would be useful for the dates & deadlines listing at
http://www.cyclescape.org/overview#deadlines

to have an iCal output, as then people can embed this in their calendaring system.

This is as requested by a few users of the Cambridge group, at:
http://camcycle.cyclescape.org/threads/339#message_21553

**Comment by mvl22** [comment]
No doubt there is a Ruby gem, but on open source implementation (by me) in PHP can be seen at
http://download.geog.cam.ac.uk/projects/ical/ical.php
which may give some clarity as to the format. See the function 'create', which shows it is reasonably simple.

**Comment by mvl22** [comment]
I've finally spotted this, below the long list I had.

Can you have this floated to the right of the
"Upcoming deadlines and dates within the discussion threads you are subscribed to"
text.

Perhaps use this icon rather than text:
http://community.dur.ac.uk/grey.jcr/lib/img/icons/ical.gif

**Comment by mvl22** [comment]
Can a single-event iCal attachment be added to the deadline/date e-mail message?

**Comment by mvl22** [comment]
Report of slight bug:

There seems to be a bug in the .ics file format in event notifications. Since a month or two ago, my email reader (eM Client) produces the following error message whenever one of these emails arrives:

```
iMIP Error 

The following problem occurred when processing an iMIP message: The
iCalendar doesn't have valid beginning ('BEGIN:VEVENT').
```

**Comment by nikolai-b** [comment]
If this bug is from you I think it is related to this:
https://rollbar.com/cyclestreets/cyclescape/items/43/

Your public token on the staging site is different to the public token on the prod site.  I sent an email but you might have missed it.

If it is someone else could you PM me more details?
http://severinghaus.org/projects/icv/

**Comment by nikolai-b** [comment]
@mvl22 bump?

**Comment by mvl22** [comment]
No, the bug report is feedback no. 1773 in the admin area.

**Comment by mvl22** [comment]
I can now reproduce the problem. If you download the .ics attachment that comes with an e-mail, you get something like:

```
BEGIN:VEVENT
DTSTAMP:20160105T192549Z
UID:cdf56fde-4783-4c70-955c-32aed7e0c9e8
DTSTART;VALUE=DATE:20160204
DESCRIPTION:North Area Committee 4th February 2016
SUMMARY:North Area Committee\, Chesterton Community College
URL:http://www.cyclescape.org/threads/827#message_28702
END:VEVENT
```

If you validate that at:
http://severinghaus.org/projects/icv/

It gives:

```
Sorry, your calendar could not be parsed.
Error:	Error was: Error at line 1: Expected [VCALENDAR], read [VEVENT]
```

**Comment by nikolai-b** [comment]
(note this is in staging not master....)

**Comment by mvl22** [comment]
Hard to test, but code looks fine and this is all low-risk changes type stuff, so fine to make this live.

**Comment by roxannedebeaux** [comment]
Not sure if this is the right place to comment... 

The iCal feature creates an all day event in my calendar. Is it possible for it to import the event start time? As there is no end time in Cyclescape perhaps the events should import as 1 hour duration.

**Comment by nikolai-b** [comment]
Good point @roxannedebeaux, I think I've fixed this but hard to tell across all iCal readers.

On a side note:
For me it is much easier to track things if they are made as a new issue and link to the old issue on GitHub if relevant.  Otherwise it isn't clear what is a priority, what is new, e.t.c.

**Comment by roxannedebeaux** [comment]
No problem, I am still learning how to best use github so I welcome any
tips!


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*
