### ISSUE TITLE
Google Street View integration

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#37]
Google Street View is need in three places:

 * Setting of a location as a message reply type. Campaigners will undoubtedly use this heavily. It should result in an iframe directly, not a link elsewhere.
 * A button under the issue map which opens a div underneath showing 'Street View here'.
 * Ditto, under the map on the thread page

This enables people to get more context easily about the issue, as well as helping newer campaigners to familiarise themselves with the location.

The location should obviously default to the issue's location.

Key problem is how to handle large area-based issues. As a first iteration:

1. For large areas, state that 'The area is too large' to create a Street View location.
2. For smallish areas, take the centre-point.
3. For lines, take the centre-point of the line
4. For point-locations, obviously just take that location.

Setting of a location in the message-reply type will need a map view and the streetview panel next to it, with the location matched in real-time as the location is dragged, enabling people to get an accurate location first time.

**Comment by mvl22** [comment]
The code to display a Street View panel, and then capture the location once the user has interactively changed the position is here:

https://developers.google.com/maps/documentation/javascript/examples/streetview-events

which looks fairly easy.

**Comment by mvl22** [comment]
This is now live, but it's clear to me that one further iteration is going to be needed for full usage.

On the main Google website, when using Street View, there is a small window in the corner, that lets you drag the 'Street View person' around, so that you can jump easily to a location which isn't so near.

I think this shows the same thing, albeit with a massive map instead of a smaller one.
https://developers.google.com/maps/documentation/javascript/examples/streetview-simple

I think this is unfortunately necessary, as the second time I've tried to use this useful new facility, here:
http://camcycle.cyclescape.org/threads/1818
results in being stuck in the nearby cemetery with no way to get out of it.

Similarly, with an area-wide issue, one would have to do a lot of clicking to get from the centre-point of Cambridge to wherever the wanted location is.

A third example of why it's needed is that if talking about a thread in one place, but you want to illustrate a similar location elsewhere in the UK/beyond, this isn't possible at present.

So the ability to jump to another place on the map would be good.

**Comment by nikolai-b** [comment]
Yes, fully agree.  As this is a view change only from a new feature I've pushed it straight to master.  Let me know if you like it!

**Comment by mvl22** [comment]
Thanks; now rolled out and works nicely - thanks.

**Comment by mvl22** [comment]
http://camcycle.cyclescape.org/threads/227
is giving error 500 now - can't see why it's happening only on this thread though:

```
Completed 500 Internal Server Error in 1396.4ms

ActionView::Template::Error (undefined method `centre' for nil:NilClass):
    14:       = f.action :submit, button_html: {class: "btn-green"}
    15: 
    16: :javascript
    17:   var svLatNew = #{@issue.centre.x};
    18:   var svLongNew = #{@issue.centre.y};
  app/views/message/street_views/_new.html.haml:17:in `_app_views_message_street_views__new_html_haml__29791032691838047_41305760'
  app/views/messages/_new.html.haml:50:in `_app_views_messages__new_html_haml__736138200415199587_70068040378700'
  app/views/message_threads/show.html.haml:33:in `_app_views_message_threads_show_html_haml__4453352178857280412_70068036132560'
```

**Comment by nikolai-b** [comment]
Looks like that issue doesn't have a thread.  This is probably because some admin has deleted it.  From the code it looks like threads don't have to have an issue.  Do you know why?

Although I have access to the server I don't have admin rights so can't log into rails to see if there are more threads without issues.  For now I've just pushed https://github.com/cyclestreets/cyclescape/commit/4bb6bbeb83b61f9158baab17f9ff68166c7373e4 which hides street view if the thread has no issues.

**Comment by mvl22** [comment]
Ah, yes, of course, that will be the problem.

Administrative threads (Discussion threads > Administrative) can have no issue. This is for stuff like organising meetings, etc.

It is still useful to have Street View as a reply type, and I think we should avoid inconsistencies of this kind.

I think a much better fix will be to set the centre-point of the group's area if it is a group-owned thread, or some specific location if it is not. In the latter case, I suggest the specific location be like an easter egg which has some significance to cycling. However, as I can't think of one, let's just put it at 10 Downing Street, London, for now.

**Comment by mvl22** [comment]
Ah, actually, it's simpler than that as (I'm pretty sure) you can't have administrative threads that aren't attached to a group. So just take the group's location's centrepoint for administrative threads.

**Comment by nikolai-b** [comment]
Ok, I'm going on the side of caution and have added https://github.com/cyclestreets/cyclescape/commit/e3af5110752ad397415def0fbcfb37e1a35755ce which will try:

1. the issues location (including deleted issues)
2. the groups location
3. the created by users location
4. a random location (as a fall back)

**Comment by smsm1** [comment]
You can have groups without a location, thus the easter egg/random location is still required.

**Comment by mvl22** [comment]
Thanks; now rolled out.
