### ISSUE TITLE
Planning application not coming through

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#371]
This planning application, 15/0844/REM, in Cambridge:
http://planit.org.uk/planapplic/Cambridge/15/0844/REM/ (web view)
http://planit.org.uk/planapplic/Cambridge/15/0844/REM/json (data view)
(which oddly says "*** not on map ***" - perhaps this is significant)

as scraped from
https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=summary&keyVal=NNVMYTDX07800

is not appearing in a Cyclescape planning application search:
http://camcycle.cyclescape.org/planning_applications/search?utf8=%E2%9C%93&q=15%2F0844%2FREM&button=

It does appear in this particular listing API call:
http://planit.org.uk/find/applics/json?limit=30&start_date=2015-05-01&auth=Cambridge&pg_sz=500&limit=500

Something is causing this not to be picked up.

I think the fact that it doesn't appear on the map (not sure why that should be), should not stop it still appearing in a text search.

**Comment by nikolai-b** [comment]
They won't be picked up currently as were explicit reject planning applications without locations (location being has a lat and lon in the api call).
I can't see a problem with pulling in ones without a location so if you want to let me know.

**Comment by mvl22** [comment]
Yes, please do add support for these.

I think the behaviour should simply be that these unlocated items do appear in the search but not in the area listings.

**Comment by mvl22** [comment]
https://github.com/cyclestreets/cyclescape/commit/0119aef39b026b88635a3f6787f4da43eb69a1c5 seems to be reverting the additional new areas?

**Comment by nikolai-b** [comment]
No. Just making the code compact (multiple areas per line). I was having to
scroll a bit too much.

**Comment by mvl22** [comment]
Ah sorry. Yes, please do make live when you're happy.
