### ISSUE TITLE
Minor bugs on /issues/<id>-<moniker>/threads/new

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#374]
On the (new) page when creating a thread from a newly-created issue, e.g.:

http://camcycle.cyclescape.org/issues/1696-west-cambridge-site-masterplan/threads/new

there are two bugs:

1) The page title is "New Thread on %{issue}"

2) The "Owned by" drop-down has very large text rather than the standard font size.

Otherwise this is a very useful improvement!

**Comment by mvl22** [comment]
> 1) The page title is "New Thread on %{issue}"

This is still an issue and presumably easy to fix.

> 2) The "Owned by" drop-down has very large text rather than the standard font size.

Looks like this got resolved.

**Comment by rbazinet** [comment]
Is there a valid URL so I can see the behavior? The URL from June 2, 2015 throws an error.

**Comment by mvl22** [comment]
@rbazinet Could you create an account on the main site and I'll send a new URL which will give you a reproduce case.

**Comment by rbazinet** [comment]
@mvl22 account created.

**Comment by rbazinet** [comment]
@mvl22 this is complete and committed to a feature branch.

**Comment by mvl22** [comment]
@nikolai-b I see this is ready for review on a branch at:
https://github.com/cyclestreets/cyclescape/commits/issue-374
