### ISSUE TITLE
Option to enable e-mail subscription as digest

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#375]
Request from a user today (and similar requests over the last few years) for a digest delivery of e-mails that day, as per mailman.

Implementation will need to ensure that the inevitable replies which contain say 20 irrelevant messages are properly stripped out if the user just replies.

As there is no generic address, this will probably need a "Reply here: " or "E-mail this address: thread-...@" to respond to this message.

**Comment by nikolai-b** [comment]
Some implementation thoughts:

Send out one email every n days for all the message thread notifications.
The email would have a no-reply@cyclescape.org type reply-to address.
Each message would have a mail_to link which would be how to reply.
The structure would be:

Thread 1
 Message 1
 Message 2
 Message 6
--
Thread 2
 Message 5
--
Thread 3
 Message 3
 Message 4

**Comment by nikolai-b** [comment]
@mvl22 any thoughts on above ^ ?

**Comment by mvl22** [comment]
What time of day is the digest sent?

I would suggest 8am - so it catches everything from the previous day, and ready when people wake up, near the top of their list.

**Comment by nikolai-b** [comment]
https://github.com/cyclestreets/cyclescape/blob/master/config/schedule.rb#L57

I went with a bit earlier in case some keen campaigner starts posting at 7am ish.

**Comment by mvl22** [comment]
6.50am is fine; thanks :)
