### ISSUE TITLE
Can't set privacy on initial thread

### ISSUE THREAD

**Issue by iainlane** [cyclestreets/cyclescape#379]
The thread users are prompted to create after submitting a new issue has fields "Title", "Owned by" and "Message" but not "Privacy" like subsequent threads have.

Sometimes I wish to create a thread and paste in an email conversation so that other group members are in the loop but I don't necessarily want these to be public.

**Comment by nikolai-b** [comment]
If the group is selected the the Privacy drop down appears now.
