### ISSUE TITLE
Links to documents sent by email don't work - get a 401 error

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#382]
If someone posts a link to a document, e.g. 
http://www.cyclescape.org/threads/1879/messages/23924/documents/799
and I follow that link from the corresponding email sent by Cyclescape, after logging in, I always get a page saying only "You are not authorised to access that page." (which is a 401 page). However, I can get at the document if I go to the original thread. Is the problem that the link sent in the email isn't actually correct (aren't messages done by an anchor), arther than being a correct link to which access is denied?

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape/commit/0f3b5290d1fecfb8ca8adc9b0c26ed5e3ccb1b47
