### ISSUE TITLE
Filtering of planning applications

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#386]
We've had the planning applications feed live for a while now. It's clear there's an awful lot of rubbish contained with them, to some extent crowding out the interesting ones, and so this thread is an attempt to build up a list of what we should filter. Some of this is probably best handled as upstream PlanIt API options.

**Comment by mvl22** [comment]
Cambridge:

**Conditions (implementation of specific conditions after approval)**

Planning conditions are almost always not of relevance, as the principle is not really changeable.

* 15/0587/COND6 Condition 6
* 15/0527/COND5 Condition 5
* 15/0467/COND13 Condition 13

**Tree works**

Never of interest.

* 15/273/TTCA T1 - Ash: fell
* 15/270/TTCA T1 - Prunus: reduce to previous pruning points (approximate reduction of 20%)

**Advert consent**

Probably never of interest, except maybe an obstructive bus stop in a cycleway, but that would already have to be a bus stop.

* 15/0902/ADV Installation of a fascia sign and hanging sign (both non-illuminated)
* 15/1074/ADV 1x Externally illuminated fascia sign
* 15/0905/ADV Painted shop name on front, corner and side of building with...

**Notes**

LBC - Listed Building Consent: These do seem to have the same type of documents and relevance as an ordinary planning application, e.g. "15/1008/LBC Provision of awning to front elevation. Reduction and alteration...".

**Comment by mvl22** [comment]
@smsm1 Shaun, can you look through the lists for Ipswich and add a similar posting?

**Comment by mvl22** [comment]
@georgio8 George, can you look through the lists for Camden/London and add a similar posting?

**Comment by mvl22** [comment]
I've updated the text above to include Certificates of Lawfulness for Existing Use or Development which I see is occasionally coming through also.

**Comment by mvl22** [comment]
I see this is being done in the import stage. However, I think this should be done in the view side, because:

1) We lose historical data if we later realise we want to re-enable them (without having to do a full historical re-pull from upstream.

2) A search for a known planning application number which is within one of the groups now being filtered will not come up.

Is this easy to adjust?

**Comment by mvl22** [comment]
I've adjusted the list above to include TTPO - can we add this in too please.

My list still has:

"14/1896/COND6 Condition 6"
"15/525/TTPO T1. Prunus [...]"

which in theory should be filtered.

I wonder if the regexp is being checked against the whole string (consisting of reference + optional description), rather than just the reference part?

**Comment by nikolai-b** [comment]
Added TTPO in 78d8154ba
I can't see any COND6 in my list, could you check again and add a link to it (hopefully the query just hadn't finished updating)?

**Comment by mvl22** [comment]
Ah, I spot some are coming through with just /CON[0-9]+ i.e. CON not COND:

11/0219/CON6 Condition 6

Can that be added too?

**Comment by mephillips-durham** [comment]
Examples for Durham:

**Certificates of lawfulness**
DM/16/01270/COL Application for Certificate of Lawfulness for proposed change
DM/15/03790/COL Construction of new rear dormer window

**Advert consent**
DM/16/01231/AD Display of 1 no. 7.5m high internally-illuminated
DM/15/03850/AD Internally illuminated fascia signage

**Conditions**
DM/16/01372/VOC Variation of condition 4 on planning permission
DM/16/01331/VOC Variation of conditionn to extend opening hours

**Tree works**
DM/16/00780/TCA Fell 1 No. Oak Tree
DM/16/00787/TCA Reduce by 3m to previous pruning point
DM/16/00421/TPO Various tree works

**Comment by jf1** [comment]
Still too much rubbish in my planning feed so hope you can filter these out...

[This](http://gmcc.cyclescape.org/planning_applications/uid/111950/AO/2016/N2) has /AO/ in its title (adverts).
[This](http://gmcc.cyclescape.org/planning_applications/uid/111986/TCA/2016/S1) has /TCA/ in its title (trees).
[This](http://gmcc.cyclescape.org/planning_applications/uid/60075) has "Certificate of lawfulness" in its description, and [this](http://gmcc.cyclescape.org/planning_applications/uid/DC/061737) has "Certificate of lawful development" - so they share: "Certificate of lawful".
[This](http://gmcc.cyclescape.org/planning_applications/uid/DC/061751) has "Discharge of conditions" in its description.

You're also welcome to hide any with "extension" or "loft conversion" in their descriptions.

**Comment by nikolai-b** [comment]
We need an admin interface, with a region select drop down and regex.  Agreed @mvl22 ?

**Comment by mvl22** [comment]
No, I think we should try to get this dealt with upstream.

For now I think we should hard-code the examples above.

**Comment by nikolai-b** [comment]
Why would PlanIT want to remove these? Aren't they showing all the planning applications?  We will want to filter them all based on our specific requirements.

**Comment by mvl22** [comment]
No, I'm suggesting that they provide a field which classifies each application with a code, generalising the different things for different areas to a standardised set of codes. That is after all what they are doing in general terms with other aspects of each planning application.

We can then just exclude standardised classes of application based on those codes.

**Comment by nikolai-b** [comment]
For me this doesn't make sense because:

* this shifts the onus of work of finding a UK wide classification system onto Planit
* removes our ability to fine tune what we show / hide

Having an admin section with authority and regex rule and hiding applications where this matches gives us complete control.  Even if PlanIt add a standard field we'd still need to decided what to listen to / hide.

**Comment by nikolai-b** [comment]
It is a short job to add a filter and I'd really like to make planning applications far more useful for you which I think this will.  Are you happy to see how it feels on staging?

**Comment by mvl22** [comment]
Obviously we can't be prejudge what PlanIt might want to do, but this makes much more sense to have this done upstream because it is likely that most client applications are likely to need filtering.

People interested in tree protection don't want to see stuff about advertising boards. People concerned about neighbours' extensions won't want to see stuff about listed building consents. And so on. The fact that we, as the first actual client user of PlanIt data, have immediately run into this issue means that it's almost certain that others will have similar requirements.

There are 439 planning authorities. Cambridge already has 4 filters in place, with more likely, and it's probable that the same will be needed for the others. It doesn't scale for every client application to have to define and maintain around 1,600 regular expressions in the ultimate case. Even if we took London and say 20 other areas, that's still hundreds.

PlanIt is already doing various work to analyse each Planning Authority's output, and write conversions for each. So it would make a lot of sense if, as part of that existing process, filters were defined and maintained at that level.

Also, many local authorities use the same systems. But PlanIt has already generalised away the vendor type, so we don't see it. So what can be specified at the PlanIt API level once (for say the 40%+ (?) of LAs that use IDOX) at scraper level, would for us have to be specified individually for each one, and we'd have to work out which set of regexps for which LA.

Of course, PlanIt may not want to put this on their roadmap, in which case this is all academic. But I'd rather that be investigated before we start building machinery to maintain lengthy regexp lists ourselves.

**Comment by jf1** [comment]
There's nothing lost in asking PlanIt, but I thought they just used the exact reference provided by the PA.

I think you're right to estimate that approx half of the PAs use the standardised IDOX system, and hopefully more will start using this or another standardised system soon. But even if everyone did, such systems may change over time so some local admin of the filtering options would still be required.

It'd make most sense to have the standardisation applied further upstream, by the PAs themselves, so if PlanIt aren't minded to implement and maintain new filters then perhaps a similar outcome could be achieved by approaching eg an LGA data person.

However it happens it'd be nice if there was some way to make the non-IDOX feeds usable.

**Comment by nikolai-b** [comment]
@mvl22 It seems relatively simple, we want our own regex on IDOX authorities and the ability to have regex on non-IDOX.
A simple admin system is that you add regex and select no authority and it would be applied to all authorities without their own regex (or using some other criteria, i.e. a checkbox of IDOX authorities), other authorities would have their own.  That way if PlanIt implement something we can use it.  Cambridge doesn't have four filters by the way, it has one regex https://github.com/cyclestreets/cyclescape/blob/staging/app/models/planning_application.rb#L93  `\/(TTCA|TTPO|COND.*|CON\d*|CLUED|ADV)$`

I've built a simple admin interface which I believe will be useful even if there is standardisation upstream. That said I'll leave it for now till we hear back from PlantIt

**Comment by mephillips-durham** [comment]
Another, totally different, approach would be Bayesian analysis of the applications that people vote to hide and those which actually get turned into issues. Filtering based on the type of application, even if provided by PlanIt, will not help with the suggestion by @jf1 above to hide anything with "loft conversion" or "extension", but Bayesian analysis would.
Obviously a lot more work though. Personally I'd settle for an admin interface to have regexps for filtering on the application number. Although there are 429 authorities there are many few than that with cycle campaigns active on Cyclescape, and if it's the responsibility of the group then it becomes scalable.

**Comment by mvl22** [comment]
Cambridge further example to filter out:

16/1148/NMA - Non Material Amendment

**Comment by mvl22** [comment]
TTCA, ADV, etc. are now re-appearing in my stream, presumably because the code-based filter has been removed but no equivalent has been reinstated in the new form at `/admin/planning_filters/new`, which I don't know how to use as there is no guidance adjacent to it.

**Comment by nikolai-b** [comment]
https://github.com/cyclestreets/cyclescape/issues/386#issuecomment-217481866

**Comment by mvl22** [comment]
`translation missing: en-GB.admin.planning_filters.create.success`

**Comment by mvl22** [comment]
I've copied that in, but still got no idea if I'm doing the right thing. It seems to have had no effect. Not sure if I'm supposed to use the outer / ... / markers.

Interfaces like this *always* need guidance on how to use them, and what their limitations are.

For instance, if that only takes effect during a data import, that should be specified.

**Comment by nikolai-b** [comment]
Agreed, I have added guidance.
You are correct that the outer `/…/` are not required and were stopping the matching.  They are ruby shorthand for "this is a Regex", sorry.

**Comment by mephillips-durham** [comment]
So can the examples I provided for Durham be filtered out? Do I have to set this up somewhere, or does someone else do that?

**Comment by nikolai-b** [comment]
@mephillips-durham very sorry I missed that.
I've added a custom filter for Durham
`\/(TCA|TPO|VOC|AD|COL)$` as it seems this is slightly different from other regions.
This should be updated now.

**Comment by jf1** [comment]
Any sensible filters you can apply for the 10 LAs in GM would be
appreciated. And Cheshire West too if that's straightforward (it's outside
of GM but we're unable to easily avoid it in Cyclescape as we can't yet
choose a political area so have to set locations by drawing straight lines)

**Comment by mephillips-durham** [comment]
Thanks @nikolai-b that is working.
