### ISSUE TITLE
Richtext editor support [was: 'Display tables within a thread comment']

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#390]
It would be useful to show tables within a thread comment, as per a discussion in a LCC group.

**Comment by nikolai-b** [comment]
Sorry but I don't understand what this means.  Could add some links and more expatiation (i.e. what tables are you referring to?)

**Comment by smsm1** [comment]
As in rich text editing.

**Comment by nikolai-b** [comment]
To be clear you want a WYSIWYG editor for threads?
That is a large change, could you explain it bit more?  E.g.
* Do you want to add only HTML tables using a WYSIWYG?
* Do you want people to be able to change the font?

Sorry for the questions I just don't think I follow you.

**Comment by mvl22** [comment]
This is a basically a request for WYSIWYG richtext (HTML) editing. NB I would not be in favour of a bbcode-style implementation where people have to type in special codes.

For this we could (should) use CKeditor. This gives the ability to select carefully what richest elements are wanted. For instance, we should allow semantic elements like list items and tables, and very limited presentational attributes like bold and italic (not underline) but not setting of font colours.

It would need to parse the HTML that is generated and ensure any non-permitted tags are filtered out, and that there is no Javascript (for security) or CSS.

When sent by e-mail, the message will need to be a multipart e-mail with both plain text and HTML parts so that the message remains easily-readable by those of us using text-based mail clients.

This it will need to generate a plain-text equivalent of the HTML. For instance, a section of text in bold would have a * surrounding it on either side, which is the common way to represent emphasis in plain text messages.

I think the richtext editor should be an optional mode. Effectively the editor area should have a very small button "Edit as richtext" which toggles between plain text and richtext. The default should remain plain text as we want to encourage people to express themselves by the clarity of their writing, rather than how much they can make bold.

Possibly the toggle should set an internal setting (rather than a computer-specific cookie) which remembers the last type used. On the other hand that would encourage its use when plain text would be fine.

The toggle will need to avoid losing whatever has already been written if the user then switches.

There is with any luck a gem which handles this stuff!

**Comment by nikolai-b** [comment]
Yep, I'd looked at https://github.com/tsechingho/ckeditor-rails but wanted to check that is what you were after.  I'll leave this for now until you prioritise it.

**Comment by mvl22** [comment]
This will probably go in the next tranche, which will include various features requested by LCC.

PS Can I just say that expatiate is one of my favourite words. Thanks for using it!

**Comment by smsm1** [comment]
I'm pretty sure it was through one of the LCC groups that I had seen this request, as they were trying to include a table into the thread, and instead it was plain text formatting and difficult to read.

**Comment by mvl22** [comment]
Request for Markdown:
https://twitter.com/SpacePootler/status/698183643005517825

**Comment by davidearl** [comment]
I agree with you Martin (in the other thread), markdown really, really isn't suitable in this context. It's OK for github geeks, but not for a general purpose content editor.

TinyMCE has improved dramatically since I looked a while back. I've been working with it in Cameo (the camcycle membership database) recently.

**Comment by mvl22** [comment]
I'm keen to hear from users about the underlying desire for 'Markdown', or whether a GUI editor would do the job, but heavily cut down to avoid pointless stuff like coloured/resizing fonts, etc.

**Comment by davidearl** [comment]
Markdown is a useful but geeky tool. It's not suitable in cyclescape IMO.
(You could offer it as a user settable option I suppose for the geeks).

But more importantly, one of the main reasons to have this is so you can
put images and other content inline. So it's got to be able to include an
image uploader, and that's well beyond the scope of plain markdown. This
would also avoid the huge usability problems of the single content type
data entry panel at the bottom of threads.

However you do this, formatted text demands formatted emails please!

(And why shouldn't we have coloured larger text? Its another method of
emphasis.)

**Comment by spacehobo** [comment]
You don't need to support images.  But it would be nice to have some of the basic formatting taken care of, and markdown helps sanitise input so you don't get html tags inserted raw.

**Comment by nikolai-b** [comment]
@mvl22 how does this fit in with #572 as now text will be treated as HTML?  What I could do is on messages (and issues), store a body which would be from the text box OR and body_html which would be from the WYSIWYG Editor.  

Then for email...
I guess now would be the time to consider sending HTML along with pain text emails as many users will use the WYSIWYG Editor and be posting HTML messages.  Thoughts?

**Comment by mvl22** [comment]
I think what we basically want is what I'm typing into Github right now - a WYSIWYG editor, completely replacing the standard text box, that contains basic formatting controls. Though it would be useful to have tables as well, as per the original request.

On processing it, the HTML should obviously be sanitized to avoid any nasties.

The e-mails should send out HTML with a plaintext representation generated on the fly, with both sent as a multipart e-mail. That plaintext representation would have things like bullets become dashes, each paragraph has a line-break, etc. - I'm sure there must be a Gem to do that kind of thing in a sensible way.

I'm not sure if we need a preview function like this Github box does.

**Comment by davidearl** [comment]
I disagree. The github one is a markup language, and far too geeky for non programmer use. The buttons help, but the text is still markup.

I’ve easily and successfully integrated tinymce into Cameo and Ensembling, and another data entry product, and it’s the editor in WordPress so it’ll be familiar to a lot of people. It has a lot of control for doing things like custom image uploads. But mainly it really is WYSIWG, which github definitely isn’t. It’s not perfect, but it’s the best solution I’ve found in doing this in multiple contexts.

**Comment by mvl22** [comment]
> The github one is a markup language, and far too geeky for non programmer use

Ah sorry, you're right - I didn't actually press the bold, etc. to try, but thought it did that - yes, we do indeed want to use a proper WYSIWYG component.

**Comment by nikolai-b** [comment]
I'm a bit lost.

 
https://github.com/cyclestreets/cyclescape/issues/390#issuecomment-120592622

> I think the richtext editor should be an optional mode. Effectively the editor area should have a very small button "Edit as richtext" which toggles between plain text and richtext. The default should remain plain text as we want to encourage people to express themselves by the clarity of their writing, rather than how much they can make bold.

https://github.com/cyclestreets/cyclescape/issues/390#issuecomment-404198930

> I think what we basically want is ... a WYSIWYG editor, completely replacing the standard text box, that contains basic formatting controls.

Having HTML / WYSIWYG component (most likely Ckeditor) always on would make life easier.  Then all future messages would be HTML (minus the nasty bits). 

What about attachments?  With Ckeditor we could allow users to upload a normal image or documented so it'd remove the need some of the extra tabs.  If we can get the deadline functionality included then we'd be nearly there!  The other message types are used far less frequently.

**Comment by davidearl** [comment]
Why does it need to be optional? If all you want is plaintext, you just
don't touch any of the buttons.

**Comment by nikolai-b** [comment]
![screenshot from 2018-07-12 20-05-05](https://user-images.githubusercontent.com/6289830/42653977-fd170508-860e-11e8-9d32-422771332704.png)

Here is a very rough idea as how Ckeditor could look on the message edit.  There is a [config tool](https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic) that makes it easy to pick a limited set of controls.

**Comment by davidearl** [comment]
Can I suggest you use the auto save plugin. People are bound to spend a
while composing messages only to find their session has timed out.

Also, save in words, floppy disks are getting that people don’t recognise
them these days. Anyone under 20 won’t ever have used one.

Source at the end - it’s a geek option.

Ckeditor is a very old name for this. Can you use tinymce version 4: it
nests elements much better than older versions.

**Comment by mvl22** [comment]
> Why does it need to be optional? If all you want is plaintext, you just don't touch any of the buttons.

Correct. This should be the only option for text. Ignore my earlier comment "I think the richtext editor should be an optional mode."

> With Ckeditor we could allow users to upload a normal image or documented so it'd remove the need some of the extra tabs.

Definitely not. The CKEditor image and upload UIs are very poor and non-discoverable. We should be handling only simple message editing in this change, and not expanding the issue to rework the UI.

**Comment by mvl22** [comment]
> Here is a very rough idea as how Ckeditor could look on the message edit. There is a config tool that makes it easy to pick a limited set of controls.

Yes, that's fine.

CKEditor does indeed let you get rid of a lot of stuff. Could we lock this down to only:

* Bold
* Italic
* Unordered list
* Ordered list
* Table
* Link
* Quote

which gives a nice clean toolbar that will enable people to find these 99% use-case buttons easily.

I don't think we really need anything else. This is pretty much the same set as Github has, minus headers (which are rarely used, and bold is acceptable in this rather limit context of sending a message.

Source is indeed not necessary - we don't want people fiddling the HTML.

**Comment by davidearl** [comment]
I'm not sure there's much point in spending time on this without the ability to interleave images, and it's not really rich text editing without, and there isn't currently any way to put images in context. In GitHub and others, it is a matter of simply pasting an image.

And the big problem with images currently is the un-obvious UI where people try to augment their post with an image by clicking the other tab, and lose their text - they are expecting both to work and they don't.

**Comment by mvl22** [comment]
> And the big problem with images currently is the un-obvious UI where people try to augment their post with an image by clicking the other tab, and lose their text - they are expecting both to work and they don't.

That's basically issue #287. I'd rather we didn't overload this ticket with reworking the whole UI at this stage. Let's get Richtext in, and solve that other problem separately on #287.

**Comment by mvl22** [comment]
> In GitHub and others, it is a matter of simply pasting an image.

I'd quite like us to get a UI that does that, yes. But I don't think either the CKeditor4 or TinyMCE route to that, which both use a rather horrid dialog box, is the way to go.

Hopefully addressing the lack of core richtext will act as the stimulus for reworking #287 at long last.

**Comment by davidearl** [comment]
That's only the default dialog box (which in tinymce asks for a URL), and that clearly isn't appropriate. What needs doing is substituting your own uploader, so that you click image, choose a file (ideally also with a drag/drop/ but choose file button would be good enough) and it then does the rest. Assuming handling the image uploads is straightforward server-side (and I imagine it is, given the existing image upload tab), then adding this dialog isn't hard (I speak from tinymce experience, but I think ckeditor came from the same roots, so I imagine it is similar - if not, I'd consider tinymce instead!)

**Comment by nikolai-b** [comment]
![TinyMCE](https://user-images.githubusercontent.com/6289830/43960969-9badcf00-9cab-11e8-977c-d904a294df13.png)

Changing to TinyMCE as that gem better maintained and uses the latest TinyMCE version.  I couldn't find a CKediter5.  For email I think that sending the emails as HTML and adding https://github.com/soundasleep/actionmailer-html2text will work.

**Comment by mvl22** [comment]
Cool, looks fine. Nice to see it's nice and cut down to the necessary semantic elements.

**Comment by nikolai-b** [comment]
So this will mean all our emails will be HTML.  I can keep the format exactly the same but really I think the links should be anchors (`<a href="">`).  It means a slight change to the text, e.g.
As plain text:

---

Cyclescape discussion thread:
  https://www.cyclescape.org/threads/4291#message_55748
You can reply to the email and the message will be added to the thread.

Everyone can view this discussion thread and post messages.

You can stop following this thread by visiting
https://www.cyclescape.org/threads/4291/subscriptions/xxxyyy/edit?t=xxxyyyzzz

---

As HTML:

---

From Cyclescape [discussion thread](https://www.cyclescape.org/threads/4291#message_55748).
You can reply to the email and the message will be added to the thread.
Everyone can view this discussion thread and post messages.
You can [stop following this thread](https://www.cyclescape.org/threads/4291/subscriptions/xxxyyy/edit?t=xxxyyyzzz). 

---

@mvl22 my guess is you'll have strong feelings about this.  Also we have lots of
> You can see the Street View at: https:www....

how would you like these to be phrased with a link?

Finally, should we keep dashes to denote a footer or use an `<hr>`?

**Comment by mvl22** [comment]
> As plain text:
> As HTML:

Those look sensible to me - thanks.

> how would you like these to be phrased with a link?

Sorry - not clear what you mean. Do you want to put something in that you think seems sensible, and I can adjust if necessary?

> Finally, should we keep dashes to denote a footer or use an <hr>?

Horizontal Rule makes sense for HTML, and dashes for text.

**Comment by nikolai-b** [comment]
> Sorry - not clear what you mean. Do you want to put something in that you think seems sensible, and I can adjust if necessary?

As Text:

---
User added a street view to the thread

This is a street view caption.

You can see the Street View at:
http://www.example.com/

---

As HTML:

---
[User](www.example.com) added a [street view](www.example.com) to the thread:

This is a street view caption.

---

With images should I embed the image?

**Comment by mvl22** [comment]
> With images should I embed the image?

Is that possible, i.e. does the hash work outside the site context?

**Comment by nikolai-b** [comment]
@mvl22 

I don't see why it would fail.

Images from
https://www.cyclescape.org/threads/4287#message_55723
work on Github:

![](https://www.cyclescape.org/media/W1siZiIsIm1lc3NhZ2VfcGhvdG9zLzY0Mi84MWQvNjQyODFkNTMyZWQ1OThjYzhkMzhmYmE2ZjYxZDdhMDU5MjRiZjFmNV83YzZwIl1d?sha=62ff094df70cc0f2)

I've merged this onto staging.
