### ISSUE TITLE
Subdomain-specific homepages lost

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#391]
http://camcycle.cyclescape.org/ and similar homepages are showing the www front page rather than their area.

I think this must have happened as a regression during the Rails 4 upgrade.

When this is fixed, please do include test for this.

**Comment by nikolai-b** [comment]
Fixed in 5d145c4, I'm leaving it open till after you've deployed.

**Comment by mvl22** [comment]
Thanks - all deployed and fine.
