### ISSUE TITLE
Dynamic hiding of page components not reliable

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#393]
Since the Rails 4 upgrade, I've noticed that the javascript trigger (whatever it is), which causes parts of the page to be hidden dynamically, e.g.

* the tag editing block near the top of the thread page
* the reply area, where the plain text editor is the default, and the other types are hidden behind it.

doesn't seem to happen the first time the page is viewed. Pressing refresh does do it OK though.

The auto page-scroll-down mechanism also does not fire.

So feels like Javascript stuff just isn't being loaded reliably.

I'd regard this as high priority against other tickets, as it's a regression.

**Comment by mvl22** [comment]
First view:

![first-load](https://cloud.githubusercontent.com/assets/361423/8632980/09d23b7e-27ac-11e5-94b5-e5d189cf2857.png)

After pressing refresh:

![after-refresh](https://cloud.githubusercontent.com/assets/361423/8632981/1394d6b2-27ac-11e5-997f-e1d4d958327e.png)

**Comment by nikolai-b** [comment]
Yes, we have reached a point where #366 has started to throw up lots of issues.  I am working to fix this https://github.com/cyclestreets/cyclescape/tree/remove-jquery-tools
