### ISSUE TITLE
Update/remove new group text at bottom of groups list

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#394]
There is the text "To create a group on Cyclescape for your local cycling campaign please send some feedback and we'll get back in touch with you soon." at the bottom of the groups page http://www.cyclescape.org/groups, which needs to be updated or possibly removed as there is a link to the new form at the top right.

Someone requesting a group, has been caught out by this, thus delaying their group creation.

**Comment by mvl22** [comment]
While we're at it, could we make the group request form a better hierarchical URL:

/group_requests/new
->
/groups/request

**Comment by nikolai-b** [comment]
Thanks @smsm1, I've removed the text.
@mvl22 apply isn't a standard CRUD action.  We can make it `/groups/group_request/new` or `/group/requests/new` but this unnecessary nesting.  It also would mean that the order of the routes.rb file would matter as `group/:id` and `groups/apply` would conflict.  It can be done but I'd prefer not to.

**Comment by mvl22** [comment]
I take the point about the ordering and I agree that should be avoided.

However, it doesn't feel right to me that we have a correct hierarchy /groups but that the creation of a new one, albeit via a moderation stage, is in a different hierarchy (group_request) entirely.

(This is not high priority though!)

**Comment by nikolai-b** [comment]
Just to explain my rational: a group has members, membership requests,
issues etc but a group does not have group requests. These don't belong to
a particular group.

**Comment by mvl22** [comment]
> These don't belong to a particular group.

Yes; I suppose.

I see a group request as simply a group that hasn't had its moderation flag enabled. At least that's how we treat these things in CycleStreets - an entry in the same table but just with one field different. I must admit I'd not looked at how you'd implemented it here. Ah yes; I see yes it is different:

https://github.com/cyclestreets/cyclescape/blob/master/app/models/group_membership_request.rb#L3-L12
