### ISSUE TITLE
Adding library items to issues 

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#396]
When I try to select library items the form to add them does not appear https://github.com/cyclestreets/cyclescape/issues/389#issuecomment-120599169
Fixed in https://github.com/cyclestreets/cyclescape/commit/ce21c276ab6afad8d56f76eee7860537bca14245 but wanted to check if others we experiencing this.

**Comment by mvl22** [comment]
The intended UI, which works for me in Chrome, is:

1) User sees two options - Compose New or From Library:
![1](https://cloud.githubusercontent.com/assets/361423/8681144/b3b675f2-2a5d-11e5-9d62-a10bffe1114e.png)
(whether that is the best UI is open to question - this could change as we expand the number of reply types).

2) If the user clicks on From Library, they get a list of Library items:
![2](https://cloud.githubusercontent.com/assets/361423/8681180/ec184ae2-2a5d-11e5-9b45-2f7818971943.png)
(This is supposed to show only Library items that match the current tags; but there is a bug which means the latest items added are shown; this needs to be fixed at some point.)

3) Clicking on a Select... slides the internal panel to the left with an animation, showing this screen:
![3](https://cloud.githubusercontent.com/assets/361423/8681229/35619190-2a5e-11e5-85f1-cd9aedb478c6.png)

At this point the user can add a comment and use the (rather tiny at the moment) green button to add the Library reply to the thread.

**Comment by nikolai-b** [comment]
same causes as #393
