### ISSUE TITLE
Duplicate entry in en-GB.yml - planning_applications_introduction_html

### ISSUE THREAD

**Issue by fabianhjr** [cyclestreets/cyclescape#398]
https://github.com/cyclestreets/cyclescape/blob/master/config/locales/en-GB.yml#L174

is a duplicated

https://github.com/cyclestreets/cyclescape/blob/master/config/locales/en-GB.yml#L176

**Comment by nikolai-b** [comment]
Thanks, fixed in https://github.com/cyclestreets/cyclescape/commit/bac6f70c063952f1e5e142cfed5a78c4a7173140
