### ISSUE TITLE
Reply type which sets a call to action

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#399]
In order to further actual _action_ on an issue, the thread needs to have a reply type or a tickbox which sets a specific call to action.

1) Users can reply or tick to specify the type of call to action, e.g. "Consultation letter needs writing", "Press release needs drafting".

2) Box on page lists the outstanding actions

3) When replying to an issue, a user can 'tick off' a specific one in the list at the type they submit a posting.

See also some background at issue #302.

**Comment by nikolai-b** [comment]
Adding a new type is easy, just would like to check how you would like it to look.

When an action is created it would send out an email saying

> User 2 requested action "Consultation letter needs writing" on thread

It would have a status bar in red (orange) in the thread.
When completed it would send out an email saying

> User 3 has completed action "Consultation letter needs writing" on thread

And the status bar would be greyed out saying completed


## Message Thread with no outstanding actions

Text | Photo | CycleStreets photo | Street view
Link | Deadline/date | **Action**

Create a new action/ task that is related to this discussion:

Text box
Placeholder: Describe the action that is required, e.g. consultation letter needs writing

Create new Action

## Message Thread with an outstanding action Version 1

Text | Photo | CycleStreets photo | Street view
Link | Deadline/date | **Action**

Outstanding actions:

* Consultation letter needs writing  [Done] (Done is a button)

Create a new action/ task that is related to this discussion:

Text box
Placeholder: Describe the action that is required, e.g. consultation letter needs writing

Create new Action required

## Message Thread with an outstanding action Version 2

**Text** | Photo | CycleStreets photo | Street view
Link | Deadline/date | Action

Text box

Post message 
- [ ] Completes action: "Consultation letter needs writing"
- [ ] Completes action: "Poster needs designing"

**Comment by mvl22** [comment]
Thanks for thinking this through - let me know when there's a UI to see in due course.

**Comment by nikolai-b** [comment]
Do you want version 1 or version 2?

**Comment by nikolai-b** [comment]
@mvl22 do you follow my text based UI and which version do you prefer?

**Comment by mvl22** [comment]
I prefer the stuff with "Completes action" buttons underneath.

But I wonder whether actually that new set of controls should really be under the entire actions box, for each of the reply types, floated to the right hand side of the green button, essentially as a second column, easily accessible but not too easy to hit accidentally.

That way, it means that an ordinary action like sending a message or attaching a draft document can be strongly associated with that "ticking off" at the same time. Otherwise it requires two actions, resulting in two messages.

**Comment by nikolai-b** [comment]
@mvl22 this is on staging now.  When you've time please have a look.

**Comment by nikolai-b** [comment]
@mvl22 if your happy with this please let me know as I'd like it live before I merge in #777

**Comment by nikolai-b** [comment]
@mvl22 should I just release this?  It is becoming a blocker as its in staging now.

You can see the UI on https://github.com/cyclestreets/cyclescape/pull/766#issue-183270927 if that helps.

Thanks

**Comment by mvl22** [comment]
Thanks - this all looks great. Please do commit.

A slight improvement would be that `Resolves actions:` should be `Resolves action:` if there is only one.
