### ISSUE TITLE
Group page design has not been implemented fully yet

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#40]
The group page design needs to be finished.

**Comment by mvl22** [comment]
![homepage-group-v3](https://cloud.githubusercontent.com/assets/361423/7499251/3a92b61a-f41e-11e4-9d69-3bf405b399b3.png)

**Comment by nikolai-b** [comment]
@mvl22 sorry I don't think I can currently help with this.  I've reverted back to that commit and the page looks nothing like the screen shot.  I've copied over the old CSS but didn't want to spend too much more time on it.  Do you have the HTML and CSS of that page?

In the meantime I've added the ability to add group profile images #384
