### ISSUE TITLE
New discussion on an issue includes site header/footer in frame

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#400]
When I create a new discussion on a thread, the header and footer of the site header and footer are included in the frame, which reaches below the page, and also means it's too wide so don't see the submit button. Scrolling vertically moved the main page in the background and not the frame content, meaning that you have to have a big enough monitor to scroll vertically if required. Browser Safari 8.0.7 on Mac OS X 10.10.4. The same happens on Chrome.

![screenshot_17_07_2015_14_12](https://cloud.githubusercontent.com/assets/82719/8747850/658acb5c-2c8e-11e5-975a-6a0637af9ec2.png)

**Comment by nikolai-b** [comment]
I've push what seems to be a fix in https://github.com/cyclestreets/cyclescape/commit/9c81e715607f40c9a824d5de33c1717a1f89fc5c to staging.  It effects all overlays, I've tested a few but it would be good to check them on a few different browsers first ( ping @mvl22 ).  When happy I'll push it to master.

**Comment by nikolai-b** [comment]
@mvl22 have you had a chance to look at the fix I've pushed to staging?

**Comment by mvl22** [comment]
Thanks for merging that into live - that's now live.

**Comment by nikolai-b** [comment]
Sorry I wasn't very clear.  I am planning to remove jQuery tools so https://github.com/cyclestreets/cyclescape/commit/9c81e715607f40c9a824d5de33c1717a1f89fc5c was a temp fix that meant the width was set correctly.  I've also added https://github.com/cyclestreets/cyclescape/commit/26771f1928a0505842143b40fa570e5c59c2e6e9 to remove the header and footer.
