### ISSUE TITLE
Library link is not firing properly

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#401]
If you follow a link to ```/library``` then click on "Add library item", nothing happens.

If you press refresh, however, it then does work.

I strongly suspect this is the same underlying cause (whatever it is) as #393.

**Comment by mvl22** [comment]
Actually, pressing refresh currently seems to make no difference.

**Comment by nikolai-b** [comment]
Should be fixed now

**Comment by mvl22** [comment]
Yep.
