### ISSUE TITLE
Cannot create thread for issue created from Planning Appplication

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#402]
Occurs when a new issue has been created from a planning application. When clicking on "discuss" to create a thread the pop up box is too large so the details cannot be entered and the submit button cannot be clicked.

**Comment by roxannedebeaux** [comment]
This can be worked around by going back to the list of issues and clicking from there.

**Comment by smsm1** [comment]
I think this will be the same as #400

**Comment by mvl22** [comment]
Duplicate of #400.
