### ISSUE TITLE
Password link on login page seems not to work

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#403]
https://camcycle.cyclescape.org/users/sign_in

the links at the end seem not to work.

**Comment by nikolai-b** [comment]
Could you expand on that?  It works for me.

**Comment by mvl22** [comment]
I've got a better debug now.

In Chrome, if you click on each of the three links on that sign_in page (obviously while not signed in), and switch on the debugging Console, you get (in order):

```Mixed Content: The page at 'https://camcycle.cyclescape.org/users/sign_in' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://camcycle.cyclescape.org/settings/sign_up'. This request has been blocked; the content must be served over HTTPS.```

```Mixed Content: The page at 'https://camcycle.cyclescape.org/users/sign_in' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://camcycle.cyclescape.org/users/password/new'. This request has been blocked; the content must be served over HTTPS.```

```Mixed Content: The page at 'https://camcycle.cyclescape.org/users/sign_in' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://camcycle.cyclescape.org/users/confirmation/new'. This request has been blocked; the content must be served over HTTPS.```

In each case; no navigation event happens.

**Comment by mvl22** [comment]
If I open in a new tab, e.g.
https://camcycle.cyclescape.org/settings/sign_up
this complains about a redirect loop.

**Comment by nikolai-b** [comment]
Removed turbolinks https://github.com/cyclestreets/cyclescape/commit/f619864daa5ce225c6c3c937e1e556aa361e82b4
