### ISSUE TITLE
Send feedback doesn't confirm that the feedback has been saved

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#404]
There have been several reports that the feedback box on submit doesn't return and confirm that it has been saved even so it has been saved in the system, meaning people are submitting several times thinking it hasn't saved.

Example report:
"When I sent feedback just now the button on this page changed to Saving... and stayed like that.

Just tried it again for this page but it keeps bouncing back to say "Send Feedback"."

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape/commit/40442df788e8a521cdd654182287b249526855df
