### ISSUE TITLE
Cannot convert planning applications into issues

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#407]
The "Send Report" button when converting planning applications in to issues results in:

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

I realise you may know about this but I just wanted to be sure.

**Comment by mvl22** [comment]
@nikolai-b Is this a simple fix?

**Comment by nikolai-b** [comment]
Thanks for reporting this @roxannedebeaux , can you let me know which issue as it worked for the one I tried.

Thanks.

**Comment by roxannedebeaux** [comment]
Hi Nikolai,

That has been the case for every planning application that I have tried to
convert to an issue. I can't indicate any particular issue for you to look
at as now whenever I click on a planning application I get a 404.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: contact@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/

**Comment by mvl22** [comment]
Yes, I'm getting a 404 also myself - sorry I didn't spot this before rolling out 4.1.

**Comment by nikolai-b** [comment]
Please can you give a link?

I've just tried it on the production and it works for me:
http://www.cyclescape.org/issues/1869-planning-application-epf-1025-15-single-storey-front-side-and-rear-extensions

**Comment by mvl22** [comment]
Was that a regression caused by different handling in the new version of Rails, out of interest?

**Comment by nikolai-b** [comment]
Yes, in this commit https://github.com/rails/rails/commit/5460591f0226a9d248b7b4f89186bd5553e7768f

**Comment by roxannedebeaux** [comment]
I will test this when I next have a planning application to convert.

In other areas...
I have worked out a consistent issue that I am having with submit buttons.
When I use my laptop the widow is too big to access the button. Scrolling
does not work but the down arrow key does. I am sure I am not the only
person this is affecting.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: contact@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
