### ISSUE TITLE
Front page design has not been implemented fully yet

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#41]
Front page design is not fully-implemented yet.

**Comment by nikolai-b** [comment]
Should I add this to Milestone 3?
The only thing I can see that is different is the find group by name or postcode.  For the postcode I will want to convert that to a lat long which I might just use http://postcodes.io/ for that.  Do you want to some groups under the "find" section?  Also do you want a twitter feed?


![screenshot from 2016-06-17 13-21-17](https://cloud.githubusercontent.com/assets/6289830/16150351/9137fa64-348e-11e6-89ec-18d8795a267f.png)

**Comment by mvl22** [comment]
> Should I add this to Milestone 3?

yes, or 4.

> The only thing I can see that is different is the find group by name or postcode. For the postcode I will want to convert that to a lat long which I might just use http://postcodes.io/ for that.

No, please use the standard CycleStreets Geocoder for that. It has full support for postcodes and everything else and there is no need to create a new external dependency.

> Do you want to some groups under the "find" section?

As per design, yes, if this seems to make sense.


> Also do you want a twitter feed?

Yes, might as well bung in an iframe for that.

**Comment by nikolai-b** [comment]
> yes, or 4.

Should I move #89 into 4 then (as you suggested doing this first)?

> No, please use the standard CycleStreets Geocoder for that. 

Sorry, of cause I should use the CycleStreets Geocoder!

> As per design, yes, if this seems to make sense.

I can put in some groups but I'm not sure which as only the **top two** seems somewhat limited.  Should this be based of members?  Or most recent activity? ...

I'm a bit against an iFrame.  Can we not register a https://apps.twitter.com/ ?  The there is a simple gem to get the users timeline and I can just update that every 10mins or hour or something.

**Comment by jf1** [comment]
@nikolai-b "Find groups local to you" isn't underlined in your screenshot and currently it links to http://www.cyclescape.org/groups - I hope this link and page will be retained.

**Comment by mvl22** [comment]
> Should I move #89 into 4 then (as you suggested doing this first)?

OK.

> I can put in some groups but I'm not sure which as only the top two seems somewhat limited.

Actually perhaps the intention was search-as-you type. I don't have strong views, so whatever you think works best.

> I'm a bit against an iFrame. Can we not register a https://apps.twitter.com/ ? The there is a simple gem to get the users timeline and I can just update that every 10mins or hour or something.

Again, fine - whatever works best. By 'iframe' I just meant the official twitter widget rather than a roll-our-own, because that does all the twitter changes (like auto-resolution of t.co URLs, replies, etc.) automatically.

**Comment by mvl22** [comment]
Great, thanks! Looks good.
