### ISSUE TITLE
Cannot create a new thread on an exisiting issue because the window is sized incorrectly

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#410]
<img width="928" alt="screen shot 2015-08-27 at 17 16 34" src="https://cloud.githubusercontent.com/assets/11997264/9526134/824128c4-4cdf-11e5-9608-62721ed09009.png">

**Comment by roxannedebeaux** [comment]
Cannot get to the submit button as the window is the wrong size.

**Comment by mvl22** [comment]
Same issue as #445.
