### ISSUE TITLE
Button to edit thread settings is not working

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#411]
![screen shot 2015-10-05 at 11 34 53](https://cloud.githubusercontent.com/assets/11997264/10278436/41abe328-6b55-11e5-9df3-ad1e3786b693.png)

Nothing happens when I click this button.

**Comment by nikolai-b** [comment]
It does for me!

Can your provide more information?  Does it ever work?  What page are your trying it from?  What browser are you using?  If you have the console open (ctrl-shit-i) and you click it do you get an error message?

Thanks.

**Comment by roxannedebeaux** [comment]
Hi Nikolai,

I don't know what it is. I get this with a number of things on cyclescape.
I click and click and wait and wait and nothing happens. I use firefox on
the mac.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

SUPPORT THE ABBEY - CHESTERTON BRIDGE & SIGN OUR PETITION:
www.tinyurl.com/ACBridge

t: @camcycle     w: www.camcycle.org.uk/     e: contact@camcycle.org.uk
Join the Campaign at: www.camcycle.org.uk/membership/join/

**Comment by mvl22** [comment]
@roxannedebeaux Is this working OK for you now?

**Comment by nikolai-b** [comment]
Please re-open if this is still an issue.
