### ISSUE TITLE
about:blank bug on older browser

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#422]
Various reports from one user using an older computer of this happening sporadically:

"I keep on getting, when signing in, directed to a page where the url line just says "about:blank"

It also happened when I posted something on Cyclescape on a different computer over the weekend. Both computers are similar, although the one I'm using now is a tad older. Mac OS 10.4.11, Safari Version 4.1.3 (4533.19.4)"

I think this would be worth checking out to see if it is a known general Rails issue as I suspect it wouldn't be specific to our coding (possibly).

I think it would be worth trying to install the noted Safari version on a computer and using the site for a bit to try to get an reproducible case.

https://en.wikipedia.org/wiki/Safari_version_history
notes that 4.1.3 is the latest version available on OSX 10.4, so upgrading is presumably not an option for the user.

**Comment by mvl22** [comment]
Ways to run old versions of Safari:
http://stackoverflow.com/questions/2965222/how-can-i-test-my-website-in-an-old-version-of-safari-on-os-x

**Comment by nikolai-b** [comment]
Given this was an old Safari version over 2 years ago I'm closing this
