### ISSUE TITLE
Membership approvals aren't being saved

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#424]
As reported on thread 227:

I was able (as a committee member) to approve applications to the Cambridge group, this doesn't seem to be working any more preventing new members from interacting. This needs fixed as a matter of very high urgency. At the moment I can click "Confirm", and the page says at the top that I've confirmed, but the status on the right doesn't change from pending.

**Comment by nikolai-b** [comment]
Fixed in 410f739c1e8cb587830032c88cf55ea4ba717e02
