### ISSUE TITLE
Tabbing focus problem

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#429]
Reported by @si-the-pie:

"When I'm done typing my message at the bottom of a thread I naturally hit Tab to go to the Post Message button. But instead I'm taken to the top of the page. Using Safari."

I can't reproduce this in Chrome or Safari. Is it still a problem?

**Comment by smsm1** [comment]
This is standard behaviour on the Mac that buttons aren't tabable to unless you have the accessibility stuff enabled. The default on the Mac is to go via all of the text boxes and to ignore buttons and links etc. I can't remember the exact way to enable it in System Preferences.

**Comment by mvl22** [comment]
@smsm1 Does that apply to controls *within* a webpage? I know that is the case for system dialog boxes but surely tabbing on a webpage is consistent across platforms and system settings?

**Comment by smsm1** [comment]
Yup, this applies even with this Github issue comment form. Apple dropped support for Safari on Windows so now only support the Mac. This means that the experience is the same in the OS and on web pages. I've just compared it to Firefox (Mac), which does tab through the various buttons.

**Comment by mvl22** [comment]
The setting, @si-the-pie, is System Preferences > Keyboard > Shortcuts > All controls.
