### ISSUE TITLE
A new issue should auto-start a discussion

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#43]
There is currently a 'friction' in starting a discussion on a fresh issue that has come to mind.

If, for instance, cycle parking at a location is need, the process is

1. Click New issue
2. Add the issue description
3. Click New thread
4. Start the thread with its first message.

This does not compare well with an e-mail list:

1. Compose the e-mail and press send.

There is also the problem that we end up with issues that have no discussions attached to them.

A suggested solution is that creation of a new issue should also start a new thread with the description being the first e-mail.

The only problem here is that the issue description should be relatively dispassionate (as a short, to-the-point description), whereas a thread is a more subjective discussion. Perhaps the solution is to have a sixth box on the new issue page which forms the message box for a new thread. Labelling would be needed to make clear what the difference between boxes 5 and 6 are, but that would probably avoid the current problem of occasional long descriptions. Box 5 could be made smaller to emphasise the need for short descriptions.

**Comment by mvl22** [comment]
Continuing the discussion at: https://github.com/cyclestreets/cyclescape/commit/cd3f4a95fcdda98dd380141e2ce3f85cd972cdfe

Can you clarify exactly what the above commit does? Does it merely display the first message at the head of the thread (which as Andy says is not needed, since the issue extract is already shown), or does it actually clone the issue as the first message automatically?

The underlying issue we are trying to solve is described at:
https://github.com/cyclestreets/cyclescape/issues/43
namely that users create an issue and assume that the job is done, when they *also* have to create a thread. I think you (Nikolai) suggested that one way to do this is to add the 'Start thread for: ...' & 'With privacy: ...' as two extra fields that get populated dynamically when an issue has been created, or something to prompt this.

I'll copy this message to the issue page, so we can discuss it properly there:
https://github.com/cyclestreets/cyclescape/issues/43

**Comment by nikolai-b** [comment]
The one line @gravitystorm is concerned about sets the message body equal to the issue description for the first thread created on an issue.  If this is not needed I can remove and merge.

**Comment by mvl22** [comment]
> sets the message body equal to the issue description for the first thread created on an issue

I think this is fine and should go live. It makes a lot more sense this way for e-mail -based users, and for web users it will mean a thread with a proper starting point to which people can actually reply.

I accept it will probably need more iteration in future.

The main thing is that users are prompted to create a thread, which is non-obvious at the moment, given the number of threadless issues.

**Comment by nikolai-b** [comment]
so for better or worse this is [committed](https://github.com/cyclestreets/cyclescape/commit/cd3f4a95fcdda98dd380141e2ce3f85cd972cdfe) in master, closing
