### ISSUE TITLE
"You are not authorised to access that page" unhelpful for ungrouped members

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#430]
This is an issue being run into constantly now by the camcycle group and a small fix here will make a major usability improvement:

1. Campaign are e-mailed a bulletin containing a link to a discussion on a current matter.
2. A user who has not signed up to Cyclescape gets the message that they need to sign in or sign up
3. They then sign up successfully
4. However, because the thread concerned is a member-only thread, they cannot access it.
5. They get "You are not authorised to access that page." with no indication that what they need to do is to join the group.

I hadn't spotted the unhelpful message in (5) before.

There have been multiple support calls all on exactly the same problem.

So the fix is:

1. Make the "You are not authorised to access that page" a page with the proper GUI around it rather than just being plain text.
2. If the thread is owned by group X, provide a link to the group X application page with "
This discussion is owned by <group name>.
Would you like to apply to _join <group name>'s Cyclescape group_?
"

The wording in (2) is carefully done - it should not say "apply to join group <name>" as that will cause confusion between 'group' as in the actual organisation (which they are probably already a member of), and 'group' as in the Cyclescape group that the organisation has set up.

The link should be to the equivalent of this link for that group:
http://www.cyclescape.org/groups/1-placefordcc/membership_requests/new

That page could be made more friendly:

1. "Your membership request will be passed on to the committee members of the group to consider." should read "Please click the button below to apply to join this group's Cyclescape area."
2. The box should have default text: "Please add me to <group name>'s Cyclescape area."
3. The button should have the usual button styling.

**Comment by mvl22** [comment]
@nikolai-b Could you prioritise this in terms of new development.

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/abb90cba51ae4faaa468bd402a17c5893b97867f and https://github.com/cyclestreets/cyclescape/commit/7222a1dc8989fff88940761e44d782b39a4331f5
