### ISSUE TITLE
Group admins need link to membership administration area

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#431]
At present a group administrator has to click on the title of the group to get to the front page of their subdomain, i.e.:
http://camcycle.cyclescape.org/
which is a rarely-needed page, then click on the four links on the right.

It would be more helpful, when they are in their group's subdomain, to have a new link on their main menu, labelled, 'Membership'. The labels might need squashing up very slightly to accommodate this.

**Comment by mvl22** [comment]
The membership top-level menu item is only appearing at `/` rather than on every page within the subdomain.

I realise that my comment might have been ambiguous - sorry:

> when they are in their group's subdomain

By this I meant on any page in the subdomain, not the top-level page of the subdomain.

In general usability terms, the list of entries in a top-level menus should not change while moving around a site, or in our case, a subdomain of the site.

**Comment by nikolai-b** [comment]
This has been updated
