### ISSUE TITLE
Add support for changes for Czech system

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#433]
As noted at: https://github.com/cyclestreets/cyclescape/pull/426#issuecomment-151109768

the Czech instance at http://www.cyklistesobe.cz/ has:

"Changes in our branch include rebranding, supportlogos change, address changes, map layer changes and more. All these hardcoded things will need to be moved out of code to the configuration."

@PetrDlouhy, could you list on this issue what the changes are? I suspect we can add support for these fairly easily as settings.

**Comment by mvl22** [comment]
[ ] Top logo is image 'Cyklisté sobě'
[ ] The title tag has 'Cyklisté sobě'
[ ] Sponsor logos at the end are different (this would be useful for UK anyway)
[ ] Custom map layer coming from http://tiles.prahounakole.cz/ (which again would be useful to be configurable)

**Comment by PetrDlouhy** [comment]
Other changes are, as we can see on the [diff](https://github.com/cyclestreets/cyclescape/compare/master...auto-mat:deploy#files_bucket):
* The link line
  * Blog link
  * User guide link
  * Twitter link
  * Facebook link
* Whole footer
  * We need to comply Norwegian funds publicity directives, so the logo size, text and spacing needs to be changed.
   * This touches even the CSS
* The header
  * User guide link
  * About page link
* Some files or their parts in the `config` folder should be moved out of GIT repository
  * application.rb
     * Default locale
     * Timezone
     * Default url
     * Google analytics code
     * Github link
     * Mailer configuration
  * development.rb
     * default_url_options
  * initializers/devise.rb
     * mailer_sender
  * initializers/geo.rb
     * NOWHERE_IN_PARTICULAR 
  * initializers/geocoder.rb
     * Geocoder url
  * initializers/map_layers.rb
    * Map layers should be overridable
  * schedule.rb
    * MAILTO
* Some hardcoded things in locale
 * github_page_link_html

There are also some functionality, which I will make into PRs:
* Some untranslated things
* Last seen at for users

**Comment by smsm1** [comment]
Regarding the section @PetrDlouhy suggests moving out of the config folder. I would suggest using the same method as the database.yml where there is an example file, which has reasonable defaults for starting development, and then you can use an alternative for each install. There's a possibility Rails now has a neater way to implement these overrides now.

**Comment by PetrDlouhy** [comment]
And replace all instances of name `Cyclescape` from locale by site name that could be set in config.

**Comment by mvl22** [comment]
Yes, I agree that all those things seem like they should be configuration anyway.

For CycleStreets, we have a system whereby the site can run off many domains*, and for each there is a set of configuration. So, as a next step after parameterising the above into installation-based settings, I think it would be good for settings to be set via a form databindinded to a configuration table. This is what we do with CycleStreets*, and it enables multiple domains to be run with a single installation and single backend database. This would enable other countries' campaigns to join the system and have domain name, logo, etc., that matches their language and desires, without having to run a copy themselves.

* See the 'Examples' section at http://www.cyclestreets.net/services/whitelabelsites/

**Comment by PetrDlouhy** [comment]
For the last seen at feature, I made an pull request: #434 

I submitted some of the translations through Transifex. But I suspect, that the locale there is outdated since it doesn't contain strings for the newest features. Can you pleas download my updates and upload new locale files?

**Comment by nikolai-b** [comment]
I've done most of this.  I'm sure it is missing a few smaller pieces but I will close it now.  If there are small things missing can we open them up as new issues please.
