### ISSUE TITLE
UCE problem

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#435]
It appears spammers have discovered cyclescape and I've had lots of of spam emails overnight on two occasions. While I see you've deleted the offending thread, it's too late, the damage is done.

Akismet has an API. Can we use that to filter posts before they get posted and emailed?

**I think this is an urgent and critical issue**. Now they've discovered it, it is only a matter of time before we get a deluge, spam detectors will start blocking legitimate mail from cyclescape severely reducing its effectiveness, and people will start leaving because of it untrustworthiness.

**Comment by mvl22** [comment]
Yes, work is already in progress.

**Comment by nikolai-b** [comment]
Added a Akismet, a captcha and a moderation interface.  I think we can close this now

**Comment by mvl22** [comment]
Various hardening techniques now in place. Will continue to monitor.

**Comment by mvl22** [comment]
Re-opening as a second stage of development is needed. Suggest we discuss in person.

**Comment by nikolai-b** [comment]
I suggest we do any second stage as a new issue

**Comment by mvl22** [comment]
Yes, I'd like to talk with you in person about some things here.
