### ISSUE TITLE
Groups page layout issue

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#437]
Wierd and temperamental groups page display issue:

![groups page](https://cloud.githubusercontent.com/assets/361423/10865175/1e8f9708-7ffb-11e5-95d4-b16541ca5a12.png)

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape/commit/fe1c3defbfdf8477c847c0e5f055c2af4992e0fe
