### ISSUE TITLE
Have a longer list for "My subscribed threads"

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#439]
This list is too short for me to review all of my subscribed threads that have had recent activity. Can it be lengthened or can there be the option to view more?

**Comment by mvl22** [comment]
Yes, this is going to get changed as the current interface is just a temporary hack basically; probably will involve pagination so there is no limit.

**Comment by mvl22** [comment]
This was implemented in #695 which duplicated this issue.
