### ISSUE TITLE
Thread page needs to show the e-mail address of the thread

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#44]
Sometimes the user may have deleted earlier e-mails of a thread, so they don't know what to e-mail to.

Similarly, if the user has been sent an e-mail with attachment from a third-party, they might want to send the message to the thread simply by forwarding rather than having to detach the e-mail, upload, and copy and paste the text. If the e-mail address is stated, they can do that easily.

So we should just show the e-mail address on the page.

**Comment by mvl22** [comment]
There is actually more detail in the duplicate issue 101, which I'll restate here:

Each thread has an e-mail address associated with it.

This is not discoverable unless you have already received e-mails to it. E-mail orientated users might wish to e-mail the thread, e.g. to make forwarding an existing e-mail on this topic easier.

So, under the reply box (i.e. under the grey area which ends with 'Post message') there should be:

    <p>You can also reply to this thread using this e-mail address: %s</p>

with some obfuscation of the address ideally. This should only appear to users that are logged in, to avoid spambots picking up these addresses anyway.

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/pull/442
