### ISSUE TITLE
Library notes and Add thread to issue overlays have lost X in top-right

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#440]
I'm pretty sure that overlays like

Add library item on:
http://www.cyclescape.org/library

Discuss (add thread) on any issue page

used to have a top-right X, so this can be easily dismissed.

Ideally it would also be possible to dismiss the layer by clicking outside the foreground panel.

**Comment by nikolai-b** [comment]
The top-right X was hard to style (jquery-tools has its own header that clashes badly with our style) e7deffd dismisses the modal when clicked outside, can we close this without added the X?
