### ISSUE TITLE
E-mails coming through twice

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#444]
Report at:
/threads/227#message_27525

Not verified by me yet.

**Comment by nikolai-b** [comment]
I should have been fixed
https://github.com/cyclestreets/cyclescape/commit/faabb41050ad86471412d076eb99b7bf9b3141d3#diff-7edb13fa5490937a766fc893ffac14dcL27

I'm closing but re-open if we get any more through,
