### ISSUE TITLE
Enable closing of threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#446]
Branched from #302:

Suggested implementation, which applies to threads:

- Any subscribed user can close a thread
- A closed thread by re-opened (by any subscribed user)
- Closed threads result in the reply UI multibox being disabled/hidden
- The close option should only be available from 48 hours after the last posting to the thread
- An e-mail sent to the thread triggers a reopen event and then posts to the thread (this maintains the principle that the e-mail and web UI are analogous and consistent)
- A closure or opening event does not trigger an e-mail to people with switched on
- A closure or opening event results in a simple line like Github does on the thread discussion view
- If ever there is a case where a thread is listed, the string " (closed)" would appear after the title, unlinked

A second tranche:

- Determine the effect on search, on listings, and on My Cyclescape presence
- Determine what happens with issues, where all the contained threads are closed

**Comment by mvl22** [comment]
The close thread button is very easy to hit accidentally.

It is a function that is only going to be used occasionally, yet is directly next to a button which is used every time a message is sent.

I think it should be set as a right-aligned button/link after the whole reply box, i.e. outside and after that box. Ideally it would be the same button style but very heavily grayed out. Perhaps set an opacity value to keep the same colour scheme for consistency's sake but which will avoid the button being prominent.

It should also have an 'Are you sure' JS popup to help avoid accidental use.

**Comment by mvl22** [comment]
"Thread has been closed by $name at less than a minute"

isn't correct English - should probably be

"Thread has been closed by $name $timeperiod ago."

(with a closing dot too).

**Comment by mvl22** [comment]
When trying to close /threads/2248 I pressed the button and it took me to a page saying:

"You are not authorised to access that page."

**Comment by nikolai-b** [comment]
The close option should only be available from 48 hours after the last posting to the thread, it was a mistake it was even shown

**Comment by nikolai-b** [comment]
Fixed in 3ab6deca
