### ISSUE TITLE
E-mails should appear threaded by using an in-reply-to header

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#45]
E-mails do not appear threaded because there is no in-reply-to header.

In the case of replies via the website, this is always the last message, since there is no notion of quoting at present.

In the case of replies to e-mails, clearly these have a context so the reply-to address should be crafted so that the in-reply-to can be determined and stored in the database, then used by the queue to emit the e-mails.

**Comment by mvl22** [comment]
See also:
https://github.com/cyclestreets/cyclescape/pull/248

**Comment by wookey** [comment]
> Wookey and others, would you agree with this spec?

[Sorry - only saw this today]

Yes, that should work.

**Comment by nikolai-b** [comment]
> Fix up historical data to add parent IDs in the database as the message just above.

I don't really want to do this unless there is a use case for it now.  We can't alter the Message ID header of emails that have already been sent so I don't see the advantage of storing the message parent until we decided to implement #253
