### ISSUE TITLE
Thread subscription inconsistency

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#450]
On
/threads/1091
/threads/1572
(and probably some others perhaps)

I've noticed that the subscription state is inconsistent. I've noticed this occasionally.

At the top is the "Follow this thread" button.

But the "Following this thread" list has me listed in that user list.

**Comment by mvl22** [comment]
Is this in master?

I came across this thread:
http://camcycle.cyclescape.org/threads/1067

which I have posted to, but am not subscribed to. I don't recall having unsubscribed from it. Crucially, I am listed in the list of users following it, but the follow this thread button also appears.

Perhaps we need a database fixup, if there is a clearly-identifiable state that can be determined.

**Comment by nikolai-b** [comment]
Not yet I'm afraid.  I'll get the messaging changes done.  Are you ready to deploy tonight?

**Comment by mvl22** [comment]
Yes, can do so.

**Comment by nikolai-b** [comment]
Can we close this now?

**Comment by mvl22** [comment]
Yes; that seems to have resolved the inconsistency.
