### ISSUE TITLE
Planning applications missing

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#452]
This relevant planning application is not available on Cyclescape. 

https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=NUTWKGDXHFA00

**Comment by mvl22** [comment]
Another report:

I would like to add this planning application on Cyclescape but it's not coming up in the search. Do south cambs planning apps get loaded? Or is there a problem with
the search.

I searched by this reference: S/3223/15/FL
Site: http://plan.scambs.gov.uk/swiftlg/apas/run/WPHAPPDETAIL.DisplayUrl?theApnID=S/3223/15/FL&theTabNo=3

**Comment by roxannedebeaux** [comment]
Another planning application not coming up in the search: 16/0847/FUL

https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=O6RDLQDXLKT00

Also this one: 16/0757/FUL

https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=documents&keyVal=O670OQDX08H00

**Comment by nikolai-b** [comment]
There have been a few bugs that I've fixed recently around planning applications.  I am going to close this  as a dup of #620 but please re-open if you get new examples of this happening.

**Comment by nikolai-b** [comment]
There have been a few bugs that I've fixed recently around planning applications.  I am going to close this  as a dup of #620 but please re-open if you get new examples of this happening.
