### ISSUE TITLE
Time handling for deadline/date type, now iCal output

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#453]
Now that iCal output is enabled, it's exposed (or rather reminded me) of the need to improve the deadline/date message type, which currently only has a date.

The iCal feed basically results in all-day events, whereas most events do have a real time.

Currently there's been an awkward workaround of putting the time in the text description of the event:
/threads/469#message_27573
(which also shows the need for a note field).

**Comment by nikolai-b** [comment]
We have the time option, @mvl22 happy to close this now?

**Comment by mvl22** [comment]
I'm not seeing the times actually come through in the iCal feed though - they are appearing as all-day events I think.

```
BEGIN:VEVENT
DTSTAMP:20160111T192808Z
UID:a4ef5ae0-1cbc-4235-843b-da9ffdd46d74
DTSTART;VALUE=DATE:20160112
DESCRIPTION:Milton Road City Deal Consultation
SUMMARY:Milton/Histon Rd Consultation Tuesday 12 January 2016\, 16.00-20.00
  Mayfield Primary School\, Warwick Road\, Cambridge CB4 3HN 
URL:http://www.cyclescape.org/threads/802#message_28375
END:VEVENT
```

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape/commit/83fdf3c3fc80a56dff8b965398ff05143357f9c8
