### ISSUE TITLE
New thread creation giving warning

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#456]
https://twitter.com/jonpsp/status/670608541527449600
and I've run into this myself.

The "We're sorry, something went wrong" message comes up, but the thread does actually seem to be created (if you then go back and navigate somewhere to find it).

**Comment by nikolai-b** [comment]
At the moment Solar is updated on every change.

https://github.com/cyclestreets/cyclescape/blob/master/config/sunspot.yml#L7-L8

I think this is failing ever so often
https://rollbar.com/cyclestreets/cyclescape/items/36/

We should change it to a hourly job which would mean the search would be
out of date but not by much.

**Comment by mvl22** [comment]
> We should change it to a hourly job which would mean the search would be
> out of date but not by much.

Yes, please add that. Just had another report of this.

**Comment by mvl22** [comment]
Several more complaints about this today. At the very least can we disable the Solr reindexing as a very short-term fix.

**Comment by mvl22** [comment]
@nikolai-b Still getting reports of this, and I'm occasionally experiencing it myself. Can you clarify whether the relevant code is in master?

**Comment by mvl22** [comment]
Problem seems to have gone. I think you adjusted things further after the discussion below.
