### ISSUE TITLE
API: documentation

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#458]
Documentation for the API seems to have gone missing.

I think it should appear at /api/ as an HTML page, i.e. the index page at the same level as the individual calls, if possible.

**Comment by nikolai-b** [comment]
I've switched to swagger documentation. If you go to
http://petstore.swagger.io/?url=http://www.cyclescape.org/api/swagger_doc
the documentation is now part of the API.

**Comment by mvl22** [comment]
There needs to be a page at
`/api`
which contains a link to the documentation.

It's otherwise hard to find.
