### ISSUE TITLE
Ability to subscribe/unsubscribe to threads quickly from thread listing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#462]
To subscribe to a thread listed at
http://www.cyclescape.org/threads
and subdomains like http://camcycle.cyclescape.org/threads
you currently have to click on the thread, then click 'Follow this thread' and wait for the page to reload.

This is a barrier to quick subscription of multiple threads.

There needs to be a 'Subscribe' button (which toggles to 'Unsubscribe') in that listing, so the user can go down the list and subscribe to a thread from that listing page directly.

Obviously this should only work if the user is signed in. All the same security and visibility constraints as on the main thread page itself should apply.

If the user has Javascript enabled, the subscription/unsubscription should be toggled by an Ajax interceptor instead. This would have the same kind of effect as the 'Approve' buttons on the /admin/users page.

**Comment by panchew** [comment]
@mvl22 PR has been accepted and merged in; close this issue?

**Comment by mvl22** [comment]
This is still open as per my comment at:
https://github.com/cyclestreets/cyclescape/pull/476#issuecomment-171450049

See again the description at the top of this page.

**Comment by rbazinet** [comment]
@mvl22 there was a misunderstanding on our side. We are fixing this now and it will be as you requested. I didn't see any comments on the pull requests added so far.

**Comment by panchew** [comment]
@rbazinet @mvl22 The buttons are correctly placed now in the listings page; is it ok to send the pull request to master or should I used staging?

**Comment by rbazinet** [comment]
I think they want us to use staging for pull requests.

--
Rob Bazinet
Founder of Still River Software Company, LLC
(o) (860) 263-0396
(m) (860) 942-9291

Blog - Accidentaltechnologist.com
Ruby & Mobile Community Editor - http://www.infoq.com
LinkedIn Profile - http://www.linkedin.com/in/rbazinet

**Comment by panchew** [comment]
I've created it against cyclescape/staging then

**Comment by panchew** [comment]
PR has been merged. Close the issue?
@mvl22 @rbazinet

**Comment by nikolai-b** [comment]
Closed in #476
