### ISSUE TITLE
Add 'issues nearby' link under map, wherever map appears

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#464]
On the issues and thread pages, there needs to be a small "More issues nearby" link under the map on the issue/thread pages.

This should take people to /issues#map-pane with the geographical location auto-centered to be the same location, perhaps zoomed out one level.

See also #49.

**Comment by rbazinet** [comment]
@mvl22 this was merged. Any reason it's still open?

**Comment by mvl22** [comment]
See my comment at:
https://github.com/cyclestreets/cyclescape/pull/488#issuecomment-170691591

**Comment by rbazinet** [comment]
I see, sorry. I saw the PR had been merged and figured it was fine.

-- 
Rob Bazinet
Founder of  Still River Software Company, LLC
(o) (860) 263-0396
(m) (860) 942-9291

Blog - Accidentaltechnologist.com  
Ruby & Mobile Community Editor - http://www.infoq.com  
LinkedIn Profile - http://www.linkedin.com/in/rbazinet
