### ISSUE TITLE
Replace hard-coded planning application areas list with dynamic API read

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#465]
The list of areas is currently hard-coded at
https://github.com/cyclestreets/cyclescape/blob/master/lib/planning_application_worker.rb#L2-L22

which means that as new areas are added, we don't get the benefit of these without committing.

However, there is an API providing a list:
http://planit.org.uk/find/areas/json?pg_sz=2000
(I've set the page size to be big enough to cover everything for the future.)

It seems to be the `name` field.

**Comment by mvl22** [comment]
Pending implementation of this, could we do a manual update at some point?

The list at:
https://github.com/cyclestreets/cyclescape/blob/master/app/models/planning_filter.rb

is out of date. There are now 311 authorities.

**Comment by mvl22** [comment]
There is now 98% coverage, so this is becoming even more important now that there is essentially UK-wide coverage which we are missing out on.

**Comment by nikolai-b** [comment]
@mvl22 I don't think the planit API is that reliable.  I can't get that large request to work.  Given the very severe rate throttling of the planit API I suggest we just update the list manually.

**Comment by mvl22** [comment]
Yes, that API call seems to be unresponsive.

Could you update the manual list then? There is now 98% coverage so we should get more coming through.
