### ISSUE TITLE
Replace OpenLayers with Leaflet.js

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#469]
CycleStreets.net has completely replaced OpenLayers2 with Leaflet.js, with vastly improved productivity and maintainability, plus better mobile support and much lower download size. We should  do the same with Cyclescape.

See also issues #56 and #468.

This is the master issue for this work.

**Comment by nikolai-b** [comment]
Work started  (e.g. https://github.com/cyclestreets/cyclescape/commit/3e640d4797a613b381124ddf08b78e5764e07bcc) and deployed to staging

* Haven't ported the issue index combined map over (will need more work, do the popups need a rethink?)
* Before we were loading the map data via ajax, now we are dumping it into the page, might slow down index actions but worse if the map moves then it won't ask for new issues in that area yet
* No idea if the leaflet drawn js is internationalized
* The styling on the choosing base layers is rubbish
* I'm not storing the users fav base layer in a cookie (I think we did that)

Probably a few more points but feel free to add more here @mvl22 (and others..?)

**Comment by mvl22** [comment]
Had a look at this - I see you've made good start.

The location setting stuff definitely needs the proper semi-transparent panel on the left, which has the confers the key benefits of larger buttons and instructions.
