### ISSUE TITLE
Move CycleStreets API key into databag settings

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#471]
Currently this is hard-coded deep within the collisions module at ```config/initializers/geo.rb``` line 9.

But it should be moved into settings, so that users are required to obtain an API key.

This will be needed when support for #213 anyway, as the key will then be used for multiple API calls.

**Comment by nikolai-b** [comment]
Been done in https://github.com/cyclestreets/cyclescape/tree/leaflet
