### ISSUE TITLE
Upvoting undistinguishable from vote clear

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#473]
The votes element seems the same if I already voted as when I didn't. But the behaviour is different - if I click to the up icon again, the vote is cleared.
![snimek obrazovky_2016-01-06_11-44-24](https://cloud.githubusercontent.com/assets/156755/12140794/dd02a92a-b46a-11e5-826e-c295e7381e48.png)

This should be done in a way, that is clear to users at first sight.

**Comment by PetrDlouhy** [comment]
Other suggestion is, that we should not only show the sum of votes, but also number of up and down votes.

**Comment by gravitystorm** [comment]
See also #545 - trying to make the up/down votes more obvious.

**Comment by nikolai-b** [comment]
Moved to :+1: system
