### ISSUE TITLE
Verify email address format in registration

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#479]
When users copy their email address from email client (in format like `<petr.dlouhy@email.cz>,`), the registration succeeds. But of course no verification email arrive. We have several such users on Cyklisté sobě. The email address format should be checked to prevent such mistakes.

**Comment by PetrDlouhy** [comment]
Now I realized, that this is a bit false alarm.
The email confirmation arrives. But I didn't get the "Welcome" message, so maybe it doesn't work so good.
This also allows to have two accounts on one email address, which I don't think is intended. It might lead to confusion of users with two accounts.

**Comment by mvl22** [comment]
Agreed that we should be detecting cases of < ... >

**Comment by nikolai-b** [comment]
Not sure I agree
https://davidcel.is/posts/stop-validating-email-addresses-with-regex/
The check for me is: does the user get a confirmation email.
We can write some regex but it will also incorrectly flag some emails as invalid (when they *might* be valid).

**Comment by nikolai-b** [comment]
That said if you just want to check for the `<...>` case then that seems ok, see #483

**Comment by mvl22** [comment]
We shouldn't be writing our own e-mail validation regexp.

Instead, we just need to detect the specific case of < ... > with optional surrounding whitespace, and leave whatever existing validation is already present.

**Comment by gravitystorm** [comment]
Closing, fixed by #483
