### ISSUE TITLE
Private messaging

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#48]
A private messaging system is needed so that a user can message another user to suggest that they subscribe to a thread.

**Comment by nikolai-b** [comment]
Fully agree.  Looks like there is an off-the-shelf solution in the form of https://github.com/mailboxer/mailboxer.

**Comment by nikolai-b** [comment]
Would this always send an email or only if the user has email in preferences?  I'm not keen on having a full blown pm system but being able to email other users makes sense, to prevent issues it could be that you can only email people in the same group, then this is very easy to implement i.e. a pm option on the users profile to a form that sends an email to the user.  We could also add a prefs option to not receive pms.  Then we can store the messages but don't really display them or have a messaging area as such.
Thoughts @mvl22 ?

**Comment by mvl22** [comment]
> Would this always send an email or only if the user has email in preferences?

I think the messaging system preferences should be totally independent of the main e-mail -related preferences.

> it could be that you can only email people in the same group

That would be a reasonable restriction, and will help keep potential spam exposure low.

> i.e. a pm option on the users profile to a form that sends an email to the user

Yes, that's right.

It should never expose the actual e-mail address of the user but do the sending internally.

> We could also add a prefs option to not receive pms.

Yes, agree. I think PMs can be on by default.

> Then we can store the messages but don't really display them or have a messaging area as such.

It would be preferable if users can see them within the system, rather than just get e-mails.

It's important that they are stored in the database, rather than just sent without any persistent storage, as otherwise we have no way to investigate spam or other abuse.

**Comment by mvl22** [comment]
Problems:

1) "Private Message between Nikolai B and ." at the top.

2) Hadn't realised these will be integrated within the standard thread listing. Yes, I suppose it works. However, there does need to be some indication in that listing that it is a direct message between two users only.

3) I thought we were going to call this something other than "Private" as that term is already used for private threads, i.e. Direct message. Currently other threads have text like "Private: Only members of Cambridge Cycling Campaign can view and post messages to this thread." which means "Private message" is definitely cause for confusion. Perhaps the DM page could say "Private: Direct message been name1 and name2".

**Comment by nikolai-b** [comment]
> Seems to work solidly; good work.

Great!

> Issues:
> 1) "Private Message between Nikolai B and ." at the top.

Fixed in 1fb9c91f

> 2) Hadn't realised these will be integrated within the standard thread listing. Yes, I suppose it works. However, there does need to be some indication in that listing that it is a direct message between two users only.

Is the notification on the top "Private Message between Nikolai B and Martin" not enough?  What were you suggesting.

> 3) I thought we were going to call this something other than "Private" as that term is already used for private threads, i.e. Direct message. Currently other threads have text like "Private: Only members of Cambridge Cycling Campaign can view and post messages to this thread." which means "Private message" is definitely cause for confusion. Perhaps the DM page could say "Private: Direct message been name1 and name2".

On the phone I thought you said PM or Private Message was ok.  We can change the text.
https://github.com/cyclestreets/cyclescape/blob/staging/config/locales/en-GB.yml#L762-L765

> 4) Does the envelope light up in any circumstances? I think accessing the thread should be the thing that marks it as 'read', and that if the user has any messages that are not read, then that causes the envelope to light up.

I agree but it is extra work.  I though we wanted to do the minimum with PMs as you didn't think they would be used much.  We have the concept of a thread view so we could check if private messages associated with the user something like
```ruby
current_user.subscribed_threads.where(privacy: 'private').includes(:latest_message, :thread_views).where('messages.updated_at > COALESCE(thread_views.viewed_at, to_timestamp(0))').references(:messages, :thread_views).exists?
```
 but as we have the message in the top panel that would happen on every page load.  This would be less of a problem if they were in the My Cyclescape section.

Points 5 - 10 have been fixed in 1fb9c91f (and updated in 34960c3) thanks for the review.

**Comment by mvl22** [comment]
> Is the notification on the top "Private Message between Nikolai B and Martin" not enough? What were you suggesting.

I meant in the listing on the My Cyclescape page. (Sorry "in the listing" wasn't very clear!)

I think on balance, let's put the whole feature live now, and not worry for now on the points above as I think they're probably fine. We can iterate further based on any feedback.

I do think we will need a way for users to be able to block messages from another user in the event of abuse.

**Comment by nikolai-b** [comment]
Agreed!

At the moment you can only send PMs if you can view the other users profile but this could be limited easily to only work if you can view the users full name (or if your a member of the same group or on a group committee where the users has a membership request).  That would severely limit the likelihood of abuse.  

Should we start of strict so only committee members where a request has been made and people in the same group can PM users?

**Comment by mvl22** [comment]
Yes please.
