### ISSUE TITLE
Don't allow users do delete their accounts

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#480]
I think, that the function, when user can delete it's own account is potentially harmful. I don't know what impact it has on the contributions that the user had, but it is dangerous anyway. Why not only deactivate the account? And why administrators doesn't have the ability to delete accounts?

**Comment by mvl22** [comment]
I think this does indeed do fake delete. Perhaps @nikolai-b can confirm.

**Comment by nikolai-b** [comment]
Yes, https://github.com/cyclestreets/cyclescape/blob/61d23f/app/models/user.rb#L39 uses the gem https://github.com/rubysherpas/paranoia

**Comment by mvl22** [comment]
It would be useful to document that we are using fake delete, in the code near line 39, as it's easy to spot.
