### ISSUE TITLE
Don't insert the description of issue as first message in new thread.

### ISSUE THREAD

**Issue by PetrDlouhy** [cyclestreets/cyclescape#486]
Don't insert the description of issue as first message in new thread. I leads to duplicated messages in thread output, like on http://www.cyclescape.org/threads/2273 which is only confusing to users. The user must investigate if the text is different or the same, which is unpleasant.

**Comment by mvl22** [comment]
Yes, I agree this confusing.

However, it's also for confusing that if someone follows a link to the thread, that they don't see the description of the issue, which in some cases may be the start of the conversation if the original submitter hasn't created a duplicate as the first posting (as they are now prompted to do, but they can still change it).

This is a policy issue, and relates to the general issue of auto-creation of threads when an issue is created.

Please don't merge the code in yet.

**Comment by PetrDlouhy** [comment]
@mvl22 The issue description is part of thread output: http://www.cyclescape.org/threads/2239

**Comment by trevorparsons** [comment]
A related confusion arises from the fact that the text proposed by Cyclescape for the title of the auto-created first thread is (apparently) the same as that of its parent issue. People creating issues generally don't change this title text, making it harder for visitors to tell the difference between a default thread and its parent issue. This is in the context of an interface which doesn't yet do a very good job of explaining the distinctions and relationships between issues and threads. Might a breadcrumb trail or similar visual metaphor help?

**Comment by nikolai-b** [comment]
With #660 we will stop doing this.

**Comment by mvl22** [comment]
> With #660 we will stop doing this.

But bear in mind that the second, third, etc. threads will have a different starting text. So this suppression of the first should only be done for the starting thread.

**Comment by nikolai-b** [comment]
Yes, sorry.  With the first thread (on issue creation) we will not use the description as the first message but in subsequent threads we still copy the description (for better or worse).

**Comment by nikolai-b** [comment]
With #660 we should close this.
