### ISSUE TITLE
Issues nearby map as another clickable layer next to maps

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#49]
At present, there is no way to view other issues nearby the current one without going to the main issue view and manually browsing to the same location.

In the same way as the collision data view (#32) and planning application view (#33) both need buttons next to the map (see #34 for the principle of this), 'Issues nearby' could be another such button, enabling this layer.

**Comment by nikolai-b** [comment]
Finished in 963ee3b
