### ISSUE TITLE
Add Github CI provider links

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#490]
Github regularly tells us:

```
Avoid bugs by automatically running your tests.
 
Continuous integration can help catch bugs by running your tests automatically.
Merge your code with confidence using one of our continuous integration providers.

https://github.com/integrations/feature/code
```

Is this something we should consider?

**Comment by nikolai-b** [comment]
Yes!!!

It has been on my mind over the past week.  I was going to email to check I can prioritise but well get on this later. I just had a go with [Circle ](https://circleci.com) but it looks like it might require a bit of configuration.

**Comment by nikolai-b** [comment]
Actually, it was just complaining about `Rakismet.key`, it probably makes more sense if you set it up as I'm not a repo admin

**Comment by mvl22** [comment]
How's that different to Travis, which seems to be what everyone else is using?

**Comment by nikolai-b** [comment]
We have CircleCI now!
