### ISSUE TITLE
Cyclescape API - 'last post' date needed

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#495]
The new Cyclescape API is very useful and meets the needs of my Issue Map web application (http://maps.camdencyclists.org.uk/issuemap/index.html) very well.

I have just one problem: the addition of a Deadline is helpful as an indication that an Issue can be dropped from the map where it is about something like a local authority consultation.
But there are other discussion-style issues for which no deadline can be defined. These should be removed from the map when none of the associated threads has a recent post. 
To support that, it would be very helpful to have a 'most recent post' field in the returned geojson object.

My workaround is to define issues as 'stale' if they were first opened more than 12 months ago. But that is incorrect because it defines issues as stale even when they have threads that iclude ongoing discussions.

Hoping this can be done without too much trouble.

**Comment by mvl22** [comment]
We recently added the ability to close an thread explicitly.

Would it be preferable for the API to transmit that status, as it will mean that issues that are still a problem but have no recent updates still come through? If they really are not relevant any more, that would prompt someone to go and close the issue, keeping the data clean.

**Comment by nikolai-b** [comment]
It seems sensible (and very easy) to send both of these.

We already use latest activity at
https://github.com/cyclestreets/cyclescape/blob/staging/app/models/issue.rb#L78
and adding a closed boolean is easy.

**Comment by georgio8** [comment]
I think we need both. It's unlikely that all the stale issues will be closed by their owners. The latest activity date could be used to give users a range of options for 'staleness'.

**Comment by nikolai-b** [comment]
I've added it to master but not deployed yet, will do soon.

**Comment by mvl22** [comment]
Are you defining that an issue is closed if all its constituent threads (if any) are closed?

**Comment by mvl22** [comment]
... or rather that no threads exist that are open?

**Comment by nikolai-b** [comment]
If no open threads exist. This is only used by the API but I take your point that an issue with no threads is hardly closed but it is also unlikely to be of interest to @georgio8 (or am I missing something)

**Comment by mvl22** [comment]
I think a logged issue with no discussions yet can be regarded as open.
