### ISSUE TITLE
Member mass-import for groups

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#50]
LCC and CTC both need the ability for mass-import of member details, ideally using the supergroup notion in the original spec.

The proposed system for this is:
1. Group admin can go to a panel and paste in all members' e-mails, and press submit
2. Cyclescape creates a hash of each e-mail, stores it in a table of these hashes (id,hash,groupId) but does not store the e-mail, to avoid data protection and security issues
3. When a person registers, a hash of their e-mail is created
4. If the hash matches any hash(es) in the hash table, they are subscribed automatically to that group(s), or asked to confirm that they want to join (probably best)
5. A message is shown confirming they have been access to the group(s)
6. The group admin can re-paste the e-mail list in at any time, which removes all the hashes with that groupId and creates a new set.
7. Where a member has become removed from the list, they are deemed no longer a member and so in some way need to be de-attached from the group's privileges.

The idea of the supergroup concept is that every group (Bromley, Kingston, etc.) shouldn't have to get a list of members from the LCC head office. The LCC head office should just be able to maintain this once, and the child group code effective gains that privilege.

None of this should stop groups adding people themselves directly.

Groups would presumably need a setting that says "Automatically accept people who are members of the %parentgroup".

Clearly there are some things here that need discussion, but the aim is very much to enable large numbers of people who are members of say LCC and CTC to get going quickly and working with their groups with very little friction to get started.

**Comment by mvl22** [comment]
I suggest we use SHA512 rather than MD5.

**Comment by nikolai-b** [comment]
I have merged this into staging.  The text will need working on (i.e. the intro text for committee members) so please let me know about that or other issues.

**Comment by mvl22** [comment]
In terms of reaching the new UI:

Could you add a tab for this, like the other items on the 'Membership' main menu item.

Took me a while to find it, at `/groups/<id>-<moniker>/membership_requests`

Also needs a cross link from `/groups/<id>-<moniker>/members`.

On the subdomain page, where it is listed on the right, it is currently 6th in the list, orphaned from the other membership items. I would say it should be 3rd, after 'Edit the membership list'.

**Comment by mvl22** [comment]
In terms of its action:

Currently the behaviour is:

"If you update this list it will not remove any existing members but it will replace an emails you entered last time."

NB There a typo "any" rather than "an".

The above doesn't yet agree with this part of my spec:

> 7. Where a member has become removed from the list, they are deemed no longer a member and so in some way need to be de-attached from the group's privileges.

However, I can see that adds quite a bit of complexity: if for instance a member were accidentally missed off, they could then get unsubscribed inadvertently from lots of discussion threads, which would be very annoying.

I suggest we deal with this later, and make live the current work first, as this will need some policy discussion with groups.

Does the activation of the membership trigger an e-mail in the same way as if they had been manually approved?

**Comment by nikolai-b** [comment]
> Does the activation of the membership trigger an e-mail in the same way as if they had been manually approved?

I'd missed that, done in 0d04440d thanks.  It automatically subscribes them and now it sends an email.

Regarding the typo I'm somewhat confused, the text is here:
https://github.com/cyclestreets/cyclescape/blob/957023ba7b1d4abd4d54bd61636507b68ef5c659/config/locales/en-GB.yml#L324-L326

Do you want it to read 
> "If you update this list it will not remove an existing members"

because that seems wrong to me.

**Comment by mvl22** [comment]
Change these:

Add the email of all your membership.
=>
Add the email addresses of all your membership.

existing members but
=>
existing members, but

replace an emails
=>
replace any emails

The last one was the typo (an -> any) I was referring to.
