### ISSUE TITLE
Chrome 'Choose File' button is broken

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#500]
In Chrome, you can drop a file from Windows (File) Explorer onto the Choose File button into order to choose it for uploading. This works on every site I have visited that uses the standard file upload button (and those that don't tend not to in order to provide a drop target for files anyway), except Cyclescape. So I have to go through the laborious process of bnavigating to the folder where my file is, even though I already have a WFE window open on that folder. Why have you disabled this very useful functionality in Chrome in the Cyclescape thread attachment/photo panel?

**Comment by mvl22** [comment]
Works for me. What version of Chrome are you using? Can you confirm that a clean restart of the browser still has the problem?

> Why have you disabled this very useful functionality in Chrome in the Cyclescape thread attachment/photo panel?

What makes you think this has been done deliberately?

**Comment by davidearl** [comment]
> What makes you think this has been done deliberately?

Because it is isn't something that normally has any involvement from the web page, and it would require some effort to disable it - it normally just works. But it may be one of the libraries you're using that is disabling it as a side effect.

So, I've done some investigation and I think it may be related to a HTML5 feature I didn't know existed - "Shadow DOM". 

So, firstly, if I restart the browser (Chrome 47, up to date) it continues to fail while all other pages with this input element work. However if I start up a secondary instance of the browser ("Switch person"), that does work. That suggested to me it might be an extension that's causing it, but (a) disabling all extensions doesn't fix the problem, and (b) adding all the same extensions in the secondary instance doesn't provoke it.

If I start examining the DOM, by right clicking on the button and "Inspect", it __doesn't__ go to the button in the inspector, it lands on the body element. There's something overlaying the button, which is what is catching the drop event (and the effect is to open the image in the browser window rather than applying it to the input. I think this is #shadow-root > input which you can see if you navigate to the button in the debugger. That's the same in both browsers, and also the same for other similar buttons on other web pages which do work, so that still isn't the entire difference, but it is a surprise to see the button being overlaid with something else, and I suspect this has something to do with it.

The only other difference I can see is that I'm signed in to Google in the primary browser, but not in the secondary. Unfortunately Chrome won't let me sign in to both simultaneously, and I don't want to dissociate the main browser as I will lose lots of settings if I do. But maybe this is the smoking gun. I can't think of anything else that would be different.

**Comment by davidearl** [comment]
I should add: I don't have "Show user agent shadow DOM" in the debugger turned on in either browser instance. That appears to be the only settable option related to shadow dom.

**Comment by davidearl** [comment]
Perhaps this shadow input is what implements the drop target function of this button in chrome?

**Comment by nikolai-b** [comment]
To confirm I do not get this problem on Chrome(ium) ver 47.
If you navigate to:
http://www.cyclescape.org//threads/123456#new-document-message
do you get the same issue?  I'm not really sure there is much we can do about this, especially if a second instance of Chrome works.

**Comment by davidearl** [comment]
I get a 404 if I follow that link.

**Comment by nikolai-b** [comment]
Sorry, 123456 was an example thread number, I wasn't sure which thread you were referring to so please replace it with one of interest

**Comment by davidearl** [comment]
(Sorry, I missed the point, I thought you were seeing if it was thread specific).

No, it makes no difference if you have that fragment on the end of the URL.

**Comment by nikolai-b** [comment]
I'm not able to reproduce this so not much I can do, sorry

**Comment by mvl22** [comment]
Any chance of a short video showing this, David? It obviously is a problem for you but I can't reproduce it either and we've had no other reports.

Is there perhaps a Chrome plugin causing the problem?

**Comment by davidearl** [comment]
Here you are: http://recordit.co/H9l3lMX0a4 . I'm not sure what it adds to my description, which is that dropping a file on the Choose File button behaves just like dropping a file on any non-hot-spot rather than as a drop target.

It's not an extension, which was also my second thought - see my extensive research from Jan 28 where I eliminated this possibility.

It is something specific to this browser instance though. But not something that affects other Choose File buttons in other sites.

**Comment by mvl22** [comment]
@davidearl Can I ask if this is still happening?

The video was good - and clearly that problem was happening. The difficulty is that none of us have been able to reproduce it and this is the only report received.

If it is still happening, obviously we do need to fix this.

**Comment by melbahja** [comment]
I had same problem, turns out I put onclick event in form element
