### ISSUE TITLE
Group membership request of duplicated user cannot be approved

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#502]
At ```/groups/2-camcycle/membership_requests``` there is a user which cannot be approved, in that clicking the Confirm link results in a "The change you wanted was rejected" page.

I notice that ```/admin/users``` has two user accounts, created consecutively (maybe a submit button bounce situation) with the same username and same e-mail, which presumably should not be happening.

So possibly two bugs here.

The group needs to approve the user so this needs to be dealt with soon.

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape/commit/41f9a069d3664e2b0f31fdefb7ea9f817417804b
