### ISSUE TITLE
Expected search result not coming up

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#504]
A search for ```cyclehack``` on the camcycle subdomain:
/overview/search?utf8=%E2%9C%93&query=cyclehack&button=

does not find thread /threads/2315 .

**Comment by roxannedebeaux** [comment]
I concur with this. I've tried many combinations of this search term and nothing works. 
There are at least 2 threads that should appears.

**Comment by mvl22** [comment]
If you could note the other thread numbers that would help us get a better reproduce-case for a fix.

**Comment by nikolai-b** [comment]
The search indexing looks to be stuck.  I've fixed this but I'm not happy with the searching in general.  I'll close but I need to get a better solution than the current solr / sunspot configuration.
