### ISSUE TITLE
Allow editing of some Issue fields by the issue creator

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#506]
An LCC user has asked:
> Is there a way that in Cyclescape I can edit consultation deadlines that have changed, either in a discussion thread or in an issue? This seems quite a common scenario, yet I can't figure out how to deal with it.
> Kind regards,
> Dominic

He is quite right, this need has occurred several times and I have had to intervene as a sysadmin to change the deadline date. Note that the Issue Map uses the Issue deadline to determine the appearance of an issue.

Editing the Deadline is a minimum requirement. I think the Description, External link and photo should also be editable by the issue creator as new facts may well emerge during the Issue's currency.

**Comment by mvl22** [comment]
Yes, I agree that an original reporter should be able to change the fields of an issue they created. I thought this was already the case but it seems only admins can, as you have found.

**Comment by nikolai-b** [comment]
Currently you can only edit an issue 24 hours after it was created
https://github.com/cyclestreets/cyclescape/blob/staging/config/authorization_rules.rb#L67

I've no idea why and its easy to change but thought I should let you know in case there was a reason.

**Comment by mvl22** [comment]
Yes, let's release that time restriction. I think we can trust that an original submitter won't turn it into spam or do unwarranted things.
