### ISSUE TITLE
convert to issue from Planning Applications is not working. 

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#508]
Clicking "Convert to Issue" results in error screen:

We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

(Attempting to do this for planning application "16/0165/FUL"

**Comment by mvl22** [comment]
I can reproduce. Not sure why this should suddenly have broken.

**Comment by roxannedebeaux** [comment]
Hmmm I just tested it and it works for other planning applications but not
this one.

I think there must be something wrong with this planning application that
makes it not work in Cyclescape (hence a number of issues with it).

My theory is that it is because it is not of a real address/location. Only
"South of Dame Mary..."

It looks like the map on the Council Site is also not working with it.

However no location on planning applications must be fairly common so it's
something that will need a work around.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by nikolai-b** [comment]
You are correct. I can see the error. What should we do with planning apps
without a proper location? Take you to a partially filled issue creation
page?

**Comment by roxannedebeaux** [comment]
Yes I think that is fine. As long as the rest of the information is there
it shouldn't be too hard to then add the location.

I like this feature as it saves me time filling out the information, it
ensures consistency and prevents errors. I want to maintain those aspects.
(I don't find the voting system useful). I have also been thinking about
ways to further filter the planning applications that are listed. I'll
start an issue about that when I've had more time.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by mvl22** [comment]
> Take you to a partially filled issue creation page?

Yes.
