### ISSUE TITLE
Put link to "create new issue" on the threads page

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#509]
It would work much better with my work-flow to have the link from here:

http://camcycle.cyclescape.org/threads

(In the same way that there is a link for admin threads on the admin tab).

**Comment by nikolai-b** [comment]
@mvl22 this is easily done but it feels somewhat wrong to have a new issue when looking at thread...?

**Comment by mvl22** [comment]
Agree; please don't change. This needs a more general look at the UI confusion between issues and threads, and the above change would confuse things further.
