### ISSUE TITLE
Map not working on planning applications

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#510]
On this page the map/location is not showing:

http://camcycle.cyclescape.org/planning_applications/uid/16/0165/FUL

**Comment by mvl22** [comment]
I can reproduce this. Very odd. The browser console is not giving any warnings either. None of the layers seem to work.

I wonder if the upstream PlanIt data is lacking geo data for this particular one.

**Comment by nikolai-b** [comment]
When there is lat / lng data than we pull it in, in this case there is none.  Not really much I can do about it other than say: 'no location given', would you like me to add that?

http://www.planit.org.uk/api/applics/json?id_match=16/0165/FUL
