### ISSUE TITLE
Planning application not coming up in search

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#519]
16/0215/FUL not appearing in planning application search by reference function.

**Comment by nikolai-b** [comment]
Not sure why that was missed. Added manually now

**Comment by nikolai-b** [comment]
Ok, so planning application UIDs might not be unique over all LAs.  Oh well.

**Comment by roxannedebeaux** [comment]
two more not showing up 
https://idox.cambridge.gov.uk/online-applications//applicationDetails.do?activeTab=summary&keyVal=O4Y97CDXL0700
https://idox.cambridge.gov.uk/online-applications//applicationDetails.do?activeTab=summary&keyVal=O4UV1IDXKZ600

**Comment by roxannedebeaux** [comment]
No new planning applications are appearing. The last appears to have uploaded in March.

**Comment by mvl22** [comment]
Confirmed that the data upstream is fine:

http://www.planit.org.uk/api/applics/json?limit=30&auth=Cambridge&end_date=2016-05-05&start_date=2015-10-23
