### ISSUE TITLE
Consistent URL for the settings page needed

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#52]
At present, if I need to suggest to a user that a setting is wrong, I have to e-mail them as follows:

"Please click on your user name (top right), click Edit my preferences button" (and then something like "tick 'Also involve me in my groups administrative discussions' and press Save."

Instead this first bit should read

"Please go to http://www.cyclescape.org/settings to fix this."

which will work for the user signed in.

**Comment by mvl22** [comment]
@nikolai-b Could you set this one as the first of the current priorities, as this would be very useful to have when then privacy improvements e-mail goes out.

**Comment by nikolai-b** [comment]
Yep, as it's only a small change I've added straight to staging https://github.com/cyclestreets/cyclescape/commit/68923cefc6af37f6c74589bcc7d003f90b49fff3

**Comment by mvl22** [comment]
Thanks. /profile does work fine now. But it isn't actually being used for the link in the buttons.

A key general principle is that each page should always have one, and only one, single canonical URL.

The other pages don't have similar URLs though.

I wonder whether we should have the four buttons going to:

/settings/profile
/settings/account
/settings/locations
/settings/preferences

**Comment by nikolai-b** [comment]
I thought you were asking for a quick link you could add to emails.

> A key general principle is that each page should always have one, and only one, single canonical URL.

This isn't possible.  You want the ability for users to view their own profile at one URL `/settings` but if they are logged out then their own profile will be at another URL `/users/123-me/profile`.  I have made those buttons work in #370 but there will always be more than one url with the users profile.  Is that ok or do you want to re-think this?

**Comment by smsm1** [comment]
Having a consistent url for the settings pages, which mean that I can send someone a link and say go to this page and change setting x, will work for any user is in my opinion very important.

**Comment by mvl22** [comment]
There are really two different things here.

The public profile, which is at ```/users/123-me/profile``` as you say. This is effectively a read-only set of pages, and the URL for this is fine at present. It is, quite correctly, different for each user and persistent, whoever is looking at it, whether the user themselves or other users.

Then there are the settings page, which are read/write pages, that let the current user make changes. One of these settings pages happens to be the details that then appear in the profile pages. These are not really the 'profile' as such. So I'm suggesting these should be under a URL hierarchy of ```/settings``` (not profile, since that is specifically a profile, whereas settings contains things not relevant to the actual profile). This set of pages under the URL hierarchy should be the same for every user. (However, do bear in mind that it is still useful for an admin to be able to see a specific user's settings, e.g. to investigate what might be going wrong in response to a feedback they submitted.)

Consider Facebook, which operates in a similar way: There is the public 'profile' at facebook.com/myusername and there are the 'settings' pages (at facebook.com/settings).

I think it's important not to mix these two concepts - the public profile and the user's settings.

**Comment by nikolai-b** [comment]
Fixed in #370

**Comment by mvl22** [comment]
The second settings page is still at {{{/users/edit}}} so I don't think this is quite ready to close.
