### ISSUE TITLE
Group discussion threads: Multi-group or national matters

### ISSUE THREAD

**Issue by jf1** [cyclestreets/cyclescape#522]
Is the intention for people to use a single group's public thread for something that's of interest to multiple groups?

If so, could we start a Cyclenation group so such a public thread could go there, and people can opt-in to all those new threads?

**Comment by mvl22** [comment]
We don't yet have a way of dealing with things that are genuinely national and of high importance.

The system currently has a maximum size, in order to avoid abuse that could result on that.

**Comment by jf1** [comment]
By 'maximum size' do you mean location area?
Perhaps I should have been clearer - this issue is not about location-specific threads, it's about general discussion threads.

If a national group were set up to facilitate this function, using existing Cyclescape features, then I would hope that the requirement for people to opt-in to the group and its threads avoids that type of abuse - any problem usage should be for the group admin to deal with so hopefully no burden on Cyclescape admins.

**Comment by jf1** [comment]
(One) national group created: http://cyclenation.cyclescape.org/ thanks.

**Comment by mvl22** [comment]
I'm going to revert the approval of this. This needs further discussion.

cc. @smsm1.
