### ISSUE TITLE
New problem with the 'Access-Control-Allow-Origin' header when using the API

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#525]
My setup for the Issue Map involves using a subdomain 'maps.camdencyclists.org.uk' which is aliased for camdencyclists.coulouris.net. Up until now I have been using the first URL quite happily for running test and production versions, but suddenly this afternoon I encountered this hard error:  
XMLHttpRequest cannot load http://www.cyclescape.org/api/issues/?order=size&bbox=-0.5534,51.2702,0.2565,51.6936&tags=[%22consultation%22,%22cycle-superhighway%22]. The 'Access-Control-Allow-Origin' header has a value 'http://camdencyclists.coulouris.net' that is not equal to the supplied origin. Origin 'http://maps.camdencyclists.org.uk' is therefore not allowed access.
mapbox.js:63 could not load features at http://www.cyclescape.org/api/issues/?order=size&bbox=-0.5534,51.2702,0.2565,51.6936&tags=["consultation","cycle-superhighway"]module.exports.log @ mapbox.js:63

All version of the map have stopped working including the one embedded at http://lcc.org.uk/pages/consultation-map !
This is rather embarrassing because I was going to show the Issue Map to some people in Hackney this evening and I can't run it!

**Comment by mvl22** [comment]
At 7.28pm I added 

Access-Control-Allow-Origin: *

to the Apache config as a hotfix.

I'm not sure why this should suddenly have changed.

Over lunchtime I did a security upgrade of the OpenSSL libraries but I don't see why that should have broken anything.

**Comment by georgio8** [comment]
Many thanks for the quick action Martin and Nikolai. The demo went ok as Nikolai knows. 
I'm afraid I'm still seeing the fault, but it's only when I use the Chrome browser, fine with Safari and FF! Will investigate further.

**Comment by mvl22** [comment]
Don't forget that the code change will need to be rolled out on the server.

Nikolai, feel free to do so if you get the chance.

**Comment by nikolai-b** [comment]
You have sent a request with the `Origin` header `http://camdencyclists.coulouris.net`
But the domain that the map is hosted on is `http://maps.camdencyclists.org.uk` have you moved something?
I'm now setting the Access-Control-Allow-Origin header from rails to be * (instead of the Origin of the request), I'm not sure if the Apache changes @mvl22 made had any effect but I'm having issues deploying to staging at the moment.  Sorry.

**Comment by nikolai-b** [comment]
To be clear I'm having issues deploying to staging (not live yet, haven't tried)

**Comment by georgio8** [comment]
It seems to be ok on all my browsers now. I think the problem must have arisen because Google rolled out a Chrome update that has a stricter definition origin control. The other browsers are said to have little control.

**Comment by georgio8** [comment]
The problem is back and it's appearing with all my browsers (Chrome. Safari, FF), so the application is definitely broken. Here's what Chrome says:
XMLHttpRequest cannot load http://www.cyclescape.org/api/issues/?order=size&bbox=-0.5534,51.2702,0.2565,51.6936&tags=[%22consultation%22,%22cycle-superhighway%22]. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://maps.camdencyclists.org.uk' is therefore not allowed access.
util.js:19 could not load features at http://www.cyclescape.org/api/issues/?order=size&bbox=-0.5534,51.2702,0.2565,51.6936&tags=["consultation","cycle-superhighway"]module.exports.log @ util.js:19

**Comment by jf1** [comment]
Just to confirm it's also failing on my chromium based browser that's not
been updated recently.

The url http://camdencyclists.coulouris.net/issuemap/ fails too.

**Comment by mvl22** [comment]
I've removed the temporary

```Header set Access-Control-Allow-Origin "*"```

line added to the server config, and that seems to have fixed it, as I think this is now handled at application level.

**Comment by georgio8** [comment]
Nikolai, [your commit](https://github.com/cyclestreets/cyclescape/commit/50496f36074012bd8ffd6189786381344c5eddd0) must be producing the '*,*' that is being disallowed by browser.

**Comment by mvl22** [comment]
No, the problem was I think that now both the application (Nikolai's correct fix) AND the Apache hotfix (added temporarily) meant that two things were creating ```*```, hence ```*, *```.

Now the Apache hotfix is removed the problem is solved I believe.

**Comment by georgio8** [comment]
Thanks Martin, fingers crossed. I was poking around trying to get a proxy to work but your fix seems to have solved it.
