### ISSUE TITLE
Cyclescape not showing last posted message

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#528]
The list shows that someone has contributed to the thread, however there contribution is not showing in the thread. For example:
http://camcycle.cyclescape.org/threads/2236
http://camcycle.cyclescape.org/threads/2072

Have both had updates within the hour which are not showing.

**Comment by nikolai-b** [comment]
Have they come though now?  
Do you mean someone emailed and the email didn't appear on Cyclescape?

**Comment by roxannedebeaux** [comment]
Those messages did come through. 
however there is another example:
http://camcycle.cyclescape.org/threads/181

I can see that a message was posted 12 hours ago but it is not appearing in the thread.
<img width="494" alt="screen shot 2016-03-08 at 10 09 59" src="https://cloud.githubusercontent.com/assets/11997264/13598515/0c72a562-e516-11e5-9427-d0f4d82f86c1.png">

I don't know if they were emailed or entered directly into the thread.
