### ISSUE TITLE
Remove the "Placeford" group from live site

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#529]
At http://www.cyclescape.org/groups the first on the list is the "Placeford Cycling Campaign" test group. This gives a bad impression, especially since it contains no issues, threads etc

**Comment by jf1** [comment]
+1

**Comment by smsm1** [comment]
I'm keen on the idea of hiding groups from the groups directory, so that you can have some that are available but not publicly advertised, for example for Campaign that no longer exists, or a subcommittee group.

**Comment by nikolai-b** [comment]
Now we are ordering the groups it seems like hiding them doesn't make as much sense, things stay unless there is a strong reason to remove but they become less visible.  Am I ok to close this?

**Comment by mvl22** [comment]
Placeford should definitely be removed as it is not real.
