### ISSUE TITLE
Search should include groups

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#530]
When I was trying to find a group on Cyclescape this morning, I searched for "Kingston" but no groups are shown on the results page.

http://www.cyclescape.org/overview/search?utf8=%E2%9C%93&query=kingston&button=

**Comment by jf1** [comment]
+1

Otherwise the list of groups at http://www.cyclescape.org/groups should be sorted alphabetically, which I'm not suggesting as it would prevent implementation of https://github.com/cyclestreets/cyclescape/issues/537

**Comment by nikolai-b** [comment]
I'm am not sure.
https://github.com/cyclestreets/cyclescape/issues/41#issuecomment-226756366
gives an example of the intended final design of the front page which I believe would make the groups search redundant.

**Comment by nikolai-b** [comment]
Now #41 is done I think this can be closed
