### ISSUE TITLE
Group list should shorten long descriptions

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#531]
On the [groups listing page](http://www.cyclescape.org/groups) some groups have long descriptions (Camden has a 550 word description, for example). These should be limited in length so that they take up roughly the same height as the map, with a "read more" link pointing at the group page.

**Comment by jf1** [comment]
+1

Ideally there should be some padding on the right of a group's description too, between that and the "You can request membership..." text in next column along.
