### ISSUE TITLE
Sort list of groups by most active

### ISSUE THREAD

**Issue by jf1** [cyclestreets/cyclescape#537]
Related to https://github.com/cyclestreets/cyclescape/issues/529

Could the list of groups be sorted by most issues, or most activity within the last x days, so the most active groups are near the top?

This would effectively hide groups like Cambridge Cycling City which also has no issues, threads etc. by moving it to the bottom of the list of groups (on page 3).

**Comment by gravitystorm** [comment]
I'd had the same idea earlier on today. With about half the groups being clearly inactive (even to the point of not setting a location), browsing the groups directory currently gives a poor first impression.

**Comment by mvl22** [comment]
Yes, good idea.
