### ISSUE TITLE
Layer switcher in wrong place issues overview

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#543]
![screenshot from 2016-03-15 11 18 46](https://cloud.githubusercontent.com/assets/360803/13776195/c85341f8-eaa0-11e5-9433-17e92af7ae10.png)

Seems to only be a problem at http://www.cyclescape.org/issues#map-pane , and not e.g. My Locations

**Comment by mvl22** [comment]
Suggest fold into #469 (Replace OpenLayers with Leaflet.js).

**Comment by gravitystorm** [comment]
Sure - this is just in case it's a trivial fix, especially since it's correct everywhere else on the site.
