### ISSUE TITLE
Broken popup image for uncategorised issues

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#544]
![screenshot from 2016-03-15 11 18 46b](https://cloud.githubusercontent.com/assets/360803/13776245/09f1c3f0-eaa1-11e5-9992-ea1508a6b6c6.png)

Using Firefox 45 on Ubuntu I see a broken image icon for most issue popups. The ones that have a category-specific icon work fine. 

[issues_controller.rb#issue_feature](https://github.com/cyclestreets/cyclescape/blob/5e13ea4fa82a86f649ad3f687696fac556de113c/app/controllers/issues_controller.rb#L144) requests the image - specifically without a default icon - and so the [issue_decorator](https://github.com/cyclestreets/cyclescape/blob/5e13ea4fa82a86f649ad3f687696fac556de113c/app/decorators/issue_decorator.rb#L42) sets the image_url path to `''`. This gets set as the src attibute in the [popup javascript](https://github.com/cyclestreets/cyclescape/blob/5e13ea4fa82a86f649ad3f687696fac556de113c/app/assets/javascripts/map_popup.js#L23) and Firefox isn't happy with the result.

I traced this back through the code history and nothing relevant has changed since I originally implemented this, so I can only guess that Firefox has changed and now shows a broken image for `<img src="">`.

I think the empty `<img>` is there to make the popups consistent with and without images. I tried with the default icon, and it doesn't look great, so that's probably why we didn't use it originally

![screenshot from 2016-03-15 11 24 53](https://cloud.githubusercontent.com/assets/360803/13776446/0f547b3e-eaa2-11e5-82e1-cb93390fe9e1.png)

The solutions would be one of:
* Remove the img element from the popup (when no specific image is provided) entirely and have everything shift to the left
* Use the default image
* Use a better default image
* Remove the img element from the popup (when no specific image is provided) and add another element with appropriate width and height to keep the text positioned 
* Something else.

**Comment by mvl22** [comment]
Yes, we should be showing a default image.

Am not in favour of removing the image element, as that creates inconsistency.

**Comment by gravitystorm** [comment]
Turns out this was a problem way back in 2012! See #144 

@mvl22 I'm happy to make it use the default icon so that at least it's not broken. Do you have any suggestions for a better icon than just a blank circle? Do we have anything appropriate already, or will we need something new?

**Comment by mvl22** [comment]
I think the blank circle is fine.
