### ISSUE TITLE
Original sources for designed icons and sprite sheet?

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#545]
Do we have any of the original, presumably psd or SVG, source for the icons used on the site?

I was trying to change the colour of the vote icons to green (since grey/light-grey means it's very hard to tell if you've already voted) but there's no green arrows [on the sprite](https://github.com/cyclestreets/cyclescape/blob/5e13ea4fa82a86f649ad3f687696fac556de113c/app/assets/images/sprite.png).

To solve this we'd need the original icons, and whatever was used to create the sprite. The icons are heavily anti-aliased so I'd rather avoid bodging them into the existing sprite manually.

**Comment by mvl22** [comment]
@joshangell Hi! Don't suppose Supercool has these on file?

**Comment by gravitystorm** [comment]
It might be worth asking Supercool via email, given that it's 4 weeks without a response here.

**Comment by gravitystorm** [comment]
@mvl22 Did you get a chance to email them yet? Any response?

If not, I guess we'll need to recreate the sprites ourselves.

**Comment by nikolai-b** [comment]
Given we've #923 I don't think we need this (nearly) 4 year old issue
