### ISSUE TITLE
API 'excluding_tags'  parameter should OR all the tags listed

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#549]
> excluding_tags, type: Array, desc: 'An array of tags that the issues must not have, e.g. ["taga","tagb"]'

As currently implemented this request excludes issues that have both taga AND tagb. But a more useful interpretation would be to exclude taga OR tagb.

I need this to implement a feature requested by @jf1 (for an Issue Map menu option to display 'all but the above').

Of course ultimately we could go for  #a full Boolean logical expression to formulate issue selectors for but the the tags and the excluding_tags parameters, but I'm not asking for that here, just a quick extension to implement Jonathan's request.

**Comment by jf1** [comment]
+1 from me obviously. Seems like that API call was intended to exclude issues that feature any (ie one or more) of the excluding_tags rather than exactly one of the excluding_tags - so looks more like a bug fix than a feature request to me.

**Comment by georgio8** [comment]
- The simplest fix would be to change the interpretation of excluding_tags to exclude Issues that have any of the listed tags. 
- Another simple option would be to keep the existing interpretation for the excluding_tags param and add another parameter excluding_any_tags with the interpretation I'm asking for.

**Comment by georgio8** [comment]
Has this been pushed to the server? I'm not seeing it yet.

**Comment by nikolai-b** [comment]
Yes it has, can you give an example?

**Comment by mvl22** [comment]
> Has this been pushed to the server?

George, just to say that you can always check, by clicking on the link after "GitHub Version" at the end of each page, which takes you to the latest commit.

**Comment by georgio8** [comment]
My coding error. The 'OTHER' menu item in [this version](http://maps.camdencyclists.org.uk/cyclescape-issue-map/index++.html) uses it and is now working well - try selecting the second 'OTHER'.
Many thanks for the quick response Nikolai!

**Comment by nikolai-b** [comment]
Great, glad it wasn't my coding error!
