### ISSUE TITLE
Max zoom for initial issue display

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#55]
Detailed lines and areas can lead to the map defaulting to zoom 18, which is probably a bit too close (and is likely to give problems with missing map images). Points default to a lower zoom for good reason, and lines and areas should zoom-to-bbox-but-not-higher-than-X too.

**Comment by nikolai-b** [comment]
I've set this as 18 max here https://github.com/cyclestreets/cyclescape/blob/staging/app/assets/javascripts/map_display.js.coffee.erb#L14 which seems to work fine.  I can set to 17 if you prefer but closing for now as the tiles work at 18.
