### ISSUE TITLE
Migrate to new /v2/geocoder API call

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#551]
The CycleStreets API V2 geocoder call is now public.

http://www.cyclestreets.net/api/v2/geocoder/

This brings the key benefit that you can return the full geometries, using `geometries=1`, so the map can be zoomed in, rather than merely be panned but stay at the same zoom level.

**Comment by jf1** [comment]
On the webpage, this text seems wrong: Example which finds results for Buckingham Palace (a location in London, UK), ...
Looks like it should be: Example which finds results for Downing Street, ...

Perhaps it's work in progress or I'm missing the rationale behind `"properties": { "type": "Unknown type"`. Ideally if a feature has the OSM tag `highway` present then its `Unknown type` value would become eg:
Highway, Trunk
Highway, Residential
Highway, Bridleway
etc.

Finally, when `&geometries=1` and the `highway` tag is present as above, could the JSON output include the OSM way IDs?
Just thinking about future functions to store eg [CEAT](http://ceat.cyclenation.org.uk/) scores and/or a local group's strategic cycle network suggestions. Both scenarios require data that's linked to OSM way IDs being stored somewhere, hopefully cyclestreets/scape.

**Comment by mvl22** [comment]
@jf1 All those are now in place:

> Example which finds results for Buckingham Palace

Sorry, documentation fixed.

> Perhaps it's work in progress or I'm missing the rationale behind `"properties": { "type": "Unknown type"`.

Bug. The type is now OSM.

> Ideally if a feature has the OSM tag
> could the JSON output include the OSM way IDs

There is now support for enabling fields `osmType`, `osmId`, `osmTagKey`, `osmTagValue` in the returned data. See the second example:

http://www.cyclestreets.net/api/v2/geocoder/

These are not connected to geometries or the presence of the highway tag.

> Both scenarios require data that's linked to OSM way IDs being stored somewhere, hopefully cyclestreets/scape.

The /v2/photomap.locations API call is what should be used. Though this isn't the right place to discuss this.
