### ISSUE TITLE
Text box size in new issue window

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#555]
Thanks! The new issue windows now fit on my screen. Unfortunately the text box is only the size of two rows of text. Despite the scroll feature, it is very challenging to fit and format messages and the deal with line breaks etc. It should be five lines deep at the very least.

**Comment by nikolai-b** [comment]
You should be able to drag the text box to a larger size to what ever suits your screen

![screenshot from 2016-04-22 16-08-00](https://cloud.githubusercontent.com/assets/6289830/14745967/5d4c2cda-08a5-11e6-88f2-9bc18a9d38dd.png)

**Comment by roxannedebeaux** [comment]
Ohhhhh Magic! I had no idea! Thanks.

It might help to have something explaining that because I am sure there are
people who are even less likely than me to work that out.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*

**Comment by nikolai-b** [comment]
I'll tweak it to display 4 lines on small screens but I was worried that might obscure the create thread button.

**Comment by roxannedebeaux** [comment]
It is a trade off isn't it! hopefully 4 lines will work.

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*Cambridge Cycling Campaign*
Charity, no. 1138090

w: http://www.camcycle.org.uk/     e: roxanne.debeaux@camcycle.org.uk
Join the Campaign at: http://www.camcycle.org.uk/membership/join/
*Donate to support the work we do. Text "CYCC11 £5" to 70070*
