### ISSUE TITLE
Area-drawing interface improvements

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#56]
The area-drawing interface will be very new to many people, and so it might be useful when funding/time allows to add tooltips to the Openlayer interface for drawing the area on.

http://www.rightmove.co.uk/draw-a-search.html
has a great example of this (based on the Gmap framework).

http://jacobtoye.github.com/Leaflet.draw/
seems to be a near-emulation of this for Leaflet.js

Both of these (in particular the first) make this drawing interface much easier for newbies to deal with.

**Comment by mvl22** [comment]
Note that #296 requires the ability for an editing control which removes individual geometries.

**Comment by nikolai-b** [comment]
With leaflet draw now in (with tooltips) can we close this?
