### ISSUE TITLE
Fix deadline setting box so that Monday is left-most, not Sunday

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#567]
The default to set Sunday as the first left-most is wrong. It should be Monday. We keep getting wrong dates in Cambridge because of this.

Is an internal locale setting properly being picked up perhaps?

![calendar](https://cloud.githubusercontent.com/assets/361423/14796546/cf393ebe-0b25-11e6-9547-6a925b35411b.png)

**Comment by jf1** [comment]
+1 for a Mon-Sun layout.
