### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#569]
Since this morning my app has been unable to access the API. The server is returning a status 400 in response to all requests:
http://www.cyclescape.org/api/issues/?order=size?order=size&bbox=-0.5534,51.2702,0.2565,51.6936&tags=[%22consultation%22,%22cycle-superhighway%22] Failed to load resource: the server responded with a status of 400 (Bad Request)

Nothing has change at my end.

**Comment by georgio8** [comment]
You can see the behaviour here: http://maps.camdencyclists.org.uk/issuemap/

**Comment by nikolai-b** [comment]
Sorry, fixed in 51458c8 and I thought I'd deployed it but the deploy had failed :disappointed:

**Comment by georgio8** [comment]
Thanks Nikolai!
