### ISSUE TITLE
HTML not being escaped properly 

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#572]
If I write 

Lorem &lt;h2&gt; ipsum 

In a post (whether by email or on the website) the 'ipsum' comes out bold on a new line and the h2 in angle brackets is missing, so presumably the angle brackets aren't being escaped properly.

**Comment by nikolai-b** [comment]
This is the intended behavior.  Post bodies are passed through 
http://apidock.com/rails/ActionView/Helpers/TextHelper/simple_format

Quoting from the [documentation](http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html)
> Sanitization
> Most text helpers by default sanitize the given content, but do not escape it. This means HTML tags will appear in the page but all malicious code will be removed. 

Thanks for reporting but I'm satisfied this isn't a security issue so I'm going to close this.  Please re-open if you have other concerns.

**Comment by davidearl** [comment]
So how do I put something in angle brackets in my post, and how am I supposed to know there is a hidden syntax applied to what I type?

**Comment by mvl22** [comment]
The issue is whether the postings should be regarded fundamentally as HTML or text. I see them as text and am surprised they aren't been treated as such.

It should just be treated as processing like with php.net/htmlspecialchars, i.e. & > < characters being escaped.

**Comment by nikolai-b** [comment]
That is a change to the current design.  It looks like it only effects a few messages though, I can change it easily if your sure that is what you want.

**Comment by georgio8** [comment]
Many user would like simple HTML formatting, e.g. to make discussion contributions more structured (bullets, etc.) But I think most users won’t be expecting to use HTML tags to produce it, I think they want a simple WYSWYG editor (as in Wordpress, etc).

I agree with Martin that this isn’t a bug fix, it’s design change, but it’s high time we debate and a few other things that are inhibiting Cyclescape’s use in my view!

**Comment by mvl22** [comment]
The current input box accepts text, and is not an HTML box, so I think strongly should be displayed as such.

Adding HTML functionality requires a simple WYSWYG editor and should be considered separately on the ticket about that.

**Comment by davidearl** [comment]
The way to do that is to use a rich text editor like tinymce. With the
relevant uploader, that would also allow inline images etc, and allow the
reorganisation of the tabbed panel which has repeatedly caused people to
lose what they type because they don't expect the tabs to act as
alternatives, so they type text and then switch to image and lose their
text.

Tinymce v4 is really quite good, a big improvement on v3. I just installed
it in Ensembling to replace the old ckeditor, and we are using it in the
Cameo membership database system for preparing rich text mailshots and
letters.

But removing verbatim text like the h2 is just so unexpected and for geeks
only.

**Comment by mvl22** [comment]
The richtext ticket is #390.

**Comment by georgio8** [comment]
So I read David response as a vote in favour of moving to a rich text editor for posts. 

Of course that doesn’t work when posting from an email client. Any suggestions for that?

**Comment by davidearl** [comment]
IMoO, If the email has HTML, use that, including images and attachments, if
not (which is fairly rare these days) convert plain text according to basic
rules (tow new lines for a paragraph, one for a br, multiple spaces with
nbsp, but otherwise escape everything.
