### ISSUE TITLE
Add simple label to issue form clarifying resizing of image

### ISSUE THREAD

**Issue by jf1** [cyclestreets/cyclescape#573]
I don't know if there's a limit on file or image size, or if there's a recommended aspect ratio. If there is, please add a comment to the `(optional)` text on the right of [/issues/new](cyclescape.org/issues/new).

**Comment by nikolai-b** [comment]
We use imagemagick to create a thumbnail of 356x200 pixels.  There isn't really a max file size, I guess ideally we should add one.  I'm somewhat reluctant to add this to the `issue/new` text as I think this overwhelming and not what most sites do.  If the current settings don't work we should just adapt them and ask users to modify their images only as a last resort.

E.g.
http://www.cyclescape.org/issues/2158-tfgm-mcc-city-centre-cycling-infrastructure-plan

**Comment by jf1** [comment]
The text (optional, 2MB max, for 356x200 thumbnail) would convey all anyone
might need to know. I must have been lucky uploading a size (1394x784) that
resizes to 356x200 - If the upload isn't 16x9 would imagemagick crop it to
maintain its aspect ratio? There's no problem, especially if it crops
rather than stretches or squashes - I was just suggesting a minor
refinement.

**Comment by mvl22** [comment]
I agree - I think the only action here needed is just to add a comment to the right-hand-side of box 2 on the new/edit thread form, which just clarifies for the user how an image is handled, i.e. that it is resized in some way.

I think it's a sensible thing for a UI to give reassurance to a user for a question that I think many users would have. Some users may not be adding images on the basis that they don't want to risk making a mess (e.g. with a massive image), and simple text would reassure them.

**Comment by nikolai-b** [comment]
I am not sure what text you'd like.
If the image is clicked we show upto a 740x555> version (with a link to the original)
and on the normal thread page we show 500x375> 
See https://github.com/thoughtbot/paperclip/wiki/Thumbnail-Generation#resizing-options for an explanation of how we resize, it is using the default options.  We could say: "the image may be resized maintaining aspect ratio" but I would argue that this may we be more confusing than informative.

I am not sure where I got my 356x200 figure from previously but it is wrong, see https://github.com/cyclestreets/cyclescape/blob/staging/lib/photo.rb .

**Comment by mvl22** [comment]
How about simply:

"The image will be automatically resized to an appropriate size."

which I think would reassure the user.

**Comment by jf1** [comment]
If there's a filesize limit and uploading a photo is still optional, how about:
"Optional, 2MB max, will be automatically resized."

If 740x555 is the maximum the site will usually show then I feel there's limited value in users uploading larger images. While some users will upload their original file whatever the size (even if eg 5000px+ wide from a modern smartphone), I'm more likely to resize before uploading so I'd rather know what to aim for.

I've not experienced the new cyclestreets photomap integrations yet but wonder if there's more potential benefit in larger images uploaded via the cyclescape interface being placed directly into the photomap system, with the cyclescape thumbnails linking to the original image on photomap. The photomap system may need enhancements to handle group privacy or another option could be to have a "private: yes/no" option in the cyclescape upload interface then if a user selects 'no' their original photo is not uploaded to the photomap.

**Comment by nikolai-b** [comment]
There is no max file size so I don't want to add text saying there is.  You can see the image in full size if you click on in and click on "View the original image".

Regarding the Cyclestreets photomap it helps to keep Github issues focused on one thing, if you have a specific requests (e.g. link to original image instead of making a copy on Cyclescape) please add a new issue.

**Comment by mvl22** [comment]
Thanks - I think that hint will give users the reassurance they need.

I've always found that the resizing seems to do the right thing.

**Comment by nikolai-b** [comment]
On reflection I agree with @jf1 that we should have a max file size so I've added that also to prevent accidental very large uploads.

**Comment by mvl22** [comment]
> On reflection I agree with @jf1 that we should have a max file size

Yes, that's fine.

I think 3MB is too small though - digital cameras these days can be more given the megapixel race.

I'd suggest maybe 10MB is probably a better figure. If that's too high, go half-way at 6MB.
