### ISSUE TITLE
Two-word tags are encouraged but not supported

### ISSUE THREAD

**Issue by jf1** [cyclestreets/cyclescape#574]
AFAIK this issue has always existed, and it's now more relevant as tags can be used with @georgio8's issues map.

If you enter a `two word` tag, ie containing a space, then the input screen considers it a single tag, eg:
![image](https://cloud.githubusercontent.com/assets/4711363/15257569/dbfe1c56-193e-11e6-87fe-c27110b31ccc.png)

However, once the issue is created it becomes two separate tags:
![image](https://cloud.githubusercontent.com/assets/4711363/15257615/14542942-193f-11e6-854e-2dded552ade5.png)

(I'm sure I've seen a guide specifically encouraging `two word` tags but typically I can't find it now).

**Comment by nikolai-b** [comment]
@mvl22 this is simple to fix https://github.com/cyclestreets/cyclescape/blob/master/lib/taggable.rb#L63 but it would mean more variation in how people write two word tags.  Another _solution_ could be to change the tagging library to show split the tag when a user types a space (e.g. apply https://github.com/bootstrap-tagsinput/bootstrap-tagsinput/issues/148#issuecomment-47201499 https://github.com/cyclestreets/cyclescape/blob/master/app/assets/javascripts/tags.js.coffee#L20)

**Comment by jf1** [comment]
> it would mean more variation in how people write two word tags

I'm not sure this needs to be addressed but if deemed necessary it seems straightforward to deal with eg by adding, after an amended line 63, a command to replace ' ' with '-' within tags.
