### ISSUE TITLE
Error when posting planning application as new issue

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#580]
This happens:
<img width="688" alt="screen shot 2016-05-31 at 13 01 46" src="https://cloud.githubusercontent.com/assets/11997264/15673673/15debb70-2730-11e6-85dd-35f15faa90a0.png">

This is the planning application:
https://idox.cambridge.gov.uk/online-applications/applicationDetails.do?activeTab=dates&keyVal=O7BO6KDXLQT00

**Comment by mvl22** [comment]
@nikolai-b Could you take a look soon as you get a chance? Also, when fixing could we add a test as this seems to have broken before, perhaps for different reasons.
