### ISSUE TITLE
Thread unsubscription problem

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#581]
Feedback no. 2226:

> I'm trying to unsubscribe from a thread (http://camcycle.cyclescape.org/threads/1879, specifically),
> but clicking "UNFOLLOW THIS THREAD" gives a 404 :(.

Does work for me.

**Comment by nikolai-b** [comment]
I can see nothing in the error logs. Not sure what to do as I can't re-create this.  Can we close the issue until it can be reproduced?

**Comment by mvl22** [comment]
Can you try reproducing it for the user noted in the feedback number noted above?
