### ISSUE TITLE
accept thread/issue ids directly in search

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#59]
e.g. searching for "170" should have a link at the top to threads/170 and issues/170 and library/notes/170 and library/items/170, depending on which exist.

**Comment by mvl22** [comment]
See also #162 which should go in at the same time.

**Comment by mvl22** [comment]
Can you check that a search for say 14 would not pick up 145 or 2145?

**Comment by nikolai-b** [comment]
Very good point.  I hadn't check that but it looks like it works as hoped
and 14 doesn't pick up 145.  It is on staging so you can double check it
doesn't add other strangeness there.
