### ISSUE TITLE
Serve OpenLayers using the Assets pipeline

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#6]
At the moment OpenLayers is served directly from the public folder, without an Expires tag. Rather than setting up an Expires tag, and then faffing around whenever we need to change it, it would be best served via the assets pipeline.

We've tried this before and didn't get it working, but OSM has managed it somehow.

**Comment by nikolai-b** [comment]
We want to move away from OpenLayers

**Comment by mvl22** [comment]
+1 !
