### ISSUE TITLE
Leaflet-related bugs

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#600]
Following on from #469 I've noticed a few regressions on staging. These include:

- [x] Map popups are unstyled (should be grey and with icon to the side)
- [ ] cursor turns to a click-pointer even when there's nothing to click (e.g. on issues#show)
- [x] area polygons should have a white fill, not black
- [x] when you edit a point-based issue, the map control starts adding a new area instead of moving the existing point
- [x] there appears to be no way to reposition a point when editing
- [x] when creating an issue, and drawing the area, when the shape is completed it should immediately be in 'adjustment' mode
- [x] when editing points, a generic leaflet icon is shown instead of a cyclescape generic marker (or a small circle, as before)
- [x] the icons at the top of the editing guidance are greyed out when editing an existing issue but they still work
- [x] drawing a route actually draws an area
- [x] selecting 'point' causes the guidance to jump up and the icon to be detached from the cursor

Unfortunately I don't have any more time this week to work on them, so I thought I'd put them here rather than make a dozen different issues for now.

**Comment by nikolai-b** [comment]
Great.  I'm pretty bad at noticing design issues so that's a real help.  I'll get though these ASAP and update here.  Cheers!

**Comment by mvl22** [comment]
Issues raised by me:

1) Collisions checkbox box has disappeared on the issue page. Using the hard-to-find tickbox within the standard leaflet control also doesn't show collisions, but generates error `Uncaught TypeError: Cannot read property 'lat' of undefined`.

2) On `/user/locations/new`, if you draw a polygon, then press Clear to remove it, the `Drag handles, or marker to edit feature` tooltip is shown, but no type is selected, so it doesn't actually do anything and doesn't give the user any indication why not. I think if Clear is chosen, the previously-selected object type should be selected. So if drawing an area, and Clear is clicked on, the Area button should get auto-selected.

3) The namefinder input box on the left, under +/- box, is very small. I would prefer the styling to be the same or similar to: https://www.cyclestreets.net/collisions/

**Comment by nikolai-b** [comment]
I think these issues have all been addressed (both from @gravitystorm and @mvl22).  I wasn't sure about the top two on @gravitystorm's list so I've not ticked them but I believe he's done the top one and I couldn't re-create the second.

**Comment by mvl22** [comment]
First two are fixed.

I'm afraid though that the results, and interface is significantly worse than what it used to be. Search for London and it gives a zoom in and then immediately zooms out to the UK, making it useless.

In terms of layout, it overlaps the middle of the map - can we get this just to the right of the +/- controls (rather than underneath) as per the CycleStreets example.

Results seem to be getting results from the USA and other places. Hmm, though I see this affects the main site also. So perhaps leave this for now.  CycleStreets adds `&countrycodes=gb,ie`.

I see that callback=... is being sent - that's basically the JSON-P implementation which is only needed for IE8. This means that failures in the results won't properly be handled by jQuery. For CycleStreets, the code we use is:

```
    // Function to determine requirement for IE<=9 to use JSONP instead of JSON; see: http://stackoverflow.com/a/19562445/180733
    jsonpTransportRequired = function () {

	// Determine details of the current browser
	var Browser = {
	    IsIe: function () {
		return navigator.appVersion.indexOf('MSIE') !== -1;
	    },
	    Navigator: navigator.appVersion,
	    Version: function() {
		var version = 999; // we assume a sane browser
		if (navigator.appVersion.indexOf('MSIE') !== -1) {
		    // bah, IE again, lets downgrade version number
		    version = parseFloat(navigator.appVersion.split('MSIE')[1]);
		}
		return version;
	    }
	};

	// Result
	return (Browser.IsIe && Browser.Version() <= 9);
    };
```

**Comment by nikolai-b** [comment]
I didn't know how to do country codes easily without messing up international installs.  As I'm sending the bounding box of the map in bbox I think the USA results should be lower down the results list, is this something that could be implemented in the CycleStreets API?

I'm not sure what you mean about the results layout in CycleStreets, for me that blocks the map in a similar manner
![screenshot from 2016-07-12 23-03-36](https://cloud.githubusercontent.com/assets/6289830/16785371/94ce0bf4-4885-11e6-997a-7e61c03e366b.png)

I've switched on jsonp only for MSIE now, thanks for that.

**Comment by mvl22** [comment]
OK, let's push this live now.

We can fix the namefinding stuff up later - on reflection it's probably no worse than what was there before.

Well done on all these changes to rip out OpenLayers.

**Comment by gravitystorm** [comment]
I think this is complete enough that other leaflet problems can be addressed in separate tickets, and prioritised individually.

**Comment by mvl22** [comment]
+1.
