### ISSUE TITLE
Thread title character count does not update when character numbers reduced

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#603]
The only way to know that the characters are within limit is to re-submit the form.

See the attached example - the character count was reduced within limit but the warning remained. 

<img width="757" alt="screen shot 2016-07-04 at 15 10 25" src="https://cloud.githubusercontent.com/assets/11997264/16563397/b7ffa5a2-41f9-11e6-8a10-834088ef527f.png">

**Comment by nikolai-b** [comment]
It wasn't designed to update when you type (that would require quite a bit more work).  I've made it so the title text input has a max length of 254.  Sadly this means if you turn a planning application into an issue then the title might still be too long but you can delete text and you will know you are at the right limit when you can add text again.

E.g.
If the limit was 5 characters and it was initially:
"Too long"
and you deleted "long" so it was
"Too"
and tried to add "ing" then it would stop you at
"Tooin"
and you would not be able to add any more.

**Comment by roxannedebeaux** [comment]
That works.

As long as it is possible to identify when you are at the limit without
having to resubmit.


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*

**Comment by mvl22** [comment]
I don't actually think we should be permitting titles as long as 255 characters - they cause weird layout issues on the My Cyclescape page, as well as being unsuited to e-mail subject titles.

Personally I would say that we ought to be limiting titles to perhaps 80 characters, to encourage succinctness when composing these.

**Comment by roxannedebeaux** [comment]
I don't mind that. The problem is only with planning applications that are
imported.

On Wednesday, 6 July 2016, Martin <notifications@github.com> wrote:

> I don't actually think we should be permitting titles as long as 255
> characters - they cause weird layout issues on the My Cyclescape page, as
> well as being unsuited to e-mail subject titles.
>
> Personally I would say that we ought to be limiting titles to perhaps 80
> characters, to encourage succinctness when composing these.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyclestreets/cyclescape/issues/603#issuecomment-230931705>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALcQUFcPu6ipun6wXTWjzQN5wx2ZFsumks5qTDHWgaJpZM4JEaCq>
> .
>


-- 

Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*
