### ISSUE TITLE
Some Trafford planning applications are in planit but not in Cyclescape

### ISSUE THREAD

**Issue by jf1** [cyclestreets/cyclescape#610]
This might need to wait until #609 is fixed. I'll tidy up the links then if required/desired.

**\* not on map **\* at planit; not in Cyclescape:
http://publicaccess.trafford.gov.uk/online-applications/applicationDetails.do?activeTab=summary&keyVal=O83C00QLHWH00
http://planit.org.uk/planapplic/Trafford/88589/FUL/16/
http://www.cyclescape.org/planning_applications/search?q=88589

mapped at planit; not in Cyclescape:
http://publicaccess.trafford.gov.uk/online-applications/applicationDetails.do?activeTab=contacts&keyVal=O7OSIBQL01000
http://planit.org.uk/planapplic/Trafford/88532/OUT/16/
http://www.cyclescape.org/planning_applications/search?q=88532
http://www.cyclescape.org/planning_applications/uid/88532/OUT/16/

Example of Trafford planning application in Cyclescape: http://www.cyclescape.org/planning_applications/search?q=88467

**Comment by nikolai-b** [comment]
I think this has been fixed now as the pull from plan it was a bit broken.  It won't pull in old ones but I'm going to close this now.  If you notice new ones missing please re-open.
