### ISSUE TITLE
Add a poll feature

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#612]
It would be good to have some kind of poll or vote feature in individual threads to assist with decision making. Ideally at least 4 options.

**Comment by nikolai-b** [comment]
Just to be clear, would this be a new component reply that anybody could create on a thread.

To create it:

Question: textbox to be user filled in

Option 1: string to be user filled in [Remove option button]

[Add new option button] (upto max of 10 options)

Viewing it in the thread:

Question? with a clickable link to full show
Option 1 (n votes)
Option 2 (m votes)


Full show (clicking on the link):

Question?

Option 1 (n votes)
List of voters
Option 2
List of voters

Anyone who can reply to the thread would be able to select the radio box.

**Comment by mvl22** [comment]
Yes that sounds right.

I guess there’s probably a Gem to do this kind of thing.
