### ISSUE TITLE
Hashtags to link together postings across multiple threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#613]
The idea is that including a hashtag like #whatever within a posting on a thread would turn it into a link that, when followed, shows other postings (not whole threads) with the hashtag. Effectively, a kind of virtual thread which is read-only.

This would be majorly helpful for managing cross-cutting matters, e.g. preparing a newsletter, putting something on the website. For instance, if someone thinks that a posting is relevant for turning into a newsletter article, they could just add #newsletter to it; the newsletter editor could then periodically check that virtual thread to get the full list.

Each posting would have a link back to the main thread itself. Possibly this should be most recent first, as the concept here is not about discussion but is more like a twitter-style feed.

I think the hashtags should appear on the same page as normal tags, e.g. "Mentions of this tag", rather than being a separate system (i.e. avoid the confusing way that Wordpress has both tags and categories).

**Comment by nikolai-b** [comment]
So I understand, this is different from Tags in that any user replying to a thread and using #whatever would create a whatever Hashtag.  This is pretty much the same as a tags but at message level instead of thread level.

**Comment by mvl22** [comment]
> This is pretty much the same as a tags but at message level instead of thread level.

Yes.

Though I think they should be listed along with tags. Essentially these are like attaching a tag at message-level, but by typing within the text, rather than typing into a separate box.

**Comment by jf1** [comment]
+1 from me, to the concept and listing hashtags along with other tags.

This reminds me of a recent request: can we search for a thread or message that contains two or more tags?
I can't find it in the issues here, so think I made it using the Cyclestreets feedback system (for photomap).

**Comment by nikolai-b** [comment]
@jf1 
There is an API but no UI for getting issues with multiple tags https://www.cyclescape.org/api#!/issues/getApiIssues
but I'd suggest any further discussion should go into a separate issue ( tag searching / hashtag searching).

**Comment by mvl22** [comment]
Suggestion from a user who I had lunch with to create a video of using this concept. I'm not 100% convinced on this, if the interface can be *really* clear on this, but the discussion I had does make it clear that this feature is liable to be something that novice users need to be able to understand clearly.

**Comment by mvl22** [comment]
Just to say that this feature will obviously need to check the message visibility of each message in the 'hashtag auto-listing', as it were, on display. I suggest that where a message isn't visible to the user, e.g. because it's Committee-only, we just say "Message (not visible to you)" or something.

We also should restrict this feature to groups only, i.e. so that auto-created hashtag listings for a particular hashtag only join those messages of that group. Otherwise we could end up with common hashtags joining messages from far-flung bits of the country within a group's discussion, which is almost certainly not wanted.

**Comment by nikolai-b** [comment]
> I think the hashtags should appear on the same page as normal tags, e.g. "Mentions of this tag", rather than being a separate system (i.e. avoid the confusing way that Wordpress has both tags and categories).

Obviously we can't search for these new hashtags as a Cambridge users' search for "Newsletter" is different to a London users' search for "Newsletter" so I think an entirely different system makes sense.  Here hashtags are group specific so they can't really mesh with the existing tags which are not.
We can then make the hashtag names unique per group so any Cambridge message with "Newsletter" would like to all the Cambridge messages.

**Comment by mvl22** [comment]
> Here hashtags are group specific so they can't really mesh with the existing tags which are not.

Sure, that's fine - give it a try and we'll see how the UI feels.

> We can then make the hashtag names unique per group so any Cambridge message with "Newsletter" would link to all the Cambridge messages.

Yes, good point.

**Comment by nikolai-b** [comment]
I've almost done this but I now realise it clashes somewhat with #428 as
#t1 or #i1 look like hashtags and links to threads and issues.  No message has anything like
#t1 in it so can we remove that and #i1 link style?

```SQL
SELECT COUNT(*) FROM "messages" WHERE (body ~ '#i[0-9]');
=> 0
SELECT COUNT(*) FROM "messages" WHERE (body ~ '#t[0-9]');
=> 0
```

**Comment by mvl22** [comment]
Yes, if it's not being used, that's fine. Good point that this clashes!
