### ISSUE TITLE
After voting to hide a planning application, map changes to closing brace

### ISSUE THREAD

**Issue by mephillips-durham** [cyclestreets/cyclescape#618]
At least in IE11, once you have voted to hide a planning application, the map area shrinks (as it did before) but instead of a map showing, we just get a closing brace:
![untitled](https://cloud.githubusercontent.com/assets/3178149/17520644/628a3f18-5e48-11e6-97f2-cd38b8a05fcb.png)

**Comment by nikolai-b** [comment]
Is this still happening, I think I've pushed some changes around this.
I don't have IE11 but in Firefox and Chrome it works for me.

**Comment by mephillips-durham** [comment]
It's working OK now in IE11. Thanks.
