### ISSUE TITLE
Migrate `runner` jobs to rake tasks 

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#627]
In schedual.rb 
https://github.com/cyclestreets/cyclescape/blob/staging/config/schedule.rb#L25
the jobs are `runner` but this is not as robust as having a rake task calling these, e.g. https://github.com/cyclestreets/cyclescape-chef/issues/36

**Comment by nikolai-b** [comment]
and similarly https://github.com/cyclestreets/cyclescape-chef/issues/35

**Comment by mvl22** [comment]
Thanks for reengineering this.
