### ISSUE TITLE
Map search not working

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#642]
Address not coming through from planning application, have also tried searching for known addresses which also returns "Location not found"

**Comment by nikolai-b** [comment]
Thanks for reporting this but it would be much easier to help if you gave clear steps of what you did and what you expected to happen.
I searched for Leeds when trying to create a new issue and the map search worked as expected for me:
![screenshot from 2016-10-20 11-53-53](https://cloud.githubusercontent.com/assets/6289830/19557069/fdbbab10-96bb-11e6-9ecd-a94d13492bac.png)

With the address not coming though on planning applications that is an external service that we use and it isn't sending us the address so there is not much I can do about it, sorry.

**Comment by mvl22** [comment]
@roxannedebeaux

If you can send me examples of addresses that didn't seem to work, I can check further.

**Comment by roxannedebeaux** [comment]
This has happened again today. 

I try to start an issue (one that isn't fed in from a planning application) I type in the address I get "location not found" I try the street without the number, I try with different punctuation. It doesn't matter what I enter I still get the same result. I am not sure there is any more detail I can provide. 

It has happened again today. I can't get the address 8 Castle Street. 

This is making this part of my job difficult. I seem to have problems with starting issues every single time I sit down to deal with planning applications and it is resulting with things not being raised.

**Comment by roxannedebeaux** [comment]
And now it is working!? I haven't done anything differently. I didn't even refresh the browser!

**Comment by roxannedebeaux** [comment]
I think there is a problem when you try to use the house number.

**Comment by mvl22** [comment]
@nikolai-b I suspect an error in the JS code.

Doing a search at https://camcycle.cyclescape.org/issues/new
for
`8 Castle Street`

I can see that a request is correctly made to the CycleStreets Geocoder API V2, i.e.

https://api.cyclestreets.net/v2/geocoder?q=8+castle+street&bbox=0.11329650878906249%2C52.19963747793401%2C0.15020370483398438%2C52.20884269057986&geometries=1

(with the key field added to that)

and that a result comes back:

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "name": "8",
                "near": "Castle Ward, Cambridge"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.1144942,
                    52.2109739
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "name": "JAC Stores",
                "near": "Castle Street, Douglas"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -4.479002,
                    54.1527999
                ]
            }
        }
    ]
}
```

but these two results do not appear in the drop down.

**Comment by roxannedebeaux** [comment]
I've now tried it with a number of addresses including my home address. It
works with the street name but not with a number.

When I delete the number it still will not work, unless I delete one letter
of the name and retype. It then seems to reset it.

This issue has only arisen in recent weeks/months.




Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*
