### ISSUE TITLE
Unnecessary email notifications when I post

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#645]
When I post to a thread, I receive an email notification to let me know that I've just posted to the thread. This notification is unnecessary!

**Comment by mvl22** [comment]
To clarify:

By "e-mail notification", do you mean the whole message presumably, i.e. you have e-mail delivery switched on and are getting your own message?

**Comment by smsm1** [comment]
Yes, this mimics the way mailing lists work, so that you can reply to your own message. I'm wondering if this should be configurable on a user by user basis depending on how heavily people are using the email pushing side of the system.

**Comment by gravitystorm** [comment]
I'd prefer it to work more like github, where you don't get your own updates, just a notification when other people add to a thread.

I sort of understand Shaun's point about mailing lists. But mailing lists are fully threaded, so you are actually replying to specific messages. For cyclescape, a reply is just another post in a chronological thread. There's no difference between replying twice to a notification vs your second reply being to yourself, since cyclescape doesn't have nested threads.

Because of this, I don't think it needs to be configurable, I think it should just avoid sending notifications to yourself.

**Comment by mvl22** [comment]
I think that the e-mails, which are a full record of the conversion, which try to mirror a mailman-style mailman list as closely as possible, are a different thing to notifications.

Notifications just effectively summarise the activity on a thread in a single sentence (e.g. "Shaun and Andy commented on 'Unnecessary email notifications when I post'"), with a link to the full postings containing the actual content. E-mails by contrast are the full thing.

> cyclescape doesn't have nested threads

Note that this is no longer quite true - e-mails are being properly threaded, so the reply-to is relevant. Switch on threaded listings (if your mail client supports it) and you'll see this:

http://blog.cyclescape.org/images/threading.png
