### ISSUE TITLE
/private_messages order wrong

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#648]
The ordering is the wrong way round. Should be most recent first, as per other thread listings.

**Comment by mvl22** [comment]
`/private_messages` is giving me a 500 now.

**Comment by mvl22** [comment]
The ordering still seems to be completely random.

They should be most recent first, and blue for unread.

**Comment by nikolai-b** [comment]
The order works for me and with the blue, can you confirm this is still an issue?

**Comment by mvl22** [comment]
Confirmed; this is now fine.

**Comment by mvl22** [comment]
There is still a problem here - if you look at `/users/5/private_messages` you'll see there is one message that isn't correctly ordered and hidden away lower down - which is very easy to miss and reduces confidence in using this page:

![screen shot 2019-02-25 at 10 56 17](https://user-images.githubusercontent.com/361423/53332746-fdeabc00-38eb-11e9-808e-f644fc36d9c6.png)
