### ISSUE TITLE
Reply type which sets the 'leader' of an issue - tidy-ups

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#649]
Now that #169 is live (great!), I think we need a few tidy-ups:

1) The person is shown as [leading] in the box on the right, which is good. This needs to have a background color also, so that they stand out, in the same way that the Owner box just above gets a colour. I suggest HTML colour #edbb99 maybe.

2) The layout of the eventual message isn't great. Instead of separating by a line-break, can we have two paragraphs, and put the user quote in quote marks perhaps:

```html
<p>Jane Smith will take on responsibility for ensuring that discussions continually move forward and that actions are carried out and followed-up:</p>
<p><em>"I'll take on responsibility for first-reviewing drafts."</em></p>
```

Obviously the e-mail equivalent will have the same thing but with the HTML stripped, retaining the quote marks in the second line.

3) The optional status of the reason box is not a clear interface, because the user doesn't know what will happen if they don't put something in the box, or whether the suggested text implies that they should phrase their sentence with that kind of prefixed text or just add the bit that would follow after that text. So can we change the label to 'Optional reason', and make the placeholder say 'You may wish to describe your motivation for leading this discussion'.

4) 'Thread leader' isn't very self-explanatory. So above the box add explanatory text paragraph `The leader of this discussion thread will ensure that the matter continues to move forward.`. Then add a second paragraph, in bold (indicating an action) `I will take responsibility for leading this discussion.`.

5) I accidentally clicked the thread leader button a second time, which removed me. I then censored the message. I wonder whether this should revert the status?

6) Could we avoid the American-style capitalisation of 'Thread Leader' - it should be 'Thread leader' (as per deadline/date). 'CycleStreets photo' also needs to be fixed similarly.

7) The `/overview` page describes the message as "Thread Leader Message Html" which is jargon. Can we make it the more event-orientated description 'Jane Smith became leader', like the other types, where the name is linked, and 'Withdrawal of leader' when someone leaves, without stating their name (as that could appear a bit aggressive).

**Comment by nikolai-b** [comment]
Point 5 will take a bit more time.  If it is important can you open it up as a new issue?

**Comment by mvl22** [comment]
> Point 5 will take a bit more time. If it is important can you open it up as a new issue?

Though it might.

I'll leave this for now.
