### ISSUE TITLE
Disabled member still getting subscribed to new threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#651]
If the admin marks a member as disabled, they still get subscribed to new threads, and appear in the user list for an existing thread.

The first problem (still getting subscribed) is the priority to fix, and is presumably an easy fix.

The second problem needs more discussion, as if they were to return then reinstating their subscriptions would be sensible. However, in some cases (e.g. person leaves the country) this is unlikely. In further cases (member is no longer alive) this is clearly problematic.

**Comment by nikolai-b** [comment]
This disabled feature, I'm not sure what it was intended to achieve.  How is disabling different from deleting?

This is a partial dup of #214.

**Comment by mvl22** [comment]
I agree - they seem to be overlapping.

I think the disabled feature was introduced when the spam-filtering/review stuff was putting. Could you try to merge the feature into deletion?

Deletion is a fake-delete anyway, so presumably we can just un-delete if required?

**Comment by nikolai-b** [comment]
Not quite.  A delete will scramble the users name and other features
e.g.
https://github.com/cyclestreets/cyclescape/blob/staging/app/models/user.rb#L218-L231 (ignoring `def display_name_or_anon` it changes other things so is not reversible.  It is a fake delete though.

Disabling users dates back from 2011 https://github.com/cyclestreets/cyclescape/commit/6e9c123 and I would be very happy to remove it, if you want to be able to un-delete users then I guess we store the profile and name in the db and can restore it but that might be a large-ish piece of work.

**Comment by mvl22** [comment]
OK, so basically disabling an account is effectively my example of potential reinstatement in the future, whereas deletion is more like my latter example.

I think the best thing is to take no action, as this basically covers everything we might need already!

**Comment by mvl22** [comment]
Actually, I can't find any way for an admin to delete a user's account - there is no such link.
