### ISSUE TITLE
GeoJSON of all group areas

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#653]
Could we make a GeoJSON which combines all the groups listed at
http://www.cyclescape.org/groups
(without pagination)
with the properties on each geometry to have each property, namely: name, description, cyclescape URL, website URL, e-mail

@nikolai-b Is this a quick job? If so, could you jump this to the top of the queue?

**Comment by jf1** [comment]
And please can you email me a copy, to help me plan a future Cyclenation
membership database and cyclenation.org.uk/map

For info I took the Cyclescape area for "Spokes: SW Herts Cycling Group"
and put it in the above map to prove it can be done (it was
straightforward), and the Cyclescape area for GMCC is not accurate (hand
plotted) whereas the GMCC area in cyclenation.org.uk/map is accurate (using ONS
UGC boundaries
<http://geoportal.statistics.gov.uk/datasets/0293170f45ac4322868978b46dba822d_4>
)

**Comment by jf1** [comment]
And please can you email me a copy, to help me plan a future Cyclenation membership database and [cyclenation.org.uk/map](cyclenation.org.uk/map)

For info I took the Cyclescape area for "Spokes: SW Herts Cycling Group" and put it in the above map to prove it can be done (it was straightforward), and the Cyclescape area for GMCC is not accurate (hand plotted) whereas the GMCC area in [cyclenation.org.uk/map](cyclenation.org.uk/map) is accurate (using [ONS UGC boundaries](http://geoportal.statistics.gov.uk/datasets/0293170f45ac4322868978b46dba822d_4))

**Comment by mvl22** [comment]
@jf1 Please can you remove Cambridge's area - it's completely wrong and misleading.

**Comment by jf1** [comment]
@mvl22 I've changed it to CamCycle's Cyclescape area, hope that's ok. It's only a prototype that hasn't been publicised. My intention was to ask groups to confirm their areas and discuss a shared solution with you.

**Comment by nikolai-b** [comment]
Does 
`curl 'http://www.cyclescape.org/groups/all_geometries.json?bbox=-10.8,49.8,2.1,59.5'` give you what you want?  I know it doesn't quite have all the fields but I can add the others if its nearly there.

**Comment by mvl22** [comment]
Yes, that's looking good. If you could add in the fields that would be great.

For the usage I'm thinking of, it would be very useful to be able to filter by type of group (local vs national). At the moment, the Cyclenation area covers over all groups, making a map less useful.

So it would be good if each group could have a setting 'local' or 'national' (defaulting to local), and I can then set the Cyclenation group to national.

Then the URL needs a parameter to enable type=... to force filtering to a particular type.

**Comment by mvl22** [comment]
Could we adjust this so that national is an option to add in, rather than it being only one or the other?

**Comment by nikolai-b** [comment]
I think this has been done

**Comment by mvl22** [comment]
I can't see any difference:

https://www.cyclescape.org/groups/all_geometries.json?national=1
https://www.cyclescape.org/groups/all_geometries.json

Both end up including the massive Cyclenation area.

**Comment by nikolai-b** [comment]
Its in the API (and documented) now, I added it to the changelog

https://www.cyclescape.org/api/groups.json
https://www.cyclescape.org/api/groups.json?national=1

**Comment by nikolai-b** [comment]
Note it is paginated but the limit is high enough to get all groups

https://www.cyclescape.org/api/#!/groups/getApiGroups

**Comment by mvl22** [comment]
Thanks - looks fine now.

**Comment by mvl22** [comment]
There's a minor bug, which is probably easy to fix:

URLs come out as e.g.

cycleipswich.www.cyclescape.org
