### ISSUE TITLE
Library drawing broken

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#655]
If adding a library item, the drawing on the map fails.

Area mode gives error "`Uncaught TypeError: Cannot read property 'click' of undefined(…)` and so drawing is not possible.

Also, this also seems to result in a type = point result, whereas if you send `&geometries=1` as documented at:
https://www.cyclestreets.net/api/v2/geocoder/
you can get other types of geometry automatically, e.g. searching for 'UK' should give the UK boundary.

**Comment by nikolai-b** [comment]
I do not get either of these issues.  I get not JS errors on Area mode and when I search for UK it does not go to a point:
![screenshot from 2016-11-19 08-09-28](https://cloud.githubusercontent.com/assets/6289830/20454156/8f3c3d7c-ae2f-11e6-9767-05c37b44d1bc.png)

Does the JS error always occur when you select Area?  I assume that when you hit a JS error that causes the UK search to brake somehow.

**Comment by nikolai-b** [comment]
Any more on this?

**Comment by mvl22** [comment]
Confirmed - the problem seems to have gone away now.
