### ISSUE TITLE
Message from member of good standing put into spam moderation

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#658]
Nikolai,

Could you look and see why message 37340 got put into moderation? I didn't see any reason given.

If there's not a log showing this, could we make a persistent log for future debugging?

The message was posting by a long-present member of good standing. Ideally the spam filtering should assume a trust model for such message.

The user then sent two further identical messages, and also two further messages on the meta subject of the spam filtering itself to the thread, which also (usefully) got filtered (and which should not be approved).

**Comment by nikolai-b** [comment]
I believe you only ever gave me the Akismet key and not the full log in details but any log on why they thought a message would be spam would be held there.

**Comment by nikolai-b** [comment]
This is an Akismet issue.
