### ISSUE TITLE
Residual non-subscription problem after posting to thread

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#659]
I've just posted to thread 857 but I'm still seeing the 'Follow this thread' button, and I'm not listed in the 'Following this thread' list.

I thought we'd tackled bugs related to this kind of thing (I'm certainly not receiving reports any longer on it) but it does seem there is a residual bug (or perhaps a database consistency issue) that needs to be cleared up still.

**Comment by nikolai-b** [comment]
Yes, the logic is somewhat complicated.  The code reads 
https://github.com/cyclestreets/cyclescape/blob/staging/app/models/message.rb#L122
subscribe creators of a message on a thread to the thread if they have never been subscribed to that thread.  You have previously been subscribed and then you un-followed this thread, hence you not automatically being re-subscribed.
This has always been the logic: 
https://github.com/cyclestreets/cyclescape/commit/2d2f685f

I can change it easily to always subscribe you even if you previously decided to un-follow as this makes more sense to me but thought I should be explain and check first.

**Comment by mvl22** [comment]
That current logic does make sense (as it avoids the problem of a user changing their geography and getting re-subscribed to stuff they already explicitly I subscribed from).

I think the extra thing that needs to be added to the logic is that a posting or an explicit follow-this-thread is a clear indication of cancelling their previous intention.
