### ISSUE TITLE
Need to be able to disable a group

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#662]
`/admin/groups` currently has no ability to mark a group as 'disabled', i.e. so that it doesn't appear in the API and in listings, and so that the subdomain is not recognised.

Currently, Cambridge Cycling City (`camcycity`) needs to be disabled but there is no way to do so, and it's polluting the API output and listings.

**Comment by nikolai-b** [comment]
So in a first stage disable would merely hide it from the API?  Would people still be able to make new threads owned by disabled groups?  Could people request to join them?  I am assuming no but was thinking there are probably some other things we would like to prevent when a group becomes disabled.

**Comment by mvl22** [comment]
These are all good questions. I think essentially a disable should freeze the group in time and hide it, so no further activity and no viewing.

Or perhaps it should really be treated as a fake-delete? Hmm.

The problem here is a group that was set up experimentally and had a bit of activity but is no longer wanted, though the data itself shouldn't be destroyed. However there could be cases where a group becomes inactive but needs to be re-activated.

Would welcome any ideas!

**Comment by nikolai-b** [comment]
We can make delete move any threads linked to it have no owner and remove all the memberships?

I am somewhat reluctant to add a disabled state as we will undoubtedly forget to disable some features that make the group frozen.  Then again if you are happy to have these missed we can make disabled stop new threads or members being created and hide it from the API.  Then if we want to add more functionality we can.

**Comment by jf1** [comment]
Have you considered three options for group status: active, inactive, disabled
(The word "hidden" may be better than "disabled")

An "inactive" group would allow historic posts to be viewed while preventing creation of new posts etc.

I understand @nikolai-b's concern and reluctance, however I feel it's better to aim for a more useful range of settings and features, even if some aspects are missed and must be added later, especially in this case where the inactive/hidden options would only be used sparingly.

**Comment by mvl22** [comment]
I suggest for the moment that we implement the hiding, and worry about the question of freezing a group later.

So:

* There would be a tickbox, `hidden` that a system administrator can set
* This would remove it from the `/groups` listing and from the API listing
* This would remove it from the drop-down list in the top-right that a user gets

Changes, like new threads, would still work. But that would require someone to go to the group's URL who knows it. In practice, the group noted above is not actually seeing any such activity even though it is actually visible.

**Comment by mvl22** [comment]
On using Disable, I get:

`The change you wanted was rejected.`

Pressing back shows that no change was made.

**Comment by mvl22** [comment]
Will I be able to un-disable?

I was assuming this would just be a tickbox on e.g. the

`/admin/groups/<id>-<moniker>/edit`

page, as a button in the admin group listing is very prominent for what will be a very rare action.

**Comment by nikolai-b** [comment]
https://github.com/cyclestreets/cyclescape/issues/662#issuecomment-268653512 that was because you were disabling `devon-otter-trail` which is now an invalid group (the short name can't have `-`) on staging I've changed it to `devonottertrail` manually, any suggestions for production.

You can enable disabled groups.  I started as a checkbox but it felt more like an action as you'd mentioned `/admin/groups`, sorry.  The minor advantage of the action is we store the time a group was disabled more easily.

**Comment by mvl22** [comment]
Good to make live - thanks!
