### ISSUE TITLE
Add issuemap to list of reserved subdomains

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#667]
Somewhere I believe there is a list of reserved subdomains like `www`, `blog`, `api`, etc., which cannot be used as group subdomains. (I can't actually find this via Github search, and I can't see it in `/app/models/group_request.rb` which is presumably roughly where it would be.)

We now have
https://issuemap.cyclescape.org/
as an officially-maintained API integration.

So `issuemap` needs to be added to the list of subdomains.

**Comment by mvl22** [comment]
Thanks. What is it, out of interest, that makes Rails pick up that file? I presume there is a magic method implementation of some kind.

**Comment by nikolai-b** [comment]
http://devblog.orgsync.com/2013/10/29/building-custom-rails-attribute-validators/

That is a custom validator in addition to the [standard rails validators](http://guides.rubyonrails.org/active_record_validations.html).
It is used https://github.com/cyclestreets/cyclescape/blob/staging/app/models/group.rb#L30 (and on the group request)

**Comment by mvl22** [comment]
Thanks - that's useful to understand.

So basically `subdomain: true` essentially maps to loading of `lib/subdomain_validator.rb` - that makes sense.
