### ISSUE TITLE
Changing a priority provides no feedback

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#668]
The thread priority buttons have been changed to work via ajax. however, there is no feedback indication to show whether this has been successful or not. I found myself selecting different priorities and unsure if my changes were saved or not.

**Comment by gravitystorm** [comment]
I would suggest something like a yellow highlight on the priority when selected, which turns to green on successful save and then fades out. Or disable the form for a moment or two while the change is saved, and then show a confirmation. Or something along these lines.

**Comment by mvl22** [comment]
> I would suggest something like a yellow highlight on the priority when selected, which turns to green on successful save and then fades out.

Yes, agree.

**Comment by nikolai-b** [comment]
We now add a status at the top of the page
