### ISSUE TITLE
User list in admin area needs amendment to pagination

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#669]
I see the user list in the admin area has been paginated, which was probably long overdue.

However, it's now very hard to find a particular user when that user's e-mail is known.

Could we either:

* Quick, workaround solution: Increase the number of items per page, so it doesn't take as many control-f page searches to find a user
* Proper solution: Add a search box which searches all fields.

**Comment by nikolai-b** [comment]
Yes, sorry I should have checked first.  Is email the only field you want to filter on?  What about display name (or name)?

**Comment by mvl22** [comment]
All those three would be useful if the search could be indexed against them.

**Comment by mvl22** [comment]
Thanks - that works nicely.

Could you just adjust the styling so that the `main-search-box` div has say 2em of margin below it, and it has a border, e.g. `border: 1px solid #ddd;`, so that the box is more clearly separated from the table below it.

**Comment by mvl22** [comment]
Much clearer!
