### ISSUE TITLE
Link for "group" is misaligned

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#673]
In Firefox on a Mac. 

The link for "Group" is now under the search box. Often this gets clicked instead of the search field so this is very annoying. 

<img width="401" alt="screen shot 2017-01-04 at 16 58 21" src="https://cloud.githubusercontent.com/assets/11997264/21651083/3c2b4c88-d29f-11e6-8a1f-362e5b07ce9d.png">

**Comment by mvl22** [comment]
Note this is when a user is a Committee member and thus has 'Membership' added to the menu.

**Comment by nikolai-b** [comment]
Is this still happening?  I can't recreate this in Firefox or Chrome on Linux.

**Comment by mvl22** [comment]
If you are a committee member and/or an admin, this happens. If you give yourself as many permissions as possible you should see the problem of things not fitting in the menu.

I see this in Chrome on Windows and Mac.

**Comment by mvl22** [comment]
@nikolai-b Turns out this one is considered a major issue by some users. Could you prioritise this one?

I guess we might need to respace the menu or something - hopefully you can come with something sensible.

**Comment by roxannedebeaux** [comment]
This problem is actually worse now. The search box cannot be used as the
group name link is sitting on top of it.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *
camcycle.org.uk/donate <https://www.camcycle.org.uk/membership/donate/>
*Charity no. 1138098*

**Comment by roxannedebeaux** [comment]
Note this has made a huge bottleneck for me today as I can't search for the
threads I need to access in order to progress other urgent work.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *
camcycle.org.uk/donate <https://www.camcycle.org.uk/membership/donate/>
*Charity no. 1138098*

**Comment by mvl22** [comment]
As a (ropey) workaround in the meanwhile, you can use tab to progress to the searchbox on the page, and then type in the search term and press return to submit.

**Comment by nikolai-b** [comment]
I'm confused.  On subdomains I don't see the group. Could you include the full URL?

Also I'm able to close the group selector, is this not possible?

![group changer](https://user-images.githubusercontent.com/6289830/57586565-5bf06e00-74ef-11e9-8531-b6ea447fcb2f.gif)

If the change I made doesn't help then I will revert it.

**Comment by mvl22** [comment]
See this screenshot - I've done select-all with the keyboard to highlight the text more clearly. Note the overlay over the search box.

![Screen Shot 2019-05-13 at 00 31 44](https://user-images.githubusercontent.com/361423/57589075-75f17700-7516-11e9-8f46-c1b848a0ae63.png)

**Comment by roxannedebeaux** [comment]
So the overlay on the search box is worse when the page has been scrolled
down. At the top, it looks like the picture from Martin. Scrolled, the
overlay is worse and the box cannot be clicked in (This is something that
only started to happen recently).

The only way to get out of this is to then refresh the page. Even being
able to click on blank screen space to remove the menu would be a step
forward.

It is even more difficult on a mobile phone as it is very hard to 'click'
on the search box without activating the menu which you can only get rid of
by refreshing the page.

This is something I easily end up having to do 10 + times a day. Really
frustrating especially considering how slow Cyclescape is to load. This has
been going on for over a year so I do hope it can be resolved.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *
camcycle.org.uk/donate <https://www.camcycle.org.uk/membership/donate/>
*Charity no. 1138098*

**Comment by nikolai-b** [comment]
@mvl22 and @roxannedebeaux I think part of the problem is that I'm not seeing that on my browser.

A simple solution could be to move the search box to the left, would you be happy with this?

| At top of page | Further down the page |
| ------           |       --- |
| ![Screenshot from 2019-05-14 20-20-33](https://user-images.githubusercontent.com/6289830/57725805-e4087c00-7685-11e9-9d62-42101d8ce667.png) | ![Screenshot from 2019-05-14 20-20-48](https://user-images.githubusercontent.com/6289830/57725806-e4087c00-7685-11e9-94ef-2c4035e99ea4.png) |

Also I can add a 0.5 second timeout on the group dropdown so it is only there on hover.

**Comment by mvl22** [comment]
If you add the Membership menu entry, that will pretty-much guarantee you experience the problem.

I'm not keen on search being moved. It's in a very standard position, and it's very odd to have it on the left.

If you change

`#main-nav nav ul#navigation li a` padding from 20px to 15px, that will fix it (except for sysadmins who get the Admin tab, but we can live with that).

I think all the changes in 9a54ae9529f91a7d733b254ac84528de944d8b4b can then be discarded.

**Comment by nikolai-b** [comment]
I don't experience any problem (I've selected all to show that the search isn't covered):

![Firefox](https://user-images.githubusercontent.com/6289830/57801825-90149a80-774c-11e9-8cd4-0819eda4ca07.png)

![Chrome](https://user-images.githubusercontent.com/6289830/57801838-999e0280-774c-11e9-8cc6-7cc207cf90bd.png)

Github has the search on the left, the advantage is that the group selector doesn't interfere with the search at all that way.  We could move the group selector to the left instead?

**Comment by nikolai-b** [comment]
Ah, sorry this is when your on a subdomain only!  I see now.  I'll fix it.

**Comment by nikolai-b** [comment]
Most Users: ![Screenshot from 2019-05-15 21-01-14](https://user-images.githubusercontent.com/6289830/57805435-c6eeae80-7754-11e9-9073-96f02606cbba.png) 

Committee: ![Screenshot from 2019-05-15 21-00-58](https://user-images.githubusercontent.com/6289830/57805444-d0781680-7754-11e9-8cef-7e196a70efe3.png) 

Admins: ![Screenshot from 2019-05-15 21-00-41](https://user-images.githubusercontent.com/6289830/57805466-de2d9c00-7754-11e9-9da7-602a73421176.png)

**Comment by mvl22** [comment]
Thanks; that should do for now.
