### ISSUE TITLE
Planning application link wrong (possible namespace clash)

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#675]
User report:

"I tried look at the planning applications and found a link to one at the end of my street in CH64 (Cheshire West and Chester) . I know its genuine since I was already aware of it. However when I click on the link it took me to a totally different application hundreds of miles away in Sheffield."

**Comment by mvl22** [comment]
Another example has come up:

```
Duplicate planning references need to be supported - e.g. 16/00391/FUL is a Basingstoke & Deane Borough Council planning reference, but if I search for it, I get this Angus request: https://cyclebasingstoke.cyclescape.org/planning_applications/uid/16/00391/FULL
```

This implies also that there isn't a unique index on the field, otherwise presumably Active Record (or whatever we're using) would have complained surely?

**Comment by nikolai-b** [comment]
Planning applications UIDs aren't uniq across LAs so I can't put a unique field on them
https://github.com/cyclestreets/cyclescape/commit/677af4a8d042f4550c5d5a64ed5a43dfeba7fcd6

I'd forgotten we were using the UID in the URL which I think is a mistake, if we just use our database ID then this won't be a problem.  If not then I guess we could do something like make the URL `/LA-NAME/UID` but that would be a shame as `LA-NAME` can change.  What are your thoughts?

**Comment by mvl22** [comment]
Yes, just prefix the URL with a lower-case version of the Local Authority name, in order to namespace these.

I'd definitely prefer that we don't reveal our own internal ID as LA + UID should already be unique and they are well-known tokens.
