### ISSUE TITLE
Edit Location not working

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#676]
When trying to save the edited location boundaries for my account I get an error message. 

https://camcycle.cyclescape.org/user/locations/1172/edit

Also, could improve the layout of location page. My intuition was to just click on the map and start moving the boundaries. Second was to click on add new location but that didn't really work out. Eventually, I worked out that instead, I had to scroll down beyond initial screen view and find something to click on. 
https://camcycle.cyclescape.org/settings/locations

**Comment by nikolai-b** [comment]
Thanks very much for reporting, I'd noticed these errors and fixed (I believe in https://github.com/cyclestreets/cyclescape/commit/49f03bc544 but it works in staging) a few days ago.

We are redesigning the location edit page entirely.  I'll open is up as a separate issue #678
