### ISSUE TITLE
Simple 'like' feature to like posts

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#677]
A user has suggested it would be nice to 'Like' a post, in `/threads/2120#message_33914`.

This is simply a thumbs up symbol, with a count. The user can undo by clicking again. Obviously a user can only 'like' once.

Same UI basically as the thumbs-up available in each icon on the map at:
http://www.urbancycleparking.org.uk/suggest/

I think this would be a fun but simple feature to add.

**Comment by nikolai-b** [comment]
To clarify, this is for messages only.  Would there be an email sent due to this?

**Comment by mvl22** [comment]
It would apply only to any kind of posting (e.g. message, photo, link, street view, library item posting) within a discussion thread listing.

It would not apply anywhere else, e.g. not on an issue page, not on a library item itself, etc.
