### ISSUE TITLE
Merge user locations and make settings/locations and edit page

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#678]
From a comment in #676 and https://github.com/cyclestreets/cyclescape/issues/661#issuecomment-271191842.

It is possible to combine all the locations for every user and make users have only one location.
Then we can move the current edit page to be at https://www.cyclescape.org/settings/locations so there is no edit / delete option.

This would involve losing the category information but I think the simplification to the UI would be greater.

**Comment by jf1** [comment]
In future I'd like the ability to enable/disable notifications or view planning applications on a per-location basis. Would consolidating multiple locations into one prevent this?

Example scenario: I have locations for several areas in GM, but if I'm busy or searching planning apps then I'd (temporarily) like to use just one smaller location.

I expect consolidation would also make it harder for people to delete just one of their locations, eg if they have a new commute.

ps. FYI my locations page zooms to a single area that only combines two of my four locations. I can zoom out to see the others, but they're not easy to spot as the black outline doesn't stand out from the black dots used for city-centres, eg. I have a small location in Cambridge yet Coventry etc look almost identical
![image](https://cloud.githubusercontent.com/assets/4711363/21887497/07e33732-d8b8-11e6-9c23-3e0d6d53150c.png)

**Comment by nikolai-b** [comment]
> Would consolidating multiple locations into one prevent this?

Yes it would.
We don't have that feature currently so I guess its a case of balancing the desires to simplify the locations with the ability to add lots of customization.

> I can zoom out to see the others, but they're not easy to spot as the black outline doesn't stand out from the black dots used for city-centers

Thanks for that.  I've split it out into a separate issue.

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/b79ab5aa15b93cddb0419f20508d8b95e9466449
