### ISSUE TITLE
NewThreadNotifier sends new_user_location_issue_thread emails to admins

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#68]
https://github.com/cyclestreets/toolkit/blob/master/app/workers/new_thread_notifier.rb#L68 needs the same fix as in https://github.com/cyclestreets/toolkit/blob/master/app/controllers/message_threads_controller.rb#L73

**Comment by nikolai-b** [comment]
Closing as I don't think this is still an issue.

**Comment by mvl22** [comment]
Yep, no such e-mail coming through, so presumably fixed long ago.
