### ISSUE TITLE
Invitations API

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#683]
Asking on the off-chance something may have been done in this area...

At present we (Camcycle) send out Cyclescape invitations when someone ticks the box on our membership form. We do this manually. If there were an API to do this, we could automate it in our membership database. Without it, it's one of the more complicated manual jobs to do when enrolling someone.

If there is an API now that would support this, could you point me at the documentation. If not, can you consider this a feature request.

Thanks,
David

**Comment by jf1** [comment]
+1 from GMCC

**Comment by nikolai-b** [comment]
@davidearl would this fit your workflow?

You send an POST to `api/login` with the JSON body of
```json
{"email":"user@example.com","password":"pa33word"}
```
and you'd get an API token (APITOK) for that user valid for x hours.

Then you could make a POST to `api/memberships?token=APITOK` with
```json
{"email":"recently_joined_user@example.com","role":"member","full_name":"Jo Doe","group":"camcycle"}
```
then if you were not a committee member we'd return an error,
if we had a user in Cyclescape with that email we'd make them a member of camcycle,
if there was no member we'd create one and send the standard invitation email.  I believe this mimics the current implementation:

![screenshot from 2018-11-18 20-02-12](https://user-images.githubusercontent.com/6289830/48677433-e83b5d00-eb6c-11e8-98a1-e06797f55b83.png)

**Comment by davidearl** [comment]
Yes, that would do the job, thank you.

I’m a bit nervous of having the password in there. Most apps would do this by provinding an API token in the UI. On the other hand I think we will use an account that is only for this purpose.

Just for the record, this doesn’t just apply for Camcycle, it’s for any grou; group in the call seems to satisfy that,.

This has the potential to automate one of the more significant manual tasks we currently have to do.

**Comment by davidearl** [comment]
Please could the login response be JSON (even if just as JSON string) rather than text payload. It would be helpful if the second request also returned a valid JSON payload, even if success is a 200 http response, just something like “ok” (with quotes) or {“status”:”ok”}

**Comment by mvl22** [comment]
Yes, the API is JSON-based, and should indeed be serving formatted correctly with the right HTTP status, exactly as you suggest.

**Comment by nikolai-b** [comment]
I am reluctant to create API keys that do not expire (hence the login endpoint) but given it has very limit usage then I will put it in the UI, probably only for committee members on 

Yes this is a JSON API so it will return valid JSON, I didn't specify it above but how about:

```JSON
{
  "status": "success",
  "data": null
}
```

**Comment by davidearl** [comment]
> I am reluctant to create API keys that do not expire (hence the login endpoint) 

Well, it's pretty universal in APIs I've used from big and small providers. The point is that it isolates the API from a standard login (potentially restricting what an API can do), avoids 2FA problems, means you can revoke the API access independently of the account password, and perhaps most important, doesn't require the account credentials to be stored in plain text in a third-party system.

There's no reason you couldn't have a similar API request to the login one to obtain a time limited token though I'm not sure what is gained by that. It goes over https, so it's not going to get intercepted anywhere.

Anyway, it doesn't make any difference to me particularly if you want to do it with a password.

> Yes this is a JSON API so it will return valid JSON

Thanks. Yes that's fine. JSON is helpful even when no payload is strictly necessary as I already have library functions that get valid from a JSON API which I can leverage. (I know it's not hard, but I can avoid proliferating similar cURL calls for slightly different cases).

**Comment by mvl22** [comment]
> I am reluctant to create API keys that do not expire

Like David, I don't really see a problem here. We have this in the CycleStreets API. If a key gets abused, or the keyholder doesn't want it any longer, they should be able to delete it.

**Comment by davidearl** [comment]
I started trying this, but I guess you're now working on api keys looking at the code changes last night. (I get a 404 on https://www.cyclestreets.org/api/login ).

Please could you re-open this (I don't seem to be able to myself) until it is available in the live version, so I get to know when I can use it (I'm ready to almost immediately).

Also, where will the api key go in the /api/memberships request? Is it api_key in the payload? I assume we will get or set a key in the profile page for the account concerned, yes?

Also, in the payload for the /api/memberships, are you expecting a JSON object as the entire POST content, or does the above indicate POST params named email, full_name etc?

**Comment by nikolai-b** [comment]
@mvl22 this is in staging, when you can review https://github.com/cyclestreets/cyclescape/pull/800 then I can push it live.

**Comment by nikolai-b** [comment]
> Then you could make a POST to api/memberships?token=APITOK

I altered it to be a POST to `api/memberships?api_key=APITOK`, sorry.  When this is live you will see your api key when your logged in and visit `api/`.  @mvl22 is this a sensible use case for staging or do we want to keep that clean?

**Comment by davidearl** [comment]
If you have a staging version I can test against, that would be great.

I'll modify my code to work with api_key.

Re my query above, is the POST of a single JSON object payload? Or several POST params (multi-part/form-data)?

**Comment by mvl22** [comment]
> @mvl22 is this a sensible use case for staging or do we want to keep that clean?

I'm quite happy that David and anyone else who is developing API integrations be given password access to use the staging server as a PLAY environment.

**Comment by davidearl** [comment]
Can you tell me where you are with this now? Is it in staging, and if so could I have an account on there which allows me to make invitations, so I can test my end? Or is it now in live?

**Comment by nikolai-b** [comment]
Hi @davidearl there is a changelog on the site you can get to from [What's new?](https://www.cyclescape.org/pages/changelog) link at the bottom of the page which will let you know when new changes are made live.  I'll try to remember to notify you when it is in live.  As this is in staging I'm going to close this issue.  

@mvl22 I'd prefer if we stick with your comment https://github.com/cyclestreets/cyclescape/issues/445#issuecomment-195012144 and leave issues that in staging as closed.

Sorry I was very slow at reply about the staging account, I'd be excited to see it tested!

You can access staging here http://staging.cyclescape.org/ using the details here:

https://github.com/cyclestreets/cyclescape-chef/commit/c40567c28f6d4d4812af1953454fda84f81677cf#diff-746e6c67a0a1ae4268d70d8f12c3cd3dR328
(so staginguser and staging)

If you go to https://www.staging.cyclescape.org/api you will see your API key and you can see the documentation and if you click membership you are guided in making real requests.

**Comment by davidearl** [comment]
Thanks, you'll be pleased to know that worked from the Cameo UI with only a couple of minor corrections (mainly you said /memberships above, when it is /membership, but the documentation page is correct, and of course the URL to request from has to be https://staginguser:staging@... otherwise it doesn't get past the basic auth - I guess in your api test page it is doing the curl from the browser, so it is already validated: in any case, it isn't shown in the cURL command shown or the URL).

The only issue I noticed is that the validation link it sends is relative to www.cyclescape.org, not www.staging.cyclescape.org, so it doesn't work when you click it, but that's presumably a problem with your staging setup, not this API.

I am a little troubled by the invitation process in general and GDPR, but I'll add a separate issue for that.

Thanks for doing this, it will remove one of the remaining more time-consuming manual steps in membership enrolment. I look forward to it being in the live system shortly.

**Comment by mvl22** [comment]
> I'd prefer if we stick with your comment #445 (comment) and leave issues that are in staging as closed.

Yes, 'closed' should definitely mean 'implemented in code', even if not yet quite rolled out.

If there is any question as to whether code is rolled out, just check the "Version ref" link at the bottom, which shows where the live server is up to.

**Comment by mvl22** [comment]
> The only issue I noticed is that the validation link it sends is relative to www.cyclescape.org, not www.staging.cyclescape.org

That's almost certainly a bug - the site should be picking up the correct URL of its installation. Nikolai, can you check this over?

**Comment by nikolai-b** [comment]
@davidearl this is live now.
