### ISSUE TITLE
Getting page header/footer around the Library section

### ISSUE THREAD

**Issue by smsm1** [cyclestreets/cyclescape#686]
![st marys woodbridge road - cyclescape 2017-02-12 22-45-09](https://cloud.githubusercontent.com/assets/82719/22866881/eac0e052-f174-11e6-8ce7-4abc8aed8eb2.png)

Seems the partial that generates the Library section on the threads page (screenshot from https://cycleipswich.cyclescape.org/threads/3003# ) includes the main page header and footer.

**Comment by nikolai-b** [comment]
Thanks, that doesn't look good. I'm not able to reproduce this, would you mind adding steps to recreate it or is it just always there?  Are there any JS errors in the console?

**Comment by smsm1** [comment]
Odd, I'm not able to reproduce it just now. I'll reopen if I can find a way to reproduce.
