### ISSUE TITLE
User's last group should be memorised for next login

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#687]
If a user uses the group switching control, or follows a link to a different subdomain, this should be , remembered so that their next login should be to that subdomain.

Many complaints in person of users saying that they have to do this each time when they log in. (I know the subdomain can be bookmarked, but in practice that's less and less likely.)

Spec should be as follows:

1) At the point of login ONLY, if the URL is currently www, and if the user's last page impression (e.g. from last time they used the site) was a group (i.e. non-www subdomain), the user's URL should be redirected from www to this last group. E.g. user who had previous switched to the Camcycle group accesses www.cyclescape.org/issues, logs in, and they are then redirected to camcycle.cyclescape.org/issues.

2) Group switching and all other URL management remains exactly the same.

**Comment by nikolai-b** [comment]
I've tested this and the site currently does what you are asking for.
I logged in and switched the group to camcycle.  I logged out, changed the URL to https://www.cyclescape.org/, logged back in and was directed back to camcycle.  I change my group to ipswich, logged out, change url to https://www.cyclescape.org/, gged back in and was directed back to ipswich.

**Comment by nikolai-b** [comment]
@mvl22 does this not work for you?
