### ISSUE TITLE
When there are unread direct messages, the top-right icon should light up

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#690]
Currently, the top-right icon for accessing direct messages is always grey. Users have complained that they never look there.

If there are unread direct messages, the icon should be lit up. Maybe it should turn orange/yellow.

Ideally the number of messages would be shown in a red blob, but that can be a second stage of iteration if necessary.

**Comment by nikolai-b** [comment]
I've commited this to master (because of the state out the branches) but I'd like to check it out on staging first, if your happy we can deploy.

**Comment by mvl22** [comment]
I've just sent you a message at:
https://camcycle.cyclescape.org/threads/1852

This immediately resulted in (1) appearing in red.

The design for this all looks great, and clearly the functionality is working. But I think this should not show for the message that I've just sent out!

**Comment by nikolai-b** [comment]
Ah yes, I'd forgotten that would happen.
Should be fixed now.

**Comment by mvl22** [comment]
Thanks - do make live.

**Comment by mvl22** [comment]
Better now thanks!

Actually this showed me I had one unread message but it wasn't clear which. Should we apply the same colourings stuff to that list?
