### ISSUE TITLE
Ordering of people list is completely random

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#691]
The list of people on the right for a thread seems to be completely random.

Committee members should be listed first, followed by general members. There should be a very small (say 8px) line break between these two blocks (perhaps coloured light gray), but they should visually remain a single block.

This needs a sort algorithm therefore. It should be applied separately for the two blocks (Committee, general).

However, we can't assume that people have two or more name tokens in their name field.

A simple algorithm would be sort by the full name. But this is unusual as people are used to sorting by surname. However, this would be far better than the current random list.

A better algorithm would be:

1) Index by the start of the last token. E.g.:
"Foo Bar" would be indexed on "Bar"
"Foo Bar Zog" would be indexed by "Zog".
"James Smith" would be indexed by "Smith".
"John James Smith" would be indexed by "Smith".
"Woo" would be indexed by "Woo"

2) Sort by the last token index. If two items are the same, then sort by the full string. E.g. ordering of this set of names would be
"Foo Bar"
"Foo Bar Zog"
"James Smith"
"John James Smith"
"Woo"

**Comment by nikolai-b** [comment]
Are you sure about "Foo Bar Zog"? I would put that last.

**Comment by mvl22** [comment]
> Are you sure about "Foo Bar Zog"? I would put that last.

Sorry, yes, you're quite correct!

**Comment by nikolai-b** [comment]
I'm assuming leaders  are above committee members.
I'm also assuming that we are only interested in committee members of the thread's group (if the thread is owned by a group) and not if the thread is not owned by a group.

**Comment by mvl22** [comment]
> I'm assuming leaders are above committee members.

Yes, sorry for not being clear.

> I'm also assuming that we are only interested in committee members of the thread's group (if the thread is owned by a group) and not if the thread is not owned by a group.

Correct.

**Comment by mvl22** [comment]
Looks good.

Would be good if this could be cherry-picked into master, rather than being blocked behind other changes.
