### ISSUE TITLE
Have a floating link-to-top button in bottom-right

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#692]
Users can't find the link to top button.

Although this is symptomatic of a wider design problem, I think having a circle with an arrow giving link-to-top, fixed in the bottom-right as a fixed-position CSS item, would be helpful.

**Comment by nikolai-b** [comment]
With the floating nav do we still want this?

**Comment by mvl22** [comment]
Yes, I think so. I still find myself needing to scroll to the top sometimes to see some details, though a lot less.
