### ISSUE TITLE
Add CSV option to Issues API

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#699]
As at https://github.com/cyipt/cyipt/issues/23:

We need to add a CSV renderer option, as an alternative to JSON and XML.

**Comment by nikolai-b** [comment]
The output is currently GeoJSON, are you sure you want CSV? @Robinlovelace 

Also, sorry the API docs are down but fixed in ad9f178093e

Normally you can get to them via https://www.cyclescape.org/api

**Comment by Robinlovelace** [comment]
GeoJSON is better imo from 1st impressions. Example dataset would be gr8 : )

**Comment by smsm1** [comment]
For some cases, such as taking the list into a spreadsheet for further manipulation or including in a report the CSV would work better.

**Comment by nikolai-b** [comment]
@mvl22 if @Robinlovelace is happy with CSV do we need this still?
The doc page has a place where you can see the options we support
https://www.cyclescape.org/api#!/issues/getApiIssues
and will give the responses

**Comment by Robinlovelace** [comment]
For people wanting CSV we could recommend this site: http://www.convertcsv.com/geojson-to-csv.htm

**Comment by nikolai-b** [comment]
I don't think we need to offer a CSV and GeoJSON, there are many tools to convert down to CSV but please re-open if you think I should add this.
