### ISSUE TITLE
Can't read a thread I should have access to

### ISSUE THREAD

**Issue by sam-7** [cyclestreets/cyclescape#702]
When trying to access https://www.cyclescape.org/threads/1044 I get a 'not authorised to access that page'.  It says it belongs to Cambridge Cycling Campaign and gives a link to request membership.  I'm already a member and trying to request membership confirms that.

Not a lot more debugging I can do without DB access.  Looks like others may have the same issue i.e. it's something about that thread - https://www.cyclescape.org/threads/1518#message_18193

**Comment by mvl22** [comment]
The thread you note is set to be Committee-only, so the system is correctly preventing access.

**Comment by sam-7** [comment]
Thanks for looking into it so quickly.  Perhaps the error message could be changed in these cases not to say 'would you like to join group XXX'?

________________________________

**Comment by nikolai-b** [comment]
Fixed in staging as:
![screenshot from 2017-04-11 23-36-18](https://cloud.githubusercontent.com/assets/6289830/24933728/be26d222-1f0f-11e7-8361-eee608db4dea.png)
(not yet in live)
Thanks for reporting.

**Comment by sam-7** [comment]
Great.  Thanks for being so responsive
