### ISSUE TITLE
Planning application search should be integrated into main search

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#704]
More user feedback that there is confusion and extra work created by having two separate places to search for a planning application.

The main search should add a 4th tab, so that a search in the main box picks up this search.

The existing planning application search box can remain if needed, though ideally if there is some way to integrate the two, e.g. by having that submit to the main search and have the 4th tab automatically switched-to, that would also be fine.

**Comment by mvl22** [comment]
Just to flag up that, in writing issue number 715 it's clear that the search box is easy to be confused with the main search.

**Comment by mvl22** [comment]
Is this now implemented and in `master`? Compare these two result screens, for the same:

https://camcycle.cyclescape.org/overview/search?utf8=%E2%9C%93&query=17%2F1023%2FFUL&button=

https://camcycle.cyclescape.org/planning_applications/search?utf8=%E2%9C%93&q=17%2F1023%2FFUL&button=

Would be good if we can get this live.

**Comment by nikolai-b** [comment]
It is waiting on your :+1: see #717
