### ISSUE TITLE
Double issue listing

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#712]
I'm seeing a few threads listed twice in my My Cyclescape:

![screen shot 2017-04-24 at 14 59 05](https://cloud.githubusercontent.com/assets/361423/25349774/e1c35998-291a-11e7-91a2-9a53c6e7d701.png)

The link to each pair goes to the same place.

I assume this is presumably somehow related to the double e-mailing problem.

**Comment by mvl22** [comment]
I believe this was fixed in: ca418099cf2cee0065bde43c12380d9d1b66b60f

Nikolai, can you confirm whether the query here is safe though, as the Czech guys could get caught by this?

**Comment by nikolai-b** [comment]
Thanks,  I'll fix that migration.
