### ISSUE TITLE
New threads getting stuck in moderation causing much confusion

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#713]
Every new thread creation is resulting in a 500.

What happens is:

1) User creates issue (which works fine, if you work out what the URL would be)
2) The new thread form comes up, with the issue details cloned.
3) User submits new thread form.
4) 5-10 second wait.
5) Error 500 page appears. Thread is not created, so the issue remains an issue with no threads visible to ordinary users.
6) The new thread is shown in the Admin moderation list.
7) E-mail goes out to users (which shouldn't be happening, because in theory it's in moderation)
8) Users who read their e-mail quickly follow the link in the e-mail and they get a 404. This is obviously highly confusing.
9) Once the Admin moderates the thread message, everything is fine, and obviously the link present in the e-mail works because the thread is now present.

The priority is definitely working out why new threads always get put into moderation. Presumably this is then causing the error 500 page.

**Comment by nikolai-b** [comment]
@mvl22 I believe this is fixed but please re-open if I'm mistaken.
