### ISSUE TITLE
Release cleanups from #717

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#723]
Cleanups from release #717:

- [x] Need to update What's new list
- [x] Site footer has incorrect set of images - need to match earlier list
- [x] Planning applications tab in search should not use American Capitalisation

**Comment by nikolai-b** [comment]
@mvl22 You can update the images in admin -> site config.
I'll update the "What's new" and the capitalisation.

**Comment by mvl22** [comment]
Thanks; footer now confirmed same as before. I've updated some of the links.

**Comment by nikolai-b** [comment]
Done in 9e5f7f86 and f10268f1
