### ISSUE TITLE
Thumbs up shows 'Anon' in threads where participants are identified

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#724]
Hard to use for approvals etc if a person can not be identified.

**Comment by roxannedebeaux** [comment]
Problem has now changed and appears as in the picture attached. 
<img width="483" alt="screen shot 2017-07-12 at 11 06 05" src="https://user-images.githubusercontent.com/11997264/28112776-321c65e6-66f2-11e7-95b2-bbd87bb8c840.png">

**Comment by mvl22** [comment]
Nikolai - the point here is that "and others" isn't helpful. Just list everyone, preferably split by line break rather than comma-space.

**Comment by mvl22** [comment]
Great, thanks!
