### ISSUE TITLE
Emails truncated at dashes, not just correct footer separator

### ISSUE THREAD

**Issue by wookey** [cyclestreets/cyclescape#728]
Sending a mail containing several dashes on a line (definitely 8, maybe fewer) causes all the text below to be discarded and not appear in the thread. This is presumably due to a sloppy search for a proper footer separator which is
dash-dash-space alone on a line.

Whilst it's true that these days people do not necessarily have a correct footer separator, 
It's better to include some footers sometimes when people get the separator wrong, than it is to throw away part of a mail because it has a row of dashes in it, so this test should be more explicit.

**Comment by nikolai-b** [comment]
The library we use has treats:

https://github.com/github/email_reply_parser/blob/master/test/emails/email_2_1.txt

as a signature which I believe it is doing correctly.  Yes, emails are truncated at dashes and I can fix that but it looks like that will mean outlook replies will not be identified as footers.

Not sure what to do with this one, sorry.

**Comment by wookey** [comment]
On 2017-11-01 22:48 +0000, Nikolai wrote:
> The library we use has treats:
> 
> https://github.com/github/email_reply_parser/blob/master/test/emails/
> email_2_1.txt
> 
> as a signature which I believe it is doing correctly. Yes, emails are truncated
> at dashes and I can fix that but it looks like that will mean outlook replies
> will not be identified as footers.

Hmm. I see your problem. Bloody Outlook and its disregard for email standards.

> Not sure what to do with this one, sorry.

Does it in fact use ------<space>?

If it did then truncating rows of dashes with a space on the end would
work for both outlook replies and the long-standing footer-separator
(but not 'row of dashes in mail').

But if not, then yes on balance massive long appended previous mails by
outlook (and other mailers that have copied that interface) are a lot
more common than genuine bits of mail with some dashes in, so this
behaviour does make some sense.

Wookey
-- 
Principal hats:  Linaro, Debian, Wookware, ARM
http://wookware.org/

**Comment by nikolai-b** [comment]
Sadly I think this is going to be a "won't fix".
