### ISSUE TITLE
Database read-only / offline modes

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#73]
Is it worth having database offline and read-only modes, like OSM has?

These are a central configuration change that changes the behaviour of the site. When in read-only mode all the pages are displayed but no updates are permitted (useful when migrating databases around), in offline mode you get splash screens instead.

**Comment by gravitystorm** [comment]
What do the current ops team think of this? Have there been any related problems during the last few years? If not, we can close this issue.

**Comment by mvl22** [comment]
I think this is useful to keep in the issue list for implementation at some point, but not a priority.

At present the level of usage of the site isn't so critical that taking it offline completely for an hour late at night to perform a server migration is too problematic, but that day will come.

**Comment by gravitystorm** [comment]
I think it's better to close this issue - there's a million 'nice to haves' possible, but if there's no actual need to implement it it's not worth managing an open ticket about it.

I'm sure if the need arises in future, we can open another ticket!
