### ISSUE TITLE
Need ability to search by # tag

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#730]
There is now the functionality to use tags in Cyclescape however, finding a list of where those tags have been used is very difficult unless you can find one of the tags to click on. E.g. searching for "#newsletter" shows every reference to "newsletter" without differentiation. It renders the new feature almost pointless if you can't get to it. (But if I could get to it then it would be very useful) Can there be a way to easily get this list?

Could there be a way to get notifications within Cyclescape when hashtags you are following are used?

**Comment by mvl22** [comment]
Yes - good point - currently there is no obvious way to get to these.

There is an index at:
https://camcycle.cyclescape.org/hashtags

but this is not currently linked to from anywhere.

There should indeed be a search tab for this new feature.

**Comment by roxannedebeaux** [comment]
Or perhaps allow search in the search box using # in front of the word to
differentiate?

Thanks for that link. It's a good start for me and I will try to get some
key users to look there as well.


Kind Regards,

Roxanne De Beaux
Cycling Campaign Officer

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138090*
