### ISSUE TITLE
Group profile edit crash

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#732]
Submitting an update at: `/groups/57-icag/profile/edit` gives an error 500.

As reported by a user to @georgio8

**Comment by mvl22** [comment]
@nikolai-b Could you prioritise this amongst other tickets please? I suspect this is probably a quick fix but blocks groups getting going.

**Comment by jonacaz** [comment]
I am the user. Let me know if you need me to recreate, retest etc.

**Comment by mvl22** [comment]
@jonacaz Thanks!

It's reproducible just by pressing submit.

**Comment by mvl22** [comment]
@nikolai-b Can we merge this and the other recent changes to master?
