### ISSUE TITLE
Password reset timeout is too short - users can be locked out permanently

### ISSUE THREAD

**Issue by wookey** [cyclestreets/cyclescape#736]
A friend has been unable to use cyclescape for months/years because:

I can't log on , as it requires a password reset, which takes about 2 hours to get to me, and I have to do
within an hour.

Can we please extend the timeout to something more reasonable like 24 hours. 1 hour is ridiculous. Standard greylisting gives a 45-min delay for new mail sources, for example.

**Comment by mvl22** [comment]
Urgh, I never realised there was a time limit (it's a default in the library, Devise, we are using). 2 hours is the value and this is a ludicrous default. Thanks for the bug report pointing this out.

https://github.com/cyclestreets/cyclescape/blob/master/config/initializers/devise.rb#L168

I'll change this now.

**Comment by mvl22** [comment]
@wookey Can you ask your friend to try again now?
