### ISSUE TITLE
Datepicker in wrong place

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#75]
On the staging branch, the deadline message date picker is appearing in the wrong place (below the footer) since the top css attribute isn't being set.

git-bisect pin-points 16d449f3ba9c652caaa and simply changing jquery-rails back to 2.0.2 fixes it. Updating jquery tools (in vendor/assets) to 1.2.7 doesn't appear to fix things.

Needs fixing before the next deployment.

**Comment by nikolai-b** [comment]
done in #406
