### ISSUE TITLE
Committee thread allowing non committee members to access

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#756]
I've noticed that a thread labelled 'committee only' currently has a few non-committee members subscribed and at least one of those members has been able to participate in the thread. 

https://camcycle.cyclescape.org/threads/548

I removed committee members who have recently left the committee and found that their names were removed from the thread list, however, the older names are still on it.

**Comment by mvl22** [comment]
@nikolai-b I think we are missing a trigger for when a person is removed as a Committee meeting, in that it needs to go through all existing threads to check their membership and remove them if necessary.

**Comment by nikolai-b** [comment]
I tried to re-create this but I can't.  I can see that two users were removed from the camcycle committee.  One at Tue, 02 Jan 2018 18:01:23  and they were removed from the thread at Tue, 02 Jan 2018 18:01:24 (so one second later).
The next was removed at Tue, 02 Jan 2018 18:01:41 and they were removed from the thread at Tue, 02 Jan 2018 18:01:42 (again, one second later).

The code is
https://github.com/cyclestreets/cyclescape/blob/staging/app/models/group_membership_observer.rb#L18
and the tests are
https://github.com/cyclestreets/cyclescape/blob/staging/spec/models/group_membership_observer_spec.rb#L50-L67

**Comment by nikolai-b** [comment]
Oh, sorry this is for older members.  In that case would you mind sending details to @mvl22 privately and I can look more at it.

**Comment by nikolai-b** [comment]
I'm closing this as we've changed quite a few of these gems.  If you can find an example of it happening again please re-open with the extra information.

**Comment by mvl22** [comment]
That particular thread still has old Committee members on it. At the very least, the action here is to normalise all threads to be the correct memberships, fixing up the effects of since-fixed bugs.

**Comment by nikolai-b** [comment]
Done.  I found 13 more cases like this and I've deleted these subscriptions.  If there is another problem please open a new issue.

```ruby
MessageThread.where.not(group_id: nil).where(privacy: "committee").map { |mt| mt.subscribers.joins(:memberships).where(group_memberships: {group_id: mt.group_id, role: "member"}).pluck("thread_subscriptions.id") }.flatten
```
