### ISSUE TITLE
Show planning applications

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#76]
There is a planning application branch, which needs rebasing and finishing off.

The user interface is, if I recall, functionally complete - the parser and cron tasks for processing the planning application feed needs finishing.

The limitation of the current approach is that it requires downloading, reparsing and check/update/insert on all ~2 million planning application records every evening. If upstream now have a "records changed this hour/day" feed like OSM does, then we should use that instead. The vast majority of the records are unchanged each day, and parsing them all is a multi-hour process.

**Comment by mvl22** [comment]
The GUI work is all in place. Here are screenshots of it:

1: Any member of the site can view list of planning applications matching their area(s) of interest,
shown most recent first. Each application has a page of its own.

![1 - listing of planning applications](https://cloud.githubusercontent.com/assets/361423/6204193/db95641e-b539-11e4-8c58-3eea4c28d433.png)

2: That application page has full details

[No screenshot available.]

3: On the page is a 'Convert to an issue' button:

![2 - convert to an issue button](https://cloud.githubusercontent.com/assets/361423/6204197/f5ea5cb6-b539-11e4-81f9-66597f37cf92.png)

4: The data is cloned into the standard ‘New issue’ form:

![3 - application cloned into new-issue form](https://cloud.githubusercontent.com/assets/361423/6204198/01aa4f5c-b53a-11e4-9607-45c6016d9f13.png)

at which point it can be submitted then like any other issue.

**Comment by nikolai-b** [comment]
in master now!

**Comment by mvl22** [comment]
You are awesome, Nikolai :)

And so is Andy for getting this all started off so brilliantly!
