### ISSUE TITLE
Unable to copy text from previous Cyclescape posts

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#761]
Something is preventing selection/highlighting of text from Cyclescape threads. I use this numerous times a day (tried twice already this morning) so I hope this can be fixed asap.

**Comment by mvl22** [comment]
I can reproduce the problem on Win/Chrome.

@nikolai-b Can you scrutinise the Map message type javascript to see if it is causing some kind of problem?

**Comment by nikolai-b** [comment]
Any better? I've not be able to recreate on Chromium on Linux but I've reverted a possible cause.

**Comment by roxannedebeaux** [comment]
No, it's still not working for me in Firefox.


Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138098*

**Comment by nikolai-b** [comment]
I might need some help with this one as it works on my computer:

![screenshot from 2018-02-24 10-55-41](https://user-images.githubusercontent.com/6289830/36629694-6f8f5138-1951-11e8-9d71-343ac3c6c927.png)


Can you tell me the what version of Windows and the Chrome or Firefox version?  
Also do you get any errors in the console?

**Comment by mvl22** [comment]
I *think* this is happening only while signed in. I've tried several times just now and reproduced that in all but one case (though that might be because of a caching issue, thinking back).

There are no warnings in the console.

**Comment by nikolai-b** [comment]
@mvl22 thanks, this means we can't select polygon drawing as standard.  I've added some help text:

![screenshot from 2018-02-24 14-49-29](https://user-images.githubusercontent.com/6289830/36631543-f7e5cd30-1971-11e8-8a84-19aed8f530c4.png)

Are you ok with this?

**Comment by mvl22** [comment]
Yes, clearly selectability of text is way more important - please do make live ASAP.

However, I'm not sure why this shouldn't be possible - do you have an idea of actually why it was failing?

**Comment by nikolai-b** [comment]
Yes I believe this is how leaflet draw works, see

https://jsfiddle.net/rzhfm7us/3/

Which is copied from the leaftlet demo http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

At first you can select the text but if you click on the polygon (or any other edit button) then you cannot select the text.
