### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#762]
Our SSL certificate will not work in Chrome versions greater than M70 as Chrome plans to distrust Symantec:

https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

I believe that gives us till ~ October 23, 2018 but maybe we could rethink this anyway and use Lets encrypt as they were due to support wildcard certs in a few days: https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html
It looks like they are delaying but I presume it will be ready in a few months so enough time to use that instead of buying another certificate.

@mvl22 any thoughts?

**Comment by mvl22** [comment]
Well, it expires on Tuesday, 4 December 2018 anyway, so we'd be replacing it about that time.

I suggest we look at this further once Let's Encrypt have their long-awaited wildcard cert system in place.

**Comment by mvl22** [comment]
@nikolai-b Just to flag that actually we've little time on this now. I understand Chrome 70 is about to be released any day, so we need to act quickly.

How easy is it to get Let's Encrypt into the deployment system? Presumably someone must have written a Chef package for this?

**Comment by nikolai-b** [comment]
@mvl22 with Wildcard cert turns out it is web hosting company specific...

https://www.mythic-beasts.com/support/domains/letsencrypt_dns_01

> If you have a hosting account with us, you don't need to follow this guide. Support for Let's Encrypt is fully automated for hosting accounts, and you can enable a certificate for your website using our control panel.

Do we? Otherwise I can go about making a custom chef script.

**Comment by mvl22** [comment]
> Do we? Otherwise I can go about making a custom chef script.

They are referring to hosting using preset Apache/etc. stuff. They have created scripts that hook into their setup for that kind of simple hosting. By contrast, we are using our own VM fully under our own control. So we do have to do this ourselves.

**Comment by mvl22** [comment]
Looks like we need Certbot 0.22 or later:

https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579
https://letsencrypt.org/docs/client-options/#acme-v2-compatible-clients

Looks like the `ppa:certbot/certbot` PPA does have a version of this available for Ubuntu 14.04:

https://launchpad.net/~certbot/+archive/ubuntu/certbot

**Comment by nikolai-b** [comment]
@mvl22 I don't think certbot is the best way to do this as it requires us modify DNS TXT record.

https://www.mythic-beasts.com/support/domains/letsencrypt_dns_01 also has manual instructions which I've made into an PR on the chef repository.

**Comment by mvl22** [comment]
I don't entirely like the idea that we're embedding a specific registrary's DNS API implementation into generic software - surely DNS TXT records are the standard way to do this, and would be expected for anyone wanting to set up any kind of wildcard SSL if they use Let's Encrypt?

**Comment by mvl22** [comment]
Anyway, let's focus on getting this live as soon as it's working. Do push this live when you're happy, as Chrome 70 is arriving any day now. Let me know if you need any info.

**Comment by nikolai-b** [comment]
@mvl22 cyclescape.org is using a lets encrypt wildcard SSL certificate.

I've added a cron job https://github.com/cyclestreets/cyclescape-chef/blob/master/local-cookbooks/letsencrypt/recipes/default.rb#L78-L88 but I've been bitten by cron running with different `ENV` so although I've tested it I'm not sure it works till it actually runs and works.

We are due to renew 30 days before the cert expires (20 January 2019), so we should get a new cert on 22nd of Dec.  I'll add a calender notification to double check it worked.

**Comment by mvl22** [comment]
Awesome, nice work!

https://www.ssllabs.com/ssltest/analyze.html?d=cambridge.cyclescape.org&hideResults=on
https://www.ssllabs.com/ssltest/analyze.html?d=www.cyclescape.org&hideResults=on

That's giving us an A rating.

In 6ea03df8404c9abb4462d75ec92f8fa4359beb91, can that `find` call be tightened up to search only in particular places? We don't want it to pick up some random cert left somewhere.

**Comment by nikolai-b** [comment]
@mvl22 https://github.com/cyclestreets/cyclescape-chef/commit/6ea03df8404c9abb4462d75ec92f8fa4359beb91 is only searching in one place as the `#{File.join(dehydrated_cert, "cyclescape.org")}` is the folder.  It expands to:

```sh
/usr/bin/find /var/lib/dehydrated/certs/cyclescape.org -mmin -300 -name "*.pem" -ls
```

**Comment by mvl22** [comment]
Ah, OK, thanks.

Great to have this all sorted.
