### ISSUE TITLE
Linebreaks not appearing in posted text

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#764]
I type a comment with line breaks and some disappear while others don't. I think it is a problem when there is one linebreak but seems to be fine when there are two. You can see in the attached image that the - show where there were meant to be a list of points which have appeared as one paragraph, but the separate paragraphs (two line breaks) have come through fine. This is for comments typed directly into Cyclescape.

**Comment by roxannedebeaux** [comment]
<img width="591" alt="screen shot 2018-04-13 at 17 15 03" src="https://user-images.githubusercontent.com/11997264/38746191-b2f93250-3f3e-11e8-9091-b63770c4e448.png">

**Comment by roxannedebeaux** [comment]
This issue is still causing a high number of my posts to be formatted incorrectly making it difficult for people to understand what is being said.

**Comment by nikolai-b** [comment]
Very sorry this took so long.

**Comment by mvl22** [comment]
Thanks for fixing that.

Can you confirm that the br will create only a single line break, rather than a spacing between also?

**Comment by nikolai-b** [comment]
![Returns and line brake](https://user-images.githubusercontent.com/6289830/41554298-5cb8244c-732c-11e8-8d67-348b37548111.png)

This is a view change so existing messages will be represented differently after this goes live.

**Comment by mvl22** [comment]
That looks correct now.

> This is a view change so existing messages will be represented differently after this goes live.

Yes, I don't suppose there is anything we can do about that really.
