### ISSUE TITLE
Thread page is very slow

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#768]
E.g. thread 1858 takes 8 seconds to appear. Again, can we analyse what is causing the problem here and tighten up SQL or anything else inefficient?

**Comment by nikolai-b** [comment]
It has over 650 messages! I've made it a bit faster but really we'd need pagination to make it fast.

**Comment by mvl22** [comment]
> It has over 650 messages!

But this is just simple text. Are you able to profile what is taking the time - is is the database lookups (which I suspect) or the rendering time in the browser?

Retrieval of 650 text messages from an SQL database of the size we have really should not take more than a fraction of a second.

**Comment by nikolai-b** [comment]
The SQL isn't taking too long, the view rendering etc. is.  Each rendered message is not dumped SQL onto the page it is generating.  Locally with loading voting via AJAX the SQL takes ~200ms and the HTML rendering (which is ~ 1.8Mb) takes 12s.

I can investigate but really it looks like a case of 650 * a small time = a large time.
