### ISSUE TITLE
Autofill option in date field covering calendar

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#774]
I am unable to put in deadlines as the autofill option is covering the calendar. This is in Chrome. 
![screen shot 2018-06-12 at 12 59 34](https://user-images.githubusercontent.com/11997264/41289177-cfe7e3b2-6e40-11e8-8d99-f254c677bb82.png)

**Comment by mvl22** [comment]
@nikolai-b I think this just needs `autocomplete="off"` added to that input field - see on MDN:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by mvl22** [comment]
Thanks.
