### ISSUE TITLE
Message for a posting in moderation is inaccurate

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#775]
A new user states:

"I have posted messages on 2 threads and get the message 'New threads can only be automatically created by approved users. It is queued to be checked by a moderator.' - but I am not creating a new thread."

**Comment by nikolai-b** [comment]
@mvl22 what text would you like?  Something like:

> Very sorry but as you are a new user this message is being held in a queue to be checked by a moderator.  Once approved no future messages will be held.

**Comment by mvl22** [comment]
Let's just go with:

"This message has been temporarily held in a queue to be checked by a moderator, as you are a new user."

**Comment by mvl22** [comment]
Ah sorry, I think the problem was that the user was getting that message when they posted to an *existing* thread - the problem is that they then get a message about a new thread.

**Comment by nikolai-b** [comment]
I'm a bit lost.

The user posted to an _existing_ thread.  They received

> Very sorry but as you are a new user this message is being held in a queue to be checked by a moderator. Once approved no future messages will be held.

We've changed that so now if they posted they'd receive:

> This message has been temporarily held in a queue to be checked by a moderator, as you are a new user.

What is the bug now?

**Comment by nikolai-b** [comment]
We've made a few changes, if this still happens would you mind opening up a new issue?
