### ISSUE TITLE
Unnecessary 'leave site' pop up appears every single time a Cyclescape page is 'left'

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#779]
![screen shot 2018-07-24 at 12 30 22](https://user-images.githubusercontent.com/11997264/43141460-d9bfb8d2-8f4d-11e8-83ec-2f6f3a303fa7.png)
![screen shot 2018-07-24 at 13 19 26](https://user-images.githubusercontent.com/11997264/43141461-d9db392c-8f4d-11e8-9d2d-0ebafb780a86.png)

**Comment by mvl22** [comment]
@nikolai-b Can you revert the relevant change ASAP - thanks.

**Comment by nikolai-b** [comment]
Fixed in 3a9f98c2, very sorry about that

**Comment by mvl22** [comment]
Thanks for fixing this quickly :)
