### ISSUE TITLE
Cyclescape freezes on mobile browser when backspace is used

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#780]
Seems to happen nearly every time I try to backspace for more than 2 or three characters. Freezes sometimes for a minute or more, usually for a frustrating 5 or 10 seconds, if I don't realise this results in a mess of text. I don't think this is my mobile as this does not happen in any other app or website. 

I use Cyclescape on my mobile a lot so issues like this make it very difficult to get on with my work.

**Comment by mvl22** [comment]
I have noticed that textbox performance does seem unusually bad on iOS Safari compared to other sites, though others are not always perfect.

Is it possibly a character count or some other monitoring javascript interjecting constantly.

**Comment by nikolai-b** [comment]
Sadly there isn't anything I know of checking the textbox.  I think this might need a very detailed performance report for me to have any idea where to start looking.  Does this happen on all message threads or only on large ones?  Is it effected by the number of subscribers?  Has this always happened or has it started (and if so when)?

Would you mind seeing if any suggestions from https://www.google.co.uk/search?q=ios+safari+freezes make any difference?

Sorry I know that isn't entirely helpful!

**Comment by nikolai-b** [comment]
We have changed a few things since Oct and there are performance improvements in the pipeline so I'm closing this.  If there are still issues please re-open but it would be very useful if you also answer some of my questions above.

**Comment by roxannedebeaux** [comment]
Sorry Nikolai, I do my best but user testing is not part of my job
description and I have more work than I can handle day-to-day. I don't have
a programming background so I don't always know how to explain what is
happening.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *
camcycle.org.uk/donate <https://www.camcycle.org.uk/membership/donate/>
*Charity no. 1138098*

**Comment by nikolai-b** [comment]
Thanks Roxanne, I really welcome your bug reports!  No pressure time-wise, just that there are somethings I spend a long time trying to re-create and I can't.  Sorry I couldn't fix it but do re-open with an example or two if it happens again.
