### ISSUE TITLE
Switching network on phone causes loss of login

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#781]
A user has reported that if they go from e.g. wifi to 3G then they lose the login and have to log in again.

Does the login system do any linking of the IP to the session? If so, that is clearly inappropriate these days, as people's connection does change in a way that didn't use to happen in pre-mobile days.

**Comment by nikolai-b** [comment]
We do not use IP address but [30 minuets](https://github.com/cyclestreets/cyclescape/blob/staging/config/initializers/devise.rb#L132-L135) of inactivity will cause the user to be signed out.
