### ISSUE TITLE
Performance poor

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#782]
The performance of the site is quite poor at the moment - could you have a look and see if any code improvements can be made? It does seem to have worsened quite a bit in the last month.

@nikolai-b Could you treat this as a high-priority ticket when you next start working on things.

**Comment by nikolai-b** [comment]
@mvl22 could you add more detail?  Is it poor on all pages?  Is it poor all the time?  I've checked the CPU and memory and they seem fine.  Also I've tried a few threads and can't say I've noticed it being much slower, maybe I should add some load time metric...

**Comment by nikolai-b** [comment]
Closing in favour of https://github.com/cyclestreets/cyclescape/issues/844
