### ISSUE TITLE
Upgrade OS, postgres and postgis 

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#789]
We are on Postgres 9.3 which is [EOL](https://www.postgresql.org/support/versioning/) in September 2018.  Upgrading to 9.6 is not that hard but will need a few minuets of downtime.  Sadly I've no idea how to automate the upgrade in chef.

1. Install the new postgres version (9.6) and postgis version (2.3) in the [postgres recipe](https://github.com/cyclestreets/cyclescape-chef/blob/1ca68bde0656a47cac00b68c78cd142b93de8c1b/local-cookbooks/postgres/recipes/default.rb)
2. Remove the [redundant](https://github.com/rgeo/activerecord-postgis-adapter/blob/a2862d19b945ab7f951f48c57fedb63617d202e6/History.md#202--2014-06-06) `script_dir` [[0](https://github.com/cyclestreets/cyclescape-chef/blob/515c3fecc4b8cad6f50fc30112212973a9af5e02/local-cookbooks/cyclescape/recipes/default.rb#L97)] [[1](https://github.com/cyclestreets/cyclescape-chef/blob/96b169d7320f5c98fa2cd45f2bed51552b04f846/local-cookbooks/cyclescape/templates/default/database.example.yml#L7)] etc.
3. Turn the db off and take a backup using `pg_dump`
4. [Upgrade the cluster](https://gist.github.com/delameko/bd3aa2a54a15c50c723f0eef8f583a44)

**Comment by nikolai-b** [comment]
We also will need to install the [postgres repo](https://www.postgresql.org/download/linux/ubuntu/)

- Create the file /etc/apt/sources.list.d/pgdg.list and add a line for the repository
`deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main`
- Import the repository signing key, and update the package lists
`wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -`
`sudo apt-get update`

Then likely we will need to download the postgres-9.6-postgis-2.3 manually https://packages.ubuntu.com/artful/postgresql-9.6-postgis-2.3

**Comment by nikolai-b** [comment]
Hmm, it makes me think for all that effort then we might be better to upgrade the OS on the server.
@mvl22 [Ubuntu 14.04 LTS](https://wiki.ubuntu.com/Releases) is end of life in April 2019, can we think about upgrading?

**Comment by nikolai-b** [comment]
@mvl22 just reminding you (and myself) that we probably want to think about upgrading to the next Ubuntu version soon.

**Comment by mvl22** [comment]
@nikolai-b Yes, let's have a phone call on this soon. I agree this is now very high priority.

**Comment by nikolai-b** [comment]
Done

**Comment by mvl22** [comment]
We now need to move to 18.04 as a next phase.
