### ISSUE TITLE
Threads showing as 'unread' even when reader was the last person to post

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#791]
Threads I have posted in are showing as blue 'unread' even when there are no new posts. I have to go in to 'read' them to remove blue text. Makes it hard to determine what actually needs my attention.

**Comment by nikolai-b** [comment]
Duplicate of #787
Thanks for reporting again as I hadn't yet deployed the fix but it is fixed on the live site now.
