### ISSUE TITLE
Photomap integration needs 'Add by ID' box

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#795]
User request:

"I'd use the cyclestreets feature of cyclescape but it's impossible to directly submit a link or even a photo ID number. Using the map to try and pick out the right photo is also very difficult and very annoying."

I have found this myself - it's good to have the photomap integration, but in crowded areas, it won't always show the desired photo. It would be useful to have a box in the corner that specifies an ID that can be picked out.

**Comment by mvl22** [comment]
This works fine, but on pressing the button and having the form pre-filled, could you also do a move-map and zoom-in to the returned lat-lon?

**Comment by nikolai-b** [comment]
I've added the move to the searched for feature lat-lon and open the popup.  Let me know if your happy to deploy these.

**Comment by mvl22** [comment]
Thanks, good to deploy.
