### ISSUE TITLE
Direct Messages should not be subject to moderation

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#802]
Direct Messages can end up in moderation.

Obviously it is possible that a spammer could be sending spam, but I think it's best for a user to have a 'Report spam' or 'Block user' type control for stopping that, in the case of Direct messages.

**Comment by nikolai-b** [comment]
Should we go with "Block user's direct messages" as "Block user" might make them think they will not see their messages elsewhere?

**Comment by mvl22** [comment]
> Should we go with "Block user's direct messages" as "Block user" might make them think they will not see their messages elsewhere?

Yes, that is definitely much clearer than what I suggested!
