### ISSUE TITLE
Suggested minor change to the email footer

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#804]
Hi,

Emailed posts now end with:

> You can stop following this thread by visiting
> http://www.cyclescape.org/threads/....

> Cyclescape discussion thread:
> http://www.cyclescape.org/threads/....

But people wanting to look at the thread are likely to click on the first link they see, without reading the advice.
I suggest that these two options should be presented in the reverse order - so that the _positive_ action precedes the _negative_ one.

**Comment by mvl22** [comment]
Yes, that seems sensible to reverse.
