### ISSUE TITLE
Richtext editor fixes

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#808]
Following the implementation of #390, this thread is for fixing up issues relating to that.

**Comment by mvl22** [comment]
If the user adds extra paragraphs of space at the end, these need to be trimmed. In the attached screenshot (where I've highlighted text and then screenshotted the left side, to maintain confidentiality), you can see there are empty paragraphs. Obviously I realise this isn't a simple trim() type arrangement as these are whitespace within paragraph tags.

![screen shot 2018-12-10 at 18 18 32](https://user-images.githubusercontent.com/361423/49752374-1d3c5a80-fca8-11e8-8c00-e1c9a1668b44.png)

**Comment by mvl22** [comment]
The link style in the stylesheet seems to have broken - we now get an ugly line under it, which I'm pretty sure wasn't there before:

![screen shot 2018-12-10 at 18 20 49](https://user-images.githubusercontent.com/361423/49752480-68566d80-fca8-11e8-9d53-e16cac71a8ee.png)

**Comment by nikolai-b** [comment]
@mvl22 I've fixed stripping the empty trailing paragraphs, I've done it by parsing the input as HTML.  This will mean text emails will also be parsed so `>` will be `&gt;` and `&` as `&amp;`.

When we send emails we will then convert the HTML back into plain text but it was the only way I could think of fixing it.

**Comment by mvl22** [comment]
Problem with e-mail transmission it seems:

![screen shot 2018-12-10 at 23 16 26](https://user-images.githubusercontent.com/361423/49767754-b0d65100-fcd1-11e8-84a0-92512203fbf2.png)

**Comment by mvl22** [comment]
The search page formatting isn't right any more - the text seems notably less well-formatted, e.g. line spacing.

![screen shot 2018-12-10 at 23 44 09](https://user-images.githubusercontent.com/361423/49768859-bafa4e80-fcd5-11e8-8e8e-20c3138d855c.png)

**Comment by nikolai-b** [comment]
Mind if we split these into separate issues.  It makes it much easier to track.
