### ISSUE TITLE
Problem with e-mail transmission - alt text of image at start

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#809]
![screen shot 2018-12-10 at 23 18 55](https://user-images.githubusercontent.com/361423/49767830-04e13580-fcd2-11e8-9235-7db66ac78cfd.png)

At `/threads/227#message_58133`.

_Originally posted by @mvl22 in https://github.com/cyclestreets/cyclescape/issues/808#issuecomment-446011382_

**Comment by nikolai-b** [comment]
@mvl22 hmm, is this happening with all emails (is it happening with yours)?  That looks like a multipart boundary but that is all handled by a library so it would be strange if it had issues.  Could you forward me the email?

**Comment by nigeldeakin** [comment]
I read email using gmail.com, and I see an image (presumably the profile image)

**Comment by gravitystorm** [comment]
I see the same garbage. It's the alt text of an image, and images are blocked by default so the alt text shows up.

The image is the profile picture as part of the [_user_link.html.haml](https://github.com/cyclestreets/cyclescape/blob/staging/app/views/notifications/_user_link.html.haml#L3) partial

The `image_tag` helper [creates an alt text by default](https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/image_tag) from the filename. So setting an (empty?) alt text here would be a solution.

For reference, here's some slightly obscured message source:

```
----==_mimepart_5c0ea9e518928_22554bd0ac387f4
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
<head>
<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
</head>
<body>
<img src="http://www.cyclescape.org/media/W1siZiIsInByb2ZpbGVfcGljdHVyZXMvMjg0Lzg1YS8yODQ4NWE4YjZjMTBkYTRiMTg2YTZjOTU5ODc2YjU3ZjQ2MTFmZTcxIl0sWyJwIi.........I1MHg1MFx1MDAzZSJdXQ?sha=4d4475e4e9f7729a" alt="W1siziisinbyb2zpbgvfcgljdhvyzxmvmjg0lzg1ys8yodq4nwe4yjzjmtbkytrimtg2ytzjotu5odc2yju3zjq2mtfmztcxil0swyj........ilci1mhg1mfx1mdazzsjdxq?sha=4d4475e.......a" />
<span class='name'>
<a href="http://www.cyclescape.org/users/.../profile">...</a>
</span>
 [Committee]
 added <a href="http://www.cyclescape.org/threads/...#message_5...">a message</a> to the thread

<div></div>
```

You can see the alt text in the image link.
