### ISSUE TITLE
Richtext issues: URLs are no longer being auto-hyperlinked

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#811]
If a link is added, but the user doesn't explicitly turn it into a link (which most won't realise to do), this is no longer clickable:

![screen shot 2018-12-11 at 15 57 45](https://user-images.githubusercontent.com/361423/49812517-892cca80-fd5d-11e8-922a-44c9abde1bce.png)

In `/threads/2260#message_58143`.

**Comment by mvl22** [comment]
Is `auto_link` safe against double-hyperlinking, i.e. a URL inside an `<a>` tag in HTML not then also having the autolinking done?

**Comment by nikolai-b** [comment]
Very good question: https://www.staging.cyclescape.org/threads/1852#message_23418
