### ISSUE TITLE
Digest e-mail not coming through

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#814]
As reported in `/threads/227#message_58178`:

"My daily (overnight ...) digest of posts to subscribed threads hasn't been emailed to me - since the weekend (ie when some other stuff changed)?"

**Comment by nikolai-b** [comment]
After investigating I think this is due to the same issue as #825 there was a problem with running scheduled jobs.  This has now been fixed but if this happens again please re-open.
