### ISSUE TITLE
Clarify effect of deleting user next to the deletion control

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#815]
A group admin has asked:

"What effect (if any) would deleting a user have on their old posts? We've had a request to remove someone but I thought I'd better check what the delete user button would do before using it, so for now I've just set them to no notifications."

in `/threads/227#message_58148`.

We need to add a sentence clearly outlining the effect of deletion be added in the relevant part of the interface, i.e. where that deletion takes place, so that the effect of it is totally clear and expected.

I believe we're using fake delete, and then presumably setting the name to "A deleted user" or similar, but it would be helpful for text to confirm this or otherwise.

**Comment by nikolai-b** [comment]
Is this on `admin/users/<user-id>/edit`?  Group committee members can remove users from the group but only admins can delete users.  We have "Cancel my account" at `settings/edit` which we should probably point users to if they request to be deleted.  I'm unsure we really need admin's to delete users as it does the exact same thing as "Cancel my account" .

Deleting the user removes their subscriptions, name and groups permanently.  It obfuscates their name as you suggest.

I can add help text says: 
> This will set the name to "User id (deleted)", remove their groups, thread subscriptions, profile, and offers to lead threads permanently.  It will leave their messages and issues.

**Comment by mvl22** [comment]
Please do add that help text (it's nice and clear, thanks) on any page where deletion is possible.
