### ISSUE TITLE
Richtext issues: Text sometimes appears in large font - possibly being processed as text not HTML

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#820]
The first message of the thread at `/threads/4467#message_58197` has the wrong size text. I suspect it has somehow ended up being submitted to the server as plain text rather than HTML.

(I have obviously blanked out one side of the text for the sake of the group's privacy.)

![screen shot 2018-12-12 at 19 23 16](https://user-images.githubusercontent.com/361423/49893540-915f3580-fe43-11e8-9831-3b8582f7bdd4.png)

Reported at `/threads/227#message_58144` where the user said:

"Also, something is happening to some posts. Martin's last post in the Street Parking thread for example. The text is much larger than usual, as though the website has posted it as a photo caption."

This refers to my message within (i.e. not at the start of) this thread: `/threads/4274#message_58138` (which again here I'm showing partially blanked for privacy):

![screen shot 2018-12-12 at 19 30 24](https://user-images.githubusercontent.com/361423/49893866-64f7e900-fe44-11e8-9400-8c323f4b2e40.png)

**Comment by nikolai-b** [comment]
Hmm, have you got any ideas?  The message body does look like it is plain text but I don't know why.  I can't replicate it.  I can reject messages that don't have a `<p>` tag but that doesn't really help much...

**Comment by nikolai-b** [comment]
@mvl22 did you post using incoming mail?
![image](https://user-images.githubusercontent.com/361423/49893866-64f7e900-fe44-11e8-9400-8c323f4b2e40.png)

**Comment by mvl22** [comment]
Good point, no I didn't...

**Comment by nikolai-b** [comment]
I could try disable the "Post message" button until tinymce is initialised.

**Comment by mvl22** [comment]
> I could try disable the "Post message" button until tinymce is initialised.

Yes, that would be sensible anyway. I suspect it is something to do with the JS not being ready, perhaps on very long pages where presumably `onready` takes a while to fire.

**Comment by mvl22** [comment]
I notice that in `/threads/2947#message_58276` the source code does actually have line-breaks in. So it looks as if the incoming side may be fine but there's something going wrong in the outgoing.

**Comment by nikolai-b** [comment]
I _think_ this is when users paste content from elsewhere, it looks like tinymce doesn't strip tags by default.  Whitelisting valid HTML and using the past plugin seems to stop it but there might be other ways so if other messages come in could you ask the poster what they did?

**Comment by georgio8** [comment]
> On 19 Dec 2018, at 01:27, Martin <notifications@github.com> wrote:
> 
> We're still seeing nasty cases of line-breaks absent, which is continuing to generate quite a bit of user feedback. Is the above rolled out now?
> 
> Latest case, which is particularly bad, is at /threads/4481#message_58415.
> 
whereas the email version arrived in people’s mailboxes perfectly laid out. 

I have ‘censoring’ rights but I don’t want to delete and post it again for fear of filling mailboxes with duplicates. Can the existing post be fixed?

George

**Comment by mvl22** [comment]
This remains a significant problem for almost every time one particular user posts:

`/threads/4503`

and as you can see, makes things difficult to read.

Looking at the HTML, it is putting the whole thing in a single div with line breaks, rather than creating paragraph breaks.

The user posts both by e-mail and via the website.

**Comment by georgio8** [comment]
This is happening to my posts too, e.g.:
https://www.cyclescape.org/threads/4071#message_58813

**Comment by mvl22** [comment]
> This is happening to my posts too

So we can help debug this, as none of us have so far been able to reproduce it:

1) Are you posting by e-mail or via the website?

2) If using the website, do you get the richtext controls above the box appearing correctly?

**Comment by georgio8** [comment]
It happens only when I post using email. When I use the website the edit box seems complete and the formatting is good.

Here is the raw text of the message body as sent by Apple Mail:

From: George Coulouris <george@coulouris.net>
Message-Id: <4B61E3D3-5D34-436E-BCD5-3A03DC7F550C@coulouris.net>
Content-Type: multipart/alternative;
	boundary="Apple-Mail=_C821455D-1F0C-4FD1-A56E-B7CC812C2296"
Mime-Version: 1.0 (Mac OS X Mail 11.5 \(3445.9.1\))
Subject: Re: [Cyclescape] Tufnell Park junction revisions
Date: Fri, 11 Jan 2019 11:08:02 +0000
X-Universally-Unique-Identifier: F3FDDE93-2216-40F7-A367-E6B47731406C
In-Reply-To: <message-2b5549ff76097bbbac46@cyclescape.org>
Cc: Alison Dines <alisondines@clara.co.uk>,
 Kate Calvert <kate@katecalvert.me.uk>,
 David Lincoln <getdavidlincoln@hotmail.com>
To: message-2b5549ff76097bbbac46@cyclescape.org
References: <thread-bab5dab05b26cbfc95c8@cyclescape.org>
 <message-b520ebfa59baed9ff4b2@cyclescape.org>
 <message-9270443eb7aec7c339b1@cyclescape.org>
 <message-21a57a23e0d383501e59@cyclescape.org>
 <message-021d9181436bbc3e93b8@cyclescape.org>
 <message-d58b1bd424913623f1c0@cyclescape.org>
 <message-f9f467d740b549e286b0@cyclescape.org>
 <message-0dd7678e26c08f6e6f60@cyclescape.org>
 <message-886933e26fba55e276ce@cyclescape.org>
 <message-3d4c3c48c7c2300eb5ff@cyclescape.org>
 <message-6954cf8a5d48fb442179@cyclescape.org>
 <message-07c6d029f44ff2abf8bf@cyclescape.org>
 <message-61da9021bf31236baa3b@cyclescape.org>
 <message-e4861ab88652ff5e40bf@cyclescape.org>
 <message-7e7d4b241b0ad11cf554@cyclescape.org>
 <message-fe17f2e9d193ab5de2ad@cyclescape.org>
 <message-cbe3fdaf800d826c2655@cyclescape.org>
 <message-667981593a3b99dd3e3d@cyclescape.org>
 <message-e83b4db1b6eb212c257c@cyclescape.org>
 <message-2b5549ff76097bbbac46@cyclescape.org>


--Apple-Mail=_C821455D-1F0C-4FD1-A56E-B7CC812C2296
Content-Transfer-Encoding: quoted-printable
Content-Type: text/plain;
	charset=utf-8

 I shall be drafting a response to Camden on behalf of CCC. The deadline =
for responses is 25 January. I understand Cycle Islington are also =
preparing a group response and I hope to coordinate our responses, =
perhaps using this Cyclescape thread.
As Jean=E2=80=99s latest post on Cyclescape indicates, we shall be =
taking a line that adding motor traffic lanes while doing nothing =
significant to make cycling through the junction safer and more =
attractive is unacceptable.=20
As she mentions, Camden Council's draft Transport Strategy =
<https://consultations.wearecamden.org/supporting-communities/camden-trans=
port-strategy/> includes objectives that provide a powerful platform for =
demanding that all significant changes to the road network should to =
make cycling more attractive.=20
Of course we should also aim for the two councils to receive as many =
individual responses as possible arguing for better provision for =
cycling.


--Apple-Mail=_C821455D-1F0C-4FD1-A56E-B7CC812C2296
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html;
	charset=utf-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; =
charset=3Dutf-8"></head><body style=3D"word-wrap: break-word; =
-webkit-nbsp-mode: space; line-break: after-white-space;" class=3D""><div =
class=3D"">&nbsp;I shall be drafting a response to Camden on behalf of =
CCC. The deadline for responses is 25 January. I understand Cycle =
Islington are also preparing a group response and I hope to coordinate =
our responses, perhaps using this Cyclescape thread.</div><div =
class=3D"">As Jean=E2=80=99s latest post on Cyclescape indicates, we =
shall be taking a line that adding motor traffic lanes while doing =
nothing significant to make cycling through the junction safer and more =
attractive is unacceptable.&nbsp;</div><div class=3D"">As she =
mentions,&nbsp;<a =
href=3D"https://consultations.wearecamden.org/supporting-communities/camde=
n-transport-strategy/" class=3D"">Camden Council's draft Transport =
Strategy</a>&nbsp;includes objectives that provide a powerful platform =
for demanding that all significant changes to the road network should to =
make cycling more attractive.&nbsp;</div><div class=3D"">Of course we =
should also aim for the two councils to receive as many individual =
responses as possible arguing for better provision for =
cycling.</div><div class=3D""></div><br class=3D""></body></html>=

--Apple-Mail=_C821455D-1F0C-4FD1-A56E-B7CC812C2296--

**Comment by nikolai-b** [comment]
@mvl22 and @georgio8 thank you for that.  Emails with <div> tags were not being converted to <p> tags.  I'm not sure how easy it will be to correct this for previous messages though but it should not happen again now.
