### ISSUE TITLE
E-mail interface broken

### ISSUE THREAD

**Issue by mrd** [cyclestreets/cyclescape#825]
Just realised over the past few days that all my e-mails to cyclescape threads have gone into the great bitbucket in the sky.

**Comment by mrd** [comment]
Every single e-mail that I've sent to any thread on cyclescape has not appeared on cyclescape. For example, thread 4458 is one of many that I sent e-mail to several times over the past few days and none have appeared (until I realised it and went to the web interface to send an urgent message instead).

I don't know if it is a server configuration error or a software bug.

**Comment by nikolai-b** [comment]
@mrd thanks.  I will look in the logs now I have an thread number. If the message isn't sensitive would you mind posting the full email source here? 

To get to the source on Gmail:
![screenshot from 2018-12-14 09-52-10](https://user-images.githubusercontent.com/6289830/49996167-35e99080-ff86-11e8-9b64-652559fc0aad.png)

**Comment by mrd** [comment]
[original_msg.txt](https://github.com/cyclestreets/cyclescape/files/2679721/original_msg.txt)

**Comment by nikolai-b** [comment]
@mrd very sorry. There was a config change that broke our email processing.  The emails were still all there but not being processed.  Sadly with other changes we've made recently they are not very nicely formatted.  I'm working on fixing that now.
