### ISSUE TITLE
Richtext issues: First message of new thread misformatted

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#828]
The new thread form is text, but is being treated as HTML, so ends up without linebreaks and other formatting. See: `/threads/4478#message_58309`.

Either we need to keep it as text, and reformatted it as HTML, or (probably more consistent) upgrade the form to the richtext format.

**Comment by nikolai-b** [comment]
![screenshot from 2018-12-16 20-05-53](https://user-images.githubusercontent.com/6289830/50058287-04cbb480-016e-11e9-8d83-eae90fa20098.png)

It is treated as HTML (although the label is pushing the menu over).  This is most likely a dup of #820
