### ISSUE TITLE
Crash in changing user email address

### ISSUE THREAD

**Issue by davidearl** [cyclestreets/cyclescape#837]
I tried changing email address for a user on `/admin/users/2135-NAME/edit` but it crashed with 

    We're sorry, but something went wrong.
    We've been notified about this issue and we'll take a look at it shortly.

The user has forgotten their password and can no longer access the old email account to do a reset.

**Comment by davidearl** [comment]
Previously she had created an entirely separate account with the new email (which is not helpful as all the previous account context would have been lost) so I deleted that account first. It may be that old account with what would have been a duplicate email address may still have some kind of presence that was causing the crash when I tried to change the address on the older account. Or maybe changing user details just doesn't work.

**Comment by mvl22** [comment]
> that old account with what would have been a duplicate email address may still have some kind of presence

Yes, the users table uses the fake-delete model (see `deleted_at`) as shown at:
https://github.com/cyclestreets/cyclescape/blob/staging/db/schema.rb#L663-L691

and the e-mail has a unique index:
https://github.com/cyclestreets/cyclescape/blob/staging/db/schema.rb#L695

so that combination is almost certainly causing the problem.

**Comment by davidearl** [comment]
Just to get things sane again, would you be able to swap the email
addresses around (directly in the database by a backdoor) so the live
record has the deleted's email address and vice-versa? Then she'll be able
to continue without having to wait for a bug fix. Kiu is stuck at the
moment.

**Comment by mvl22** [comment]
I've e-mailed details.
