### ISSUE TITLE
Search broken following OS upgrade

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#838]
`/overview/search?issue_page=3&library_page=2`
`/overview/search?utf8=✓&query=cambridge&button=`
etc., is giving a 500.

Rollbar is giving a report:

`RSolr::Error::ConnectionRefused: Connection refused -{:data=>"fq=type%3AMessageThread&fq=status_s%3Aapproved&fq=%28location_ll%3A%5B55.811398724120366%2C-3.654571533203>
+OR+group_id_i%3A6%29&fq=privacy_s%3A`

**Comment by nikolai-b** [comment]
Fixed in https://github.com/cyclestreets/cyclescape-chef/commit/98d43321b8207a232109490f9490f8f6ac0d69fe

**Comment by mvl22** [comment]
Is this taking time to catch up? Almost no results are coming through:

`/overview/search?utf8=%E2%9C%93&query=station&button=#thread-results`

**Comment by nikolai-b** [comment]
Redeployed again. I think I was missing something with chef. Fixed in https://github.com/cyclestreets/cyclescape-chef/commit/03cba0b6d73155f8793001d06f7161527f311cc9
