### ISSUE TITLE
Threads not being marked as read

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#839]
Threads are not being marked as read, as shown by the lack of colour change on the My Cyclescape page.

**Comment by mvl22** [comment]
This seems OK now actually. Was this part of the upstart change?

**Comment by nikolai-b** [comment]
Yes, the way we ran background services (a.k.a. any non-webserver process) was controlled by upstarted and in the new ubuntu that is replaced by systemd.  Fixed in https://github.com/cyclestreets/cyclescape-chef/commit/98d43321b8207a232109490f9490f8f6ac0d69fe
