### ISSUE TITLE
My Cyclescape page is very slow to load

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#844]
About 5 seconds to load.

Could we do some profiling again to see which component(s) are being slow?

(Perhaps do this after the Rails 5 upgrade as that will presumably change things or might have optimisations.)

**Comment by nikolai-b** [comment]
I've spent some time on this and I can't seem to see a simple reason.  I've reduced the number of ajax requests that might help.  Is the page still noticeably slow?
