### ISSUE TITLE
Upgrade OS to Ubuntu 18.04

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#847]
We now need to move to 18.04 as a next phase.

_Originally posted by @mvl22 in https://github.com/cyclestreets/cyclescape/issues/789#issuecomment-479660583_

P.S. We need our hosting provider to upgrade the space on the boot partition.

**Comment by nikolai-b** [comment]
@mvl22 from what I understand this is likely to be the next big ticket.  Once I've got a working version on my local virtualbox then I can try staging but we might need more disk space.  Do we want use this as a chance to do a fresh install of staging on a new machine?  Then when it comes to production we can also switch over to a new machine (with a bigger `/boot` partition)?

**Comment by mvl22** [comment]
> Do we want use this as a chance to do a fresh install of staging on a new machine?

Yes, let's do that.

**Comment by mvl22** [comment]
Isn't this now resolved?

**Comment by nikolai-b** [comment]
Yes
