### ISSUE TITLE
Timestamp problem

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#849]
There is something strange going on with timestamps on cyclescape posts. (a post from hours ago says 1 min and then one says 6 then the next 1 and then 34 minutes...).

Another user has also posted about this.

Presumably a Rails 5 -related regression.

**Comment by nikolai-b** [comment]
Mind adding a link or some IDs?

**Comment by mvl22** [comment]
`/threads/4742` has postings with the timestamps not logically correct in ordering terms.
