### ISSUE TITLE
Street View post option is hit by Google's charging

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#853]
Any attempt to use the 'Street view' option generates the dreaded 'This page can't load Google Maps correctly. '

Potential workarounds that occur to me, none very satisfactory: 
1. delete the option 
2.  suggest posting a URL link for the user to follow
3. suggest posting a screen grabbed image
4. Add a feature enabling users to add a Google API Key that will be applied whenever the user is logged in (i.e. stored in their profile info).

**Comment by mvl22** [comment]
I believe there is a setting and we do have a key for other sites, so I think I need to add that and then enable the URL.

**Comment by georgio8** [comment]
Of course, that would be better than any of my workarounds, but risks incurring charges to CycleStreets.

George

**Comment by nikolai-b** [comment]
I've set the key in the config

**Comment by mvl22** [comment]
I've updated the key - not sure where that one came from, but I've used the one in our Google Console and enabled the domain.

The Street View integration is now working again properly.
