### ISSUE TITLE
Typo in the new Issue creation dialogue

### ISSUE THREAD

**Issue by georgio8** [cyclestreets/cyclescape#854]
"Start a conversion (thread) on this, describing your thoughts on what should be done. " 
should read: Start a conversation

Even coders are subject to the ridiculously aggressive auto spelling correction!

**Comment by nikolai-b** [comment]
Thank you for noticing.  I usually don't amend text, my spelling leaves a lot to be desired, so I copied from the specification verbatim:
https://github.com/cyclestreets/cyclescape/issues/660#issuecomment-440492080 :laughing:

**Comment by mvl22** [comment]
Oops on my part!
