### ISSUE TITLE
Grafana Monitor query error

### ISSUE THREAD

**Issue by Chongtianlin** [cyclestreets/cyclescape#858]
When I select more than 60 nodes in my Grafana Monitor,
![image (1)](https://user-images.githubusercontent.com/17676461/60529804-ffbef480-9cbc-11e9-8911-f8fda4d05f61.png)
it prompts the error below:
![image](https://user-images.githubusercontent.com/17676461/60529805-ffbef480-9cbc-11e9-8c62-44c179ad80e3.png)

I want to know if anyone has encountered this issue before or have any insight.

**Comment by RonZhang724** [comment]
I am experiencing the same problem...
