### ISSUE TITLE
Logrotation

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#863]
In production we had 30 Gb of logs.  We are currently rotating logs [weekly](https://github.com/cyclestreets/cyclescape/blob/staging/config/environments/production.rb#L35) but we should stop and instead set up a logrotate config in chef.

**Comment by mvl22** [comment]
Yes. I'm not bothered about Rails logs, which in my view can be discarded periodically. I do not want to lose Apache log data though, as they enable proper usage statistics.

Apache logs when compressed should be highly efficient - certainly nothing like 30GB when compressed.

**Comment by mvl22** [comment]
Thanks - that should avoid disk space becoming exacerbated unnecessarily.

**Comment by nikolai-b** [comment]
Yes, I was shocked at the disk usage. Most of the log size was from before  a2e5f40 when the logs were far more verbose.
