### ISSUE TITLE
Thread colour not changing colour after being read

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#864]
Threads are not being marked as being red again.

**Comment by nikolai-b** [comment]
Thanks, I'll try look this evening. Is it all threads?

**Comment by mvl22** [comment]
Thanks; please do push this into master.

**Comment by nikolai-b** [comment]
Already done! It is in master and on live site now.

**Comment by mvl22** [comment]
This is now resulting in the thread time ago not showing, with the real time instead. `jtimeago(...).timeago` on the My Cyclescape page.
