### ISSUE TITLE
/user/locations/new broken

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#866]
High priority problem:

`/user/locations/new` is broken.

Sorry I didn't spot this when checking over the Rails 5 change.

**Comment by nikolai-b** [comment]
It was only broken in https://github.com/cyclestreets/cyclescape/commit/0a30b189bfd68a8c1d36913e4f82629fe1e5c46a#diff-74ed903b3af00d9d4a83341628dce02fR3, not the Rails 5 upgraded.  I'll try to add a spec for that page.
