### ISSUE TITLE
E-mail gateway stuck

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#868]
User feedback:

`E-mail gateway seems to be stuck again - haven't seen my messages pop up in a long time.`

**Comment by nikolai-b** [comment]
Have you been getting emails @mvl22?  I've redeployed with a change in chef which might fix it but I couldn't see what was wrong, it looked like emails have been sent.

**Comment by mvl22** [comment]
Just to confirm that e-mails are going out fine.

I think the issue is processing of incoming messages.

**Comment by mvl22** [comment]
> I think the issue is processing of incoming messages.

Just to say that a message I e-mailed into the system got through fine. So I think this is working. I'll check with the original reporter.

**Comment by nikolai-b** [comment]
This was very likely because we started the new server which marked some mail as read. Please open a new issue if this happens again.
