### ISSUE TITLE
Warn on navigating away from incomplete reports

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#87]
Check if a user really wishes to leave a half-complete issue report

**Comment by nikolai-b** [comment]
@mvl22 now this is just the case of adding a class to the form as in
https://github.com/cyclestreets/cyclescape/blob/master/app/views/user/locations/_form.html.haml#L1
do we want that or should I close this?

**Comment by mvl22** [comment]
Yes - that kind of warning should basically happen for issue, planning application clone, and discussion thread forms.
