### ISSUE TITLE
Planning app search isn't being updated

### ISSUE THREAD

**Issue by mrd** [cyclestreets/cyclescape#871]
Hi - looking at the Planning App tab of the overview, I haven't seen any new planning apps show up here since mid-August.

I think something broke during a server upgrade?

It's getting urgent now.

**Comment by nikolai-b** [comment]
Thanks @mrd for the bug report. This was fixed in https://github.com/cyclestreets/cyclescape/commit/1c29aefe36dadb88b60320bf8b6cef1f52d35a22. PlanIt changed to start redirecting http calls to https.
If you notice any problems please do raise a bug straight away, thanks!

**Comment by mvl22** [comment]
I'm surprised that Rails wouldn't be following a standard HTTP redirect.

**Comment by nikolai-b** [comment]
I use the library [`excon`](https://github.com/excon/excon) and I set it to [explicitly](https://github.com/cyclestreets/cyclescape/blob/master/lib/planning_application_worker.rb#L25) not follow redirects.

**Comment by mvl22** [comment]
> I set it to explicitly not follow redirects.

OK, that makes sense - I suppose that ensures we end up noticing any changes and can thus update the code, rather than continuing to run deprecated URLs.
