### ISSUE TITLE
Staging email being sent

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#873]
It looks like staging is sending out live emails.  I've no idea how it was configured to stop this before (or I've forgotten) but given email has often been something we'd like to test I suggest we take this opportunity to actually send live email in staging but all to an address we control.  There is a gem [sanitize email](https://github.com/pboling/sanitize_email/) that seems to do it.  What do you think  @mvl22? Something like "staging-email at ..cyclescape.org" perhaps?

**Comment by mvl22** [comment]
Urgh, that is definitely not good. I always assumed that staging was immune from this.

Yes, I agree that is a good idea. Where should mail to that go?

**Comment by nikolai-b** [comment]
It was immune but I don't know how.  As the new staging server is sending email maybe it was a  config that was not in chef.

I'm happy for the mail to be forwarded to us, presumably can change the config later.
