### ISSUE TITLE
File uploads broken: "Component file can't be blank"

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#876]
File uploads aren't now working.

Selecting a file, adding a caption, and then clicking submit gives "Component file can't be blank" at the top of the page, very quickly.

**Comment by nikolai-b** [comment]
Thanks, fixed in 18014c0dd56f75def5abf9847a9bc72f9a27fff3 and deployed

**Comment by mvl22** [comment]
Thanks - works now.
