### ISSUE TITLE
Groups should have logos

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#89]
A committee member should be able to upload a logo for the group, and have it used in their group profile.

**Comment by mvl22** [comment]
We now have images in, so hopefully this is the same thing, just showing as another part of the page.

http://camcycle.cyclescape.org/

**Comment by nikolai-b** [comment]
Do we have a design for this?

**Comment by mvl22** [comment]
Don't think so.

I recommend we get #41 in place first before adding this.

**Comment by mvl22** [comment]
I think we should simply make this a second image to be uploaded above the current picture - i.e. logo then picture.

**Comment by mvl22** [comment]
I'm finding that this isn't actually giving good results - see:
https://camcycle.cyclescape.org/

where this file:

![square_dutch_bike89x100](https://user-images.githubusercontent.com/361423/36345705-ee898bd6-1427-11e8-9b2a-e60263a68e84.png)

results in that wrongly-resized and clipped image.

**Comment by nikolai-b** [comment]
The resizing is correct, the image that you've uploaded (89x100) is quite far from the 330x192 suggestion and is resizing and clipping as best it can.  It is the same adjustment that is applied to the group picture.

I've changed the resizing on the logo to allow the height to vary to keep the aspect ratio and to resize only if the width is > 330.  It might be worth playing about with a few images, the imagemagick options are http://markevans.github.io/dragonfly/imagemagick and I believe they are pretty much the same as the command line options http://www.imagemagick.org/Usage/resize/

Let me know if that is what your after, maybe we should change it elsewhere?

**Comment by mvl22** [comment]
I think this behaviour is correct now - if the image is smaller than the suggested it should just be shown as-is.
