### ISSUE TITLE
Standardize message thread edit form

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#890]
Only committee members can edit a message thread but bizarrely they can assign it to any group, not just ones they are in.

_Originally posted by @nikolai-b in https://github.com/cyclestreets/cyclescape/issues/241#issuecomment-555064397_

**Comment by mvl22** [comment]
Thanks.

Is this being implemented only in the view, rather than the model though? Shouldn't the model be providing the correct set?

Could you include a test for the negative case that, at code-level, the system should be refusing a change?
