### ISSUE TITLE
Library search is broken

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#892]
The search should update the library items but it does not submit via AJAX.
![Screenshot from 2019-11-25 15-34-27](https://user-images.githubusercontent.com/6289830/69554039-14b46100-0f99-11ea-9ede-389baafcf193.png)

Likely due to the change to `rails-ujs` (instead of `jquery-ujs`).  I much prefer to fix this if it went along with the way library items were added being redesigned.

**Comment by mvl22** [comment]
Currently this now results in a new window opening, showing the JSON

`/library/search.json?utf8=%E2%9C%93&query=test`
