### ISSUE TITLE
Editing versions / emails

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#899]
If we implement #895 do we want to send a email notifications when issue/threads are edited?

We could introduce versions similar to how github show the edited dropdown:

![Screenshot from 2019-12-19 22-09-40](https://user-images.githubusercontent.com/6289830/71213772-5d1b2200-22ac-11ea-83c8-f4ea1f0234e0.png)

but obviously that would be quite a bit more work.  This was brought up in https://github.com/cyclestreets/cyclescape/issues/587 so I guess we should solve them all together.

**Comment by mvl22** [comment]
> If we implement #895 do we want to send a email notifications when issue/threads are edited?

No, that seems overkill. Those receiving e-mail notifications when a message comes through will just find that the subject title has changed. The threading work done a few years ago will ensure that the mails remain correctly threaded, so those that really care or are unsure can just enable threading and see the history of the title.

Thread title tracking would require a new data structure, which seems a bit overkill to me. While the Github system is good, I think there is enough logging in place such that if there were really some kind of abusive use it could be tracked down. I think in general users will do the right thing, and the 24 hour limit system available only to the original poster provides more than sufficient safeguard here.

> This was brought up in #587 so I guess we should solve them all together.

I think message content changing is a completely separate issue, and is a complete can of worms. We should just deal with thread title, which to me is a straightforward and uncontroversial change.
