### ISSUE TITLE
Remove remaining modal dialog(s)

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#901]
There is currently a very nasty legacy modal dialog remaining, when creating an issue.

This should be replaced with a standard page, containing the same content, as the forthcoming redesign will almost certainly split this out.

This could be at e.g. `/issues/<id>/newthread` or similar.

![Screen Shot 2020-01-02 at 17 41 34](https://user-images.githubusercontent.com/361423/71682318-34545b80-2d87-11ea-88d1-02c95896f1ad.png)

I believe this is the last modal, but if any more are still present, they should similarly be removed.

**Comment by mvl22** [comment]
Ah, our good old friend the Library has one too:

![Screen Shot 2020-01-02 at 17 46 51](https://user-images.githubusercontent.com/361423/71682539-ec820400-2d87-11ea-892a-0a281cfd8324.png)

**Comment by nikolai-b** [comment]
So your suggestion would be to remove the modal and these a new page instead?

**Comment by mvl22** [comment]
Yes, the long New Thread box is practically a great big page already.

**Comment by mvl22** [comment]
All working fine, and good improvement. Please do merge to live.
