### ISSUE TITLE
Hashtags not working

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#910]
Text hashtags like #test (added I think in issue #613) are no longer working.

**Comment by nikolai-b** [comment]
They work as expected as far as I can tell:

https://www.staging.cyclescape.org/threads/4835#message_64579

To quote https://github.com/cyclestreets/cyclescape/issues/613#issuecomment-295490216

> We also should restrict this feature to groups only, i.e. so that auto-created hashtag listings for a particular hashtag only join those messages of that group. Otherwise we could end up with common hashtags joining messages from far-flung bits of the country within a group's discussion, which is almost certainly not wanted.

So maybe the complaint was about a thread that was not owned by a group, e.g.
https://www.staging.cyclescape.org/threads/4866#message_64578

**Comment by mvl22** [comment]
> a thread that was not owned by a group

Yes, that was the problem. Confirmed fine.
