### ISSUE TITLE
On mobile, set the list of users subscribed to a thread to be auto-hidden by default

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#916]
On mobile, the list of users subscribed to a thread ends up dumped at the bottom of the screen as a great big list.

In practice, this feature is rarely used but is useful to have when needed. However, at present, it is very dominant, and it makes scrolling all the more difficult.

The change is to replace the list (starting with the first person shown, so leaving the Owner and any Thread leader) so that the list becomes a single entry, and says e.g. "63 people subscribed", and when that is clicked on, the whole list appears as at present. In other words, the 63 people are collapsed into a single box which is expanded when clicked on.

![Screen Shot 2020-01-16 at 19 09 33](https://user-images.githubusercontent.com/361423/72554953-99ce3f00-3893-11ea-825d-f96794090f7b.png)

**Comment by nikolai-b** [comment]
Can this wait till we have started the redesign or #591?  I can do it now but it would mean I'd just be writing custom CSS and creating more problems for later.

**Comment by mvl22** [comment]
This is not dependent on the redesign.

**Comment by nikolai-b** [comment]
Yes but it will require me to add to custom CSS to make the animation nice and JS whereas framework: https://getbootstrap.com/docs/4.0/components/collapse/ or https://material-ui.com/components/lists/#nested-list or https://semantic-ui.com/modules/accordion.html#/examples I'd just add classes, data-attributes.  It also manages `aria-expanded` etc..  Yes I can do all these things but once we decide on a framework then I don't have to, it'd just be the case of using existing components.

**Comment by mvl22** [comment]
Obsoleted by #1003.
