### ISSUE TITLE
API for search issues

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#921]
The StreetFocus integration needs an API so that we can search for issues.

**Comment by nikolai-b** [comment]
So you want to add a search term to: https://www.cyclescape.org/api#!/issues/getApiIssues

Do you want the title and the issue body searched?

**Comment by mvl22** [comment]
Sorry, yes, spec wasn't clear. Basically just a name search, giving the same result as the Issues tab at:

https://camcycle.cyclescape.org/overview/search?utf8=%E2%9C%93&query=chisholm+trail&button=#issue-results

which presumably searches title and issue body indeed.

**Comment by nikolai-b** [comment]
This is not equivalent as the order will not be the same but I've added a search term.

**Comment by mvl22** [comment]
This seems to give the same result 6 times over:

`/api/search?sources=cyclescape,cyclestreets&q=chisholm%20trail&limit=12&countrycodes=gb%2Cie`
