### ISSUE TITLE
Add tag map

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#927]
On https://www.cyclescape.org/tags/cyclepath make the page full screen and stick in a map of all the tags, add a popup with a link to the issue.  From #923

**Comment by nikolai-b** [comment]
I've made the map fixed (sticky) so it moves with the page.  Is that what you wanted?

![Screenshot_2020-02-29 Cyclescape(2)](https://user-images.githubusercontent.com/6289830/75616143-73afe600-5b45-11ea-8e07-03018c1bb910.png)

**Comment by mvl22** [comment]
> I've made the map fixed (sticky) so it moves with the page.

Can you clarify sorry?

I would allow it to be slippy so that people can browse beyond the group's area for those tags, out of curiosity.

**Comment by mvl22** [comment]
Oh, as in CSS position fixed. Err, yes, probably that will be fine.

I'll check on staging when it lands there.

**Comment by mvl22** [comment]
I see this is working. The layout is acceptable, and obviously will be handled properly with the new design.

Could you make the overlay colour (currently light blue) on the full map be the same as the individual maps (currently dark gray) - see the difference:

![Screen Shot 2020-03-11 at 22 53 52](https://user-images.githubusercontent.com/361423/76471691-4e479580-63eb-11ea-9773-93879878ed82.png)
