### ISSUE TITLE
Add centre to issue API

### ISSUE THREAD

**Issue by nikolai-b** [cyclestreets/cyclescape#928]
Add property `center` to the geoJSON issue API which is the centre of the issue even if it a line, poly line, area etc.

**Comment by mvl22** [comment]
Good, thanks. That should enable me to replace all this!

https://github.com/cyclestreets/streetfocus/blob/master/js/streetfocus.js#L1131-L1212

**Comment by mvl22** [comment]
Do push this one live if you're happy that it's stable.

**Comment by mvl22** [comment]
This gives the output in a rather unhelpful format, and includes id and properties which are not relevant.

![Screen Shot 2020-03-08 at 18 24 57](https://user-images.githubusercontent.com/361423/76168729-46c58980-616a-11ea-8e7b-30aa66bf9e48.png)

Can this be changed to be simply:

```
centre: {
    lon: 0.14115,
    lat: 52.19999,
}
```

**Comment by nikolai-b** [comment]
Done in https://github.com/cyclestreets/cyclescape/commit/5b92269d4f1a788ed07401bb9dea172d3543285c
