### ISSUE TITLE
Lines and areas should have icons on the map

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#93]
The design calls for lines and icons to have symbols based on their tags, just as points have a marker symbol that can have an icon too.

---

This turns out to be a massive timesink. OpenLayers doesn't (as of 2.11) support multiple symbolizers, and although hinted at it doesn't appear that drawing an icon for an area is possible.multiple geojson layers would mess up the popup handling.

**Comment by nikolai-b** [comment]
Not sure we want this now, can re-open with updated designs if we do.

**Comment by mvl22** [comment]
Yes, fine to have this closed for now. I think in general the question of how area-based issues are represented on the map needs a fundamental rethink, as it clearly doesn't work well now as soon as there are more than a couple of areas.
