### ISSUE TITLE
Close thread button doesn't appear consistently

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#937]
For reasons I can't spot, I'm not seeing the Close thread button on this thread:

`/threads/38`

More examples are: 893, 995, 1022.

As a sysadmin, and a committee member, surely this should be possible?

**Comment by nikolai-b** [comment]
I never added a special rule for admins so you could only close (or open) threads that you had posted on. Fixed now.

**Comment by mvl22** [comment]
Great; thanks. Keen to get this one pushed live, as have been working on tidying up a lot of data in a group I'm a committee member of.
