### ISSUE TITLE
E-mail for poll type needs to include a link to the message

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#939]
According to
https://camcycle.cyclescape.org/threads/227#message_70529

the e-mail that goes out for a poll doesn't actually include a link to it.

**Comment by nikolai-b** [comment]
https://www.staging.cyclescape.org/rails/mailers/thread_mailer_mailer/new_poll_message

Like all new notifications the footer contains 

> From Cyclescape discussion thread. 

with a link to the message.  This is what we do on other message types, would you like poll to do something different or should we change the footer?

**Comment by mvl22** [comment]
I think on this specific case, we should repeat the link in the body of the message - it feels a bit odd otherwise to have a poll which is just text.

Add something like:

Vote at:
<link-with-#message-id>

after the options.
