### ISSUE TITLE
open_threads API parameter is not helpful for issues with zero threads

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#942]
The aim of the open_threads parameter is to enable filtering out those issues whose threads have all been closed, i.e. the issue is resolved.

However, it turns out this means that issues with zero threads (i.e. no discussion yet) are also therefore treated as resolved!

Can I suggest we remove `open_threads` and replace it with just `is_open`/`open_issues`/`open_only` or whatever?

There is no backwards compatibility as the only API user of this is code under my control that I can easily change.

**Comment by nikolai-b** [comment]
I'm using an inner join so zero threads do not count as open.  I'm not checking if the thread is public though...

**Comment by mvl22** [comment]
Could you revert this specific change - it has suddenly vastly reduced the number of issues.

**Comment by mvl22** [comment]
Great, thanks.
