### ISSUE TITLE
Message posting broken: Rakismet.key is not defined

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#946]
Posting a message is failing in Chrome. The console shows:

`POST https://camcycle.cyclescape.org/threads/227/messages 500 (Internal Server Error)`

Reports from at least one other user have this also.

**Comment by mvl22** [comment]
The Rails `production.log` gives:

```
I, [2020-04-14T09:33:51.538098 #22027]  INFO -- : method=POST path=/threads/227/messages format=js controller=MessagesController action=create status=500 error='Rakismet::Undefined: Rakismet.key is not defined' duration=10.42 view=0.00 db=1.11 params={"utf8"=>"✓", "message"=>{"body"=>"<p>Thanks - we'll check out what the problem was.</p>\r\n<p><a href=\"https://github.com/cyclestreets/cyclescape/issues/945\">https://github.com/cyclestreets/cyclescape/issues/945</a></p>", "photo_messages_attributes"=>{"0"=>{"base64_photo"=>"", "retained_photo"=>"", "caption"=>""}}, "cyclestreets_photo_messages_attributes"=>{"0"=>{"photo_url"=>"", "loc_json"=>"", "icon_properties"=>"", "cyclestreets_id"=>"", "caption"=>""}}, "street_view_messages_attributes"=>{"0"=>{"caption"=>"", "heading"=>"", "location_string"=>"", "pitch"=>""}}, "link_messages_attributes"=>{"0"=>{"url"=>"", "title"=>"", "description"=>""}}, "deadline_messages_attributes"=>{"0"=>{"all_day"=>"0", "deadline"=>"", "title"=>""}}, "document_messages_attributes"=>{"0"=>{"retained_file"=>"", "title"=>""}}, "map_messages_attributes"=>{"0"=>{"loc_json"=>"", "caption"=>""}}, "action_messages_attributes"=>{"0"=>{"description"=>""}}, "poll_messages_attributes"=>{"0"=>{"question"=>"", "poll_options_attributes"=>{"0"=>{"option"=>"", "_destroy"=>"false"}, "1"=>{"option"=>"", "_destroy"=>"false"}}}}, "thread_thread_leaders"=>{"description"=>""}}, "photo_id"=>[""], "commit"=>"Post Message", "thread_id"=>"227"}
F, [2020-04-14T09:33:51.538814 #22027] FATAL -- :   
F, [2020-04-14T09:33:51.538862 #22027] FATAL -- : Rakismet::Undefined (Rakismet.key is not defined):
```

**Comment by mvl22** [comment]
Messages submitted via e-mail are coming through.

(Which suggests that they are not going through Akismet?)

**Comment by mvl22** [comment]
Presumably this broke at
https://github.com/cyclestreets/cyclescape/commit/e02f346a19238ee4d59c465fd06406695ce473a3#diff-f6863b15788e85c331d8738c51ccf3ccL3-R10

NB I notice that has the http rather than https version of www.cyclescape.org noted.

**Comment by nikolai-b** [comment]
Thanks @mvl22, I still don't full understand why the ENV wasn't passed to the passenger application but I've reverted the changes.  Having Rails read files with secrets feels brittle but given the damage caused by my attempt to fix it I'll leave it rest for now.

We agreed that messages via email were very unlikely to be spam, they also don't have IP or user agent so the Akismet was likely to be inaccurate:
https://github.com/cyclestreets/cyclescape/commit/72570f3c35fcfd63d5d44ded7d14ce3aedf6b774

I'll update the URL to https version, thanks.
