### ISSUE TITLE
Use cyclestreets to help draw routes

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape#95]
When drawing a route, the user can do start/end and cyclestreets figures it out.

This would be most useful for helping users create their commuting routes when setting their user locations.

**Comment by jf1** [comment]
I've just made a similar suggestion in the survey, for setting the location of an issue, where the experience and solution is the same.

Start-end then auto-route might not give the exact route the user wants so:
Ultimately, the ability to 'drag' a mid-point on the auto-route (as per google maps) would be a great way to specify the correct route entirely within CS.
Initially, the option to upload a gpx file would suffice, and this feature would always be needed in case there's something unrouteable using OSM data or more easily created elsewhere eg plotaroute.com

**Comment by mvl22** [comment]
Implemented with the new place-setting UI last year.
