### ISSUE TITLE
Colchester BC's planning applications on PlanIt are not on Cyclescape

### ISSUE THREAD

**Issue by stevenmos** [cyclestreets/cyclescape#952]
I thought I'd open a new issue to avoid polluting the more general issue, #715.

e.g. a search for [LB/COL/00/0142](https://www.planit.org.uk/planapplic/Colchester/LB/COL/00/0142/), or [200534](https://www.planit.org.uk/planapplic/Colchester/200534/) on Cyclescape does not return either.

Whereas, Reading's [200534](https://www.planit.org.uk/planapplic/Reading/200534/) is [shown](https://www.cyclescape.org/planning_applications/uid/reading/200534)

**Comment by mvl22** [comment]
Could you kindly repost it on that ticket?
