### ISSUE TITLE
Latest read message not being saved

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#955]
User 2616 reporting that this thread in particular isn't getting the latest read message position (scroll) being set:

/threads/5219

Can you check this feature hasn't broken again somehow? Would be good to ensure there is a test in place.

**Comment by mvl22** [comment]
Hmm, I've just had this myself on
/threads/832

**Comment by nikolai-b** [comment]
There are tests in place [[1](https://github.com/cyclestreets/cyclescape/blob/staging/spec/controllers/message_threads_controller_spec.rb#L8-L51)], [[2](https://github.com/cyclestreets/cyclescape/blob/staging/spec/features/message_thread/thread_views_spec.rb)] and [[3](https://github.com/cyclestreets/cyclescape/blob/staging/spec/workers/thread_recorder_spec.rb)] cover most of it.  There have been no deploys but we have been having cases of `No space left on device - fork(2)` so my guess is there have been some intermittent disk issues.

I hope https://github.com/cyclestreets/cyclescape/commit/d84ac42af97fbf137f11a5de415562a2c4351e72 will go some way to solving this

**Comment by nikolai-b** [comment]
@mvl22 is this any better?  I can't reproduce but I think this might be an infrastructure issue.

**Comment by nikolai-b** [comment]
This is likely due to the same bug as in #961
