### ISSUE TITLE
Load Google Street View only on demand

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#960]
It seems we're possibly currently using about £127 of Google Maps API usage from Cyclescape a month, which is unsustainable.

I notice that the StreetView JS file is loaded on each thread page, even if there are no visible instances, because this is in the form and appears in the HTML:

`<div class='streetViewPano' data-lat='0.1434443440551711' data-long='52.1993464843147' id='newStreetViewPano'></div>`

even though it is hidden under the tabs. 

Can we set this to be loaded only on demand, i.e. if someone actually clicks on the Street View message type response button?

Currently the JS code (and the pano div) is added statically into the page, on every thread load. I think we need to set this so it dynamically adds the JS file, only when the Street View reply type is clicked on. The div itself presumably can stay, as it is presumably meaningless without the JS file.

Obviously visible message postings can be left-as is.

**Comment by mvl22** [comment]
This also might be an option, for the main message postings:

https://walterebert.com/playground/wpo/google-maps/

**Comment by nikolai-b** [comment]
I can't test this locally as we have disabled our API key on localhost so pushing to staging a bit earlier than I'd like.

**Comment by nikolai-b** [comment]
@mvl22 when you get a chance can you let me know if this is reducing our API usage?

**Comment by mvl22** [comment]
Initial indications are that this is making a significant difference - thanks.

I should have some better data later this week.

Cc: @si-the-pie for info.
