### ISSUE TITLE
Latest thread position consistently failing in long thread

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#961]
In thread 832 I’m consistently being taken to this message (or possibly the one before, not sure):

/threads/832#message_71922

and not the latest message. This is a very long thread, so I wonder if there is something failing after a certain number of posted messages.

**Comment by mvl22** [comment]
Thanks; this wasn't my imagination then!

**Comment by mvl22** [comment]
What was wrong with the new method?

Incidentally, IE11 can now be the minimum supported browser - older IE versions are no longer supported by Microsoft.

**Comment by nikolai-b** [comment]
It changed how the scrolling animation and I feared that was a hot topic.  I was prepared to do that when I thought it worked but   moving from `$(document).ready` -> `$(window).on('load', ...)` is that actual fix so I went back to the old scrolling animation.  Happy to use `scrollIntoView` if you think it won't upset anyone.

**Comment by mvl22** [comment]
Ah good point; yes, let's not open that can of worms...
