### ISSUE TITLE
Add option for feedback to go to CycleStreets API

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#965]
Currently feedback goes to the local database, which should stay.

It would be useful to have a settings-based option for it additionally to be posted to the CycleStreets API:
https://www.cyclestreets.net/api/v2/feedback.add/
as that is our main user feedback handling method.

**Comment by nikolai-b** [comment]
What feedback are we talking about here?

**Comment by mvl22** [comment]
That which is posted at /site/comments/new .

**Comment by nikolai-b** [comment]
Ok, so it would be

```json
{"type": "bug", "comments": "the thing they type", "url": "the cyclescape URL?", "name": "name if known", "email": "also if known"}
```

**Comment by mvl22** [comment]
Almost - yes. Can you use `type: other`.

**Comment by nikolai-b** [comment]
```
curl -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-API-KEY: APIKEY' \
  --data '{"type":"other","comments":"Test comment from Cyclescape","url":"https://www.cyclescape.org/overview","name":"cyclescape","email":"test@example.com"}' 'https://api.cyclestreets.net/v2/feedback.add'
```

Returns 

```
{
    "error": "No data received. This API call requires a POST operation."
}
```

Would you mind giving an adding an cURL in the documentation @mvl22?

**Comment by mvl22** [comment]
> Would you mind giving an adding an cURL in the documentation @mvl22?

Can you clarify?

The documentation already states that you need to use POST rather than GET.

**Comment by nikolai-b** [comment]
Yes, which I am doing but it still isn't working.  FYI  from the cURL manual:

```
-d/--data <data>

(HTTP) Sends the specified data in a POST request to the HTTP server
```

**Comment by mvl22** [comment]
Hmm odd.

I still didn't understand the question though:

"Would you mind giving an adding an cURL in the documentation"

**Comment by nikolai-b** [comment]
"Would you mind giving an adding an cURL in the documentation"

A [cURL](https://curl.haxx.se/) command I can copy and paste, like with [Cyclescape API](https://www.cyclescape.org/api#!/constituencies/getApiConstituencies) when you click "Try it out!" then you get a curl command.

 
To me the documentation:

---

> Example which adds an item of routing feedback.
```
POST https://api.cyclestreets.net/v2/feedback.add

(
	[type] => routing
	[itinerary] => 40669517
	[comments] => The second section of the route is failing to use the nearby cycle path which avoids a dropped kerb.
	[email] => me@example.com
	[name] => Susan Smith
)
```

> Result:

```
{
    "id": "7462"
}
```
---

The result is clearly JSON but to me it is not very clear what the format is of the POST body.  The example body is surrounded in `()`, do these have a meaning?  The `[type] => routing` should I be using `[]` and `=>` in my body?  I've assumed that the endpoint accepts JSON and expects

```
{"type":"other","comments":"Comment text","url":"https://www.cyclescape.org/overview","name":"Nikolai","email":"nikolai@example.com"}
```

but is not like the example given.  It would be useful to have the actual data being POSTed, I also tried the format in the example:

```
 curl -H 'Accept: application/json' -H 'X-API-KEY: APIKEY' \
  --data '(
        [type] => other
        [comments] => Test comment from Cyclescape
        [url] => https://www.cyclescape.org/overview
        [name] => cyclescape
        [email] => test@example.com
)' 'https://api.cyclestreets.net/v2/feedback.add'
```
but that gives 
```
{
    "error": "The data received was incomplete; both type and comments must be submitted."
}
```
.  This is the same error I get when I don't specify the `Content-Type`.

**Comment by nikolai-b** [comment]
Any update on this @mvl22 ?

**Comment by mvl22** [comment]
Basically it needs to be the same format as if you were posting a standard HTML webform. I'm not sure exactly what that looks like in cURL, but just to clarify it is definitely not JSON.

I.e. the equivalent of

/v2/feedback.add?type=other&comments=..

but using POST instead of GET for those parameters.
