### ISSUE TITLE
Postcode finder UI at /user/locations/new is broken

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#971]
Something seems to be going wrong with the UI at `/user/locations/new`.

I type in a postcode, e.g. CB1 2PY. The constituencies and wards boxes give me no results shown.

**Comment by nikolai-b** [comment]
Both work for me, would you mind adding a video or explain what is different?

![postcode](https://user-images.githubusercontent.com/6289830/98482296-67ae1500-21f8-11eb-8198-09d76fc9cc57.gif)

**Comment by mvl22** [comment]
As I mentioned, the constituencies and wards boxes give me no results shown. I can see your video similarly doesn't show them either.

**Comment by nikolai-b** [comment]
Sorry, yes I see that. I'll try to update as I think it should be easy
