### ISSUE TITLE
Sign out states insecure page

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#973]
I can't immediately see why, but on Chrome at least, if you attempt to sign out, you get a page:

> The information that you’re about to submit is not secure
> Because the site is using a connection that’s not completely secure, your information will be visible to others.

with the Inspector showing "(blocked:other)":

![sign out](https://user-images.githubusercontent.com/361423/102341976-85596180-3f90-11eb-9e0d-644a899a0a68.png)

I have disabled Adblock and that also happens.

**Comment by nikolai-b** [comment]
I can reproduce the error in my version of Chrome but I think I've fixed the issue.  It has been deployed to master, please close this if it fixed for you @mvl22

**Comment by mvl22** [comment]
Thanks; yes, that's fixed now. Thanks for finding that bit of legacy crud.
