### ISSUE TITLE
'Area too large' when trying to create a new issue

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#976]
When trying to create a new issue there is now the problem with Cyclescape alert saying the selected area is too large. 
![Screenshot 2021-01-28 at 18 19 28](https://user-images.githubusercontent.com/11997264/106182175-63115100-6196-11eb-928d-c5845d402bea.png)

**Comment by nikolai-b** [comment]
You need to create a smaller issue.  If the issue size is greater than 0.1 square degrees we don't allow it. I don't really know what 0.1 square degrees looks like but basically you should be able to create small issues but not very large ones.

**Comment by mvl22** [comment]
Roxanne, I suspect slightly smaller will be fine.

**Comment by roxannedebeaux** [comment]
I disagree with this. It is a fundamental problem with Cyclescape that
there are topics that are not specific to any area at all. They are a
general issue that applies to the whole campaign so it should work for the
whole campaign area like it used to.


Kind Regards
Roxanne De Beaux
Executive Director
Camcycle

07482 735174
camcycle.org.uk  <https://www.camcycle.org.uk/>

**Comment by mvl22** [comment]
There hasn’t been any change at all. Area-wide issues continue to be supported given their need. I suspect the area drawn was just very slightly larger than the limit.
