### ISSUE TITLE
Another UK wide issue created?

### ISSUE THREAD

**Issue by soundplusfury** [cyclestreets/cyclescape#978]
It looks like another UK wide issue. 

https://camcycle.cyclescape.org/threads/5593

**Comment by nikolai-b** [comment]
Thanks, not sure if that is the correct link as the issue looks local to Cambridge:
![Screenshot from 2021-02-03 21-50-19](https://user-images.githubusercontent.com/6289830/106814156-e1279900-6669-11eb-9a05-f89fbd65d2ed.png)

**Comment by soundplusfury** [comment]
I flagged it as it seemed to come from an LCC person. Maybe I was wrong.

**Comment by nikolai-b** [comment]
There is no constraint on where users can create issues. A user is allowed to create issue outside of their groups area.
