### ISSUE TITLE
Hyperlinking giving incorrect link

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape#981]
In `/threads/5624#message_81334`, the visible message text shows a link ending /252677 (which is correct), but the link underneath that visible URL is similar but ends with /252683.

**Comment by mvl22** [comment]
Actually, I wonder if this was actually entered that way originally as a richtext submission, rather than the hyperlinking being automatic. Could you check in the database, and if so, close this issue without action?

**Comment by nikolai-b** [comment]
Checked DB and the logs, it was submitted like this.
